using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using FluentAssertions;
using OpenWSFZ.Ft8;
using Xunit;

namespace OpenWSFZ.Ft8.Tests;

/// <summary>
/// FR-029: Synthetic-signal fixture integration test — the FT8 decoder regression
/// oracle (Gate G6, NFR-016).
///
/// Each fixture is a synthetic 12 kHz mono int16 WAV produced by the clean-room
/// qa/rr-study synthesiser (GFSK, continuous phase), generated by
/// <c>qa/rr-study/gen_decoder_fixtures.py</c>. Each WAV superimposes several FT8
/// signals at distinct audio frequencies under additive Gaussian noise, using only
/// the canonical <em>fictional</em> example callsigns from the FT8 literature
/// (<c>Q1AW</c>, <c>Q1ABC</c>, <c>Q9XYZ</c>). Each WAV is paired with an answer-key
/// subset; this test asserts <see cref="Ft8Decoder.DecodeAsync"/> recovers them.
///
/// <para>These fixtures replaced the former real off-air WSJT-X "Save All"
/// recordings, which embedded the callsigns of real, non-consenting third-party
/// operators (a privacy / GDPR concern). The trade-off is deliberate: the test is
/// no longer an <em>independent</em> off-air oracle, but a regression gate over
/// known-good encodings. See MEMORY.md "ft8_lib dependency".</para>
///
/// <para><strong>This test is expected to remain GREEN.</strong> The decoder is the
/// thin C# wrapper around the reference <c>ft8_lib</c> C library (MIT / kgoba),
/// compiled as a native shared library and loaded via <c>Ft8LibInterop.cs</c>. Any
/// regression that makes this test red is a genuine defect and will block merge via
/// Gate G6 (NFR-016).</para>
/// </summary>
public sealed class RealSignalFixtureTests
{
    // ── Fixture data ──────────────────────────────────────────────────────────

    /// <summary>
    /// Provides the three committed synthetic fixture WAVs and their
    /// answer-key subsets as xUnit theory data. The cycle timestamp is cosmetic
    /// (the assertion compares decoded message text only).
    /// </summary>
    public static IEnumerable<object[]> Fixtures()
    {
        yield return new object[] { "synth-qso-01", new DateTime(2026, 5, 28, 23, 57, 45, DateTimeKind.Utc) };
        yield return new object[] { "synth-qso-02", new DateTime(2026, 5, 29,  0,  0, 30, DateTimeKind.Utc) };
        yield return new object[] { "synth-qso-03", new DateTime(2026, 5, 29,  0,  2,  0, DateTimeKind.Utc) };
    }

    // ── Gate test ─────────────────────────────────────────────────────────────

    [Theory(DisplayName = "FR-029: FT8 decoder recovers known real off-air signals from committed WAV fixture (G6 gate — NFR-016)")]
    [MemberData(nameof(Fixtures))]
    public async Task DecodeAsync_RealSignalFixture_ContainsAnswerKeyMessages(
        string fixtureId,
        DateTime cycleUtc)
    {
        // ── Load embedded WAV ─────────────────────────────────────────────────
        float[] pcm = LoadEmbeddedWav($"Fixtures/{fixtureId}.wav");

        // ── Load embedded answer-key subset ──────────────────────────────────
        string[] expectedMessages = LoadEmbeddedAnswerKey($"Fixtures/{fixtureId}.expected.txt");

        expectedMessages.Should().NotBeEmpty(
            "the answer-key file must contain at least one expected message");

        // ── Decode ────────────────────────────────────────────────────────────
        var clock   = new FakeClock(cycleUtc);
        var decoder = new Ft8Decoder(clock);
        var results = await decoder.DecodeAsync(pcm, CancellationToken.None);

        var decodedMessages = results.Select(r => r.Message).ToList();

        // ── Assert answer-key subset is recovered ─────────────────────────────
        // Each expected message must appear in the decoded results.
        // G6 gate — this assertion must remain GREEN (NFR-016).
        foreach (string expected in expectedMessages)
        {
            decodedMessages.Should().Contain(expected,
                because: $"fixture '{fixtureId}' — WSJT-X decoded '{expected}' from the same audio; " +
                         $"a correct FT8 decoder must recover it. " +
                         $"Currently decoded: [{string.Join(", ", decodedMessages)}]");
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static float[] LoadEmbeddedWav(string resourceSuffix)
    {
        using Stream stream = OpenEmbeddedResource(resourceSuffix);
        return WavReader.Read(stream);
    }

    private static string[] LoadEmbeddedAnswerKey(string resourceSuffix)
    {
        using Stream stream = OpenEmbeddedResource(resourceSuffix);
        using var reader    = new StreamReader(stream);
        return reader.ReadToEnd()
                     .Split('\n', StringSplitOptions.RemoveEmptyEntries)
                     .Select(l => l.Trim())
                     .Where(l => l.Length > 0 && !l.StartsWith('#'))
                     .ToArray();
    }

    private static Stream OpenEmbeddedResource(string resourceSuffix)
    {
        Assembly asm  = typeof(RealSignalFixtureTests).Assembly;
        string asmName = asm.GetName().Name!;

        // Resource names use dots as separators and replace slashes
        string resourceName = $"{asmName}.{resourceSuffix.Replace('/', '.')}";

        Stream? stream = asm.GetManifestResourceStream(resourceName);
        if (stream is null)
        {
            // Try alternative naming (underscores may be preserved)
            string[] allNames = asm.GetManifestResourceNames();
            stream = allNames
                .Where(n => n.EndsWith(resourceSuffix.Replace('/', '.'), StringComparison.OrdinalIgnoreCase))
                .Select(n => asm.GetManifestResourceStream(n))
                .FirstOrDefault(s => s is not null);
        }

        return stream
               ?? throw new InvalidOperationException(
                   $"Embedded resource '{resourceName}' not found. " +
                   $"Available: [{string.Join(", ", asm.GetManifestResourceNames())}]");
    }
}
