#!/usr/bin/env python3
"""Route B2 Phase B -- B-orig-A, the waterfall-origin-convention arm.

Spec: qa/rr-study/2026-08-21-1412-architect-to-qa-origin-convention-finding-and-spec-b-orig-a.md
Authorised by the Captain 2026-08-21 ("go with b for now" -- explain the one-symbol
displacement before fixing around it).

STATUS (spec Sec.0): FIRST GATED ARM in this thread -- Sec.6.4 defines a real ROW 1-4
with PASS/FAIL semantics (unlike B-pos-A, which was diagnostic-only). ROW 0g is still
NOT re-read, re-metriced or amended -- it stands FIRED, task 4.3 stays VOID, ROW 3 (the
Phase-1 ROW, unrelated numbering) is not declared, Route B2 is not dead. No src/native
edit, no rebuild, no push, no merge -- HK-011 not engaged (synth + the two existing
diagnostic exports + a caller-side loop, same discipline as B-pos-A/Phase A). B3
(out_diag) stays HELD, not built here. This arm does NOT authorise changing design.md
D1 by itself -- ROW 1 firing only makes the Sec.5 ruling text ready for the Captain.

Question (spec Sec.1, Sec.6.1): the Architect's derivation says the waterfall index
that ft8_extract_llrs_at reads is NOT raw-PCM time -- it runs exactly ONE FT8 symbol
AHEAD of it (monitor.c's look-back window, Sec.1.3), so the GRID path is the displaced
one and the COHERENT path (raw-PCM sample space) is correct. B-pos-A could only measure
the *difference* between the two paths' optima on REAL rows with no true dt. This arm
tests the asymmetric, falsifiable claim directly against KNOWN GROUND TRUTH on synth:
does grid's own-best cell land at k_true+2 quanta while coherent's lands at k_true+0?

Design (spec Sec.6.2): synthetic only, reusing phase_a_deconfounding.py's SNR-ladder
calibration (HK-018, imported not reimplemented) and synth/encoder + coherent_llr_ctypes
verbatim. NO real-row population helper is touched anywhere in this module -- limit=
cannot bite (HK-021(i)); N_TRIALS=100 trials are independent by construction (distinct
messages, independent noise draws, fixed seed), no clustering, none imported.

Truth axis (Sec.6.3 ROW 0b, HK-026): t_true is MEASURED per trial from the rendered
PCM's own energy onset (measure_onset_s below) -- a smoothed-power threshold crossing
on the CLEAN (noiseless) render, entirely decoder-independent (no lattice, no
extractor call, no ft8_lib symbol whatsoever). dt_cmd is never taken as truth directly;
it is only checked for agreement against the measured onset.

Preconditions (Sec.6.3), evaluated in order, each a mechanical STOP:
  ROW 0a  argmin resolvable -- a trial where grid's OR coherent's n_err argmin ties
          across >=2 cells is UNDECIDABLE and excluded from both G and C. If more than
          10% of trials are undecidable -> pre-specified remedy (recalibrate the SNR
          operating point per Phase A Sec.0.1, repeat once) -> if still >10%, VOID.
  ROW 0b  truth axis measured, not asserted -- if fewer than 95% of trials have
          |t_true - dt_cmd| <= 0.5 quantum (0.04s), VOID (the truth axis is not
          identifiable and every downstream number is meaningless).
  ROW 0c  optima interior -- if |mode(G)| or |mode(C)| > 3 (the +/-4 sweep boundary),
          widen by 2 quanta each side and re-run ONCE; if still boundary, VOID.

ROWs (Sec.6.4, strictly ordered, mutually exclusive, exhaustive) -- see evaluate_row().

NFR-021: all messages here are synthetic (Q1AW-prefixed callsigns generated by
r2_sign_test._message_for_trial), never a real corpus row -- the privacy policy's own
synthetic-callsign exception applies throughout; nothing real-callsign-bearing is
touched by this module.
"""
from __future__ import annotations

import os
import statistics as st
import sys
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(REPO_ROOT, "qa", "cycleframer-alignment-replay"))
sys.path.insert(0, os.path.join(REPO_ROOT, "qa", "rr-study", "n1-extract-llrs-at-position"))
sys.path.insert(0, os.path.join(REPO_ROOT, "qa", "rr-study", "p-live-population"))
_SYNTH_ROOT = os.path.join(REPO_ROOT, "qa", "rr-study")
sys.path.insert(0, _SYNTH_ROOT)
sys.path.insert(0, HERE)

import p23_common as P  # noqa: E402
from extract_llrs_ctypes import FTX_LDPC_N, BUFFER_SAMPLES, hard_decision_ber  # noqa: E402
from run_stage1 import DEFAULT_DLL_PATH  # noqa: E402
from r2_sign_test import _message_for_trial  # noqa: E402 -- reused verbatim (HK-018)
from coherent_llr_ctypes import CoherentExtractLLRs, CURRENT_DLL_SHA256, CURRENT_SHIM_VERSION  # noqa: E402
from results_guard import guard_paths  # noqa: E402 -- N14
import phase_a_deconfounding as PHASE_A  # noqa: E402 -- SNR-ladder calibration, reused verbatim

SEED = 20260821  # this arm's own seed (session date, HK-017-style provenance)
NOISE_SEED_BASE = SEED + 900_000  # distinct from Phase A's +500_000 and B-pos-A's own 20260821

BASE_FREQ_HZ = 1500.0    # nominal grid frequency -- exact lattice point (n=0), NEVER swept
SAMPLE_RATE_HZ = 12000
SYMBOL_PERIOD_S = 0.16
TIME_QUANTUM_S = 0.08
N_TRIALS = 100
N_SUBSYM = 8              # >= 8 distinct sub-symbol dt_cmd values, spec Sec.6.2
BASE_DT_S = 0.50          # comfortably inside single-slot dt_s range, well clear of dt=0 edge

M_RANGE_INITIAL = tuple(range(-4, 5))     # k_true +/- 4 quanta, 9 points (spec Sec.6.2)
WIDEN_BY = 2                              # ROW 0c widen step, spec Sec.6.3
MAX_WIDEN_STEPS_0C = 1                    # "widen ... and re-run ONCE"

UNDECIDABLE_FRAC_MAX = 0.10               # ROW 0a bar
TRUTH_TOL_QUANTA = 0.5                    # ROW 0b: |t_true - dt_cmd| <= 0.5 quantum
TRUTH_AGREEMENT_MIN_FRAC = 0.95           # ROW 0b bar
FRAC_AT_MODE_BAR = 0.80                   # ROW 1 bar

ONSET_THRESHOLD_FRACTION = 0.10           # measure_onset_s: fraction of peak smoothed power
ONSET_SMOOTH_WINDOW_S = 0.003             # ~3ms smoothing window

SECONDARY_M_RANGE = tuple(range(-6, 3))   # spec Sec.6.5: grid fixed @ k+2, coherent @ k+2+m


def _n_err(llr, true_bits) -> int:
    """Same convention throughout this thread: ber is an exact k/174 by construction."""
    return int(round(hard_decision_ber(llr, true_bits) * FTX_LDPC_N))


def _hard_bits(llr):
    return [1 if v > 0.0 else 0 for v in llr]


# =====================================================================================
# ROW 0b -- decoder-independent energy-onset detector (HK-026)
# =====================================================================================

def measure_onset_s(clean: np.ndarray, fs: int) -> float:
    """Finds the first sample where the CLEAN render's smoothed instantaneous power
    crosses ONSET_THRESHOLD_FRACTION of its own peak, with linear sub-sample
    interpolation across the crossing. No decoder, no lattice, no ft8_lib call, no
    knowledge of the FT8 symbol structure is involved -- this is purely a threshold on
    the rendered waveform's own energy envelope (HK-026: the instrument under test
    cannot be used to bound its own blind spot). A small, constant detection lag from
    modulator.py's 10ms raised-cosine fade-in is expected and is identical across every
    trial (same fade shape, same threshold) -- it is well inside ROW 0b's 0.04s (0.5
    quantum) tolerance and does not bias the RELATIVE (per-trial) truth measurement."""
    power = clean.astype(np.float64) ** 2
    win = max(1, int(round(ONSET_SMOOTH_WINDOW_S * fs)))
    if win % 2 == 0:
        win += 1
    kernel = np.ones(win, dtype=np.float64) / win
    smoothed = np.convolve(power, kernel, mode="same")
    peak = float(np.max(smoothed))
    if peak <= 0.0:
        raise RuntimeError("onset detector: rendered signal has zero power -- degenerate render")
    threshold = ONSET_THRESHOLD_FRACTION * peak
    above = np.where(smoothed >= threshold)[0]
    if above.size == 0:
        raise RuntimeError("onset detector: no samples crossed the threshold -- degenerate render")
    idx = int(above[0])
    if idx == 0:
        return 0.0
    y0, y1 = smoothed[idx - 1], smoothed[idx]
    frac = 0.0 if y1 == y0 else (threshold - y0) / (y1 - y0)
    frac = min(max(frac, 0.0), 1.0)
    return (idx - 1 + frac) / fs


# =====================================================================================
# trial construction -- messages, commanded dt across a full symbol, measured truth
# =====================================================================================

def build_trials(log) -> list[dict]:
    from synth import encoder  # noqa: PLC0415

    frac_values = tuple(round(v, 6) for v in np.linspace(0.0, SYMBOL_PERIOD_S, N_SUBSYM,
                                                           endpoint=False))
    log("  sub-symbol dt_cmd fractions (%d distinct values spanning one %.2fs symbol): %s"
        % (N_SUBSYM, SYMBOL_PERIOD_S, frac_values))

    trials = []
    for i in range(N_TRIALS):
        msg = _message_for_trial(i)
        dt_cmd = round(BASE_DT_S + frac_values[i % N_SUBSYM], 6)
        clean = encoder.encode_message(msg, base_freq_hz=BASE_FREQ_HZ, dt_s=dt_cmd,
                                        snr_db=None, seed=0, sample_rate_hz=SAMPLE_RATE_HZ)
        clean = np.ascontiguousarray(clean, dtype=np.float64)
        assert clean.shape == (BUFFER_SAMPLES,), clean.shape
        t_true = measure_onset_s(clean, SAMPLE_RATE_HZ)
        k_true = int(round(t_true / TIME_QUANTUM_S))
        trials.append({
            "index": i, "message": msg, "dt_cmd": dt_cmd,
            "clean": clean.astype(np.float32), "t_true_s": t_true, "k_true": k_true,
        })
    log("  built %d trials (messages distinct via r2_sign_test._message_for_trial, "
        "N_SUBSYM=%d recurring dt_cmd values, BASE_DT_S=%.3f)" % (N_TRIALS, N_SUBSYM, BASE_DT_S))
    return trials


def check_row0b(trials: list[dict], log) -> dict:
    diffs = [abs(t["t_true_s"] - t["dt_cmd"]) for t in trials]
    tol_s = TRUTH_TOL_QUANTA * TIME_QUANTUM_S
    n_agree = sum(1 for d in diffs if d <= tol_s)
    frac_agree = n_agree / len(trials)
    passed = frac_agree >= TRUTH_AGREEMENT_MIN_FRAC
    log("  ROW 0b: truth axis (measured onset vs commanded dt_cmd) -- tol=%.3fs (%.1f quantum), "
        "n_agree=%d/%d (%.3f), bar=%.2f -> %s"
        % (tol_s, TRUTH_TOL_QUANTA, n_agree, len(trials), frac_agree, TRUTH_AGREEMENT_MIN_FRAC,
           "PASS" if passed else "FAIL"))
    log("  ROW 0b: max |t_true - dt_cmd| observed = %.4fs, mean = %.4fs"
        % (max(diffs), float(st.mean(diffs))))
    return {"n_agree": n_agree, "n_total": len(trials), "frac_agree": frac_agree,
            "tol_s": tol_s, "bar": TRUTH_AGREEMENT_MIN_FRAC, "passed": passed,
            "max_abs_diff_s": max(diffs), "mean_abs_diff_s": float(st.mean(diffs))}


# =====================================================================================
# sweep -- absolute call offset q*0.08s for q in k_true + m_range, freq fixed at n=0
# =====================================================================================

def sweep_all(ex: CoherentExtractLLRs, trials: list[dict], snr_db: float, m_range, log) -> None:
    """Populates trial['cells'][q] = {'m', 'ne_grid', 'hd_grid', 'ne_coh', 'hd_coh'} for
    every q = k_true + m, m in m_range. Full recompute (no memoisation) -- spec Sec.6.6
    budgets generously; recompute is simpler and avoids partial-memoisation bugs when
    ROW 0c widens the range."""
    from synth import channel  # noqa: PLC0415

    t0 = time.time()
    n_calls = 0
    for tr in trials:
        true_bits = ex.true_codeword(tr["message"])
        assert true_bits is not None
        noisy = channel.add_noise(tr["clean"], snr_db, NOISE_SEED_BASE + tr["index"],
                                   SAMPLE_RATE_HZ)
        noisy = np.ascontiguousarray(noisy, dtype=np.float32)
        cells = tr.setdefault("cells", {})
        for m in m_range:
            q = tr["k_true"] + m
            if q in cells:
                continue
            time_offset_s = q * TIME_QUANTUM_S
            rc_g, llr_g = ex.extract_at(noisy, BASE_FREQ_HZ, time_offset_s)
            rc_c, llr_c = ex.coherent_extract_at(noisy, BASE_FREQ_HZ, time_offset_s)
            ne_g = _n_err(llr_g, true_bits) if (rc_g == 0 and llr_g is not None) else None
            ne_c = _n_err(llr_c, true_bits) if (rc_c == 0 and llr_c is not None) else None
            hd_g = _hard_bits(llr_g) if llr_g is not None else None
            hd_c = _hard_bits(llr_c) if llr_c is not None else None
            cells[q] = {"m": m, "ne_grid": ne_g, "hd_grid": hd_g, "ne_coh": ne_c, "hd_coh": hd_c}
            n_calls += 1
    log("  swept %d new row-cells (snr_db=%.1f) in %.1fs" % (n_calls, snr_db, time.time() - t0))


# =====================================================================================
# ROW 0a -- argmin resolvable; per-trial G_i / C_i
# =====================================================================================

def _argmin_with_tie(cells: dict, key: str):
    vals = [(q, c[key]) for q, c in cells.items() if c[key] is not None]
    if not vals:
        return None, True   # no successful extraction at all -> treated as undecidable
    min_val = min(v for _, v in vals)
    winners = sorted(q for q, v in vals if v == min_val)
    tied = len(winners) > 1
    q_best = min(winners, key=lambda q: abs(cells[q]["m"]))
    return q_best, tied


def compute_argmins(trials: list[dict], log) -> dict:
    n_undecidable = 0
    for tr in trials:
        q_g, tied_g = _argmin_with_tie(tr["cells"], "ne_grid")
        q_c, tied_c = _argmin_with_tie(tr["cells"], "ne_coh")
        undecidable = tied_g or tied_c
        tr["q_grid"] = q_g
        tr["q_coh"] = q_c
        tr["undecidable"] = undecidable
        if undecidable:
            n_undecidable += 1
            tr["G"] = None
            tr["C"] = None
        else:
            tr["G"] = q_g - tr["k_true"]
            tr["C"] = q_c - tr["k_true"]
    frac_undecidable = n_undecidable / len(trials)
    log("  ROW 0a: %d/%d trials undecidable (grid-or-coherent argmin tied across >=2 cells), "
        "frac=%.3f, bar<=%.2f" % (n_undecidable, len(trials), frac_undecidable,
                                    UNDECIDABLE_FRAC_MAX))
    return {"n_undecidable": n_undecidable, "n_total": len(trials),
            "frac_undecidable": frac_undecidable, "passed": frac_undecidable <= UNDECIDABLE_FRAC_MAX}


# =====================================================================================
# mode / frac_at_mode, and ROW 0c / ROW 1-4 evaluation
# =====================================================================================

def mode_and_frac(trials: list[dict], key: str, log, label: str) -> dict:
    decidable = [tr[key] for tr in trials if not tr["undecidable"]]
    if not decidable:
        raise RuntimeError("no decidable trials for %s -- cannot compute a mode" % label)
    counts: dict[int, int] = {}
    for v in decidable:
        counts[v] = counts.get(v, 0) + 1
    mode_val = max(counts, key=lambda k: (counts[k], -abs(k)))  # tie-break: smaller |value|
    frac = counts[mode_val] / len(decidable)
    log("  %s: mode=%+d frac_at_mode=%.3f (n_decidable=%d) histogram=%s"
        % (label, mode_val, frac, len(decidable),
           {k: counts[k] for k in sorted(counts)}))
    return {"mode": mode_val, "frac_at_mode": frac, "n_decidable": len(decidable),
            "histogram": {str(k): counts[k] for k in sorted(counts)}}


def evaluate_row(mode_g: int, frac_g: float, mode_c: int, frac_c: float, log) -> tuple[int, str]:
    diff = mode_g - mode_c
    if mode_g == 2 and mode_c == 0 and frac_g >= FRAC_AT_MODE_BAR and frac_c >= FRAC_AT_MODE_BAR:
        row = 1
        text = ("CONFIRMED. The one-symbol displacement is the waterfall origin convention; "
                "the GRID path is the displaced one; coherent is correct in raw-PCM terms. "
                "The displacement is no longer unexplained. A narrow, D1-compatible origin "
                "correction becomes the named Phase B fix; B3 stays HELD; the Architect brings "
                "the Captain the Sec.5 ruling with these numbers.")
    elif diff == 2:
        row = 2
        text = ("GAP CONFIRMED, ATTRIBUTION WRONG. One symbol reproduces against truth, but not "
                "with the derived per-path attribution (mode(G)=%+d, mode(C)=%+d, frac bars not "
                "both met). The convention explanation is incomplete -> escalate; no fix is "
                "specced on this row." % (mode_g, mode_c))
    elif diff in (1, 3):
        row = 3
        text = ("QUANTITATIVELY WRONG. A displacement reproduces (mode(G)-mode(C)=%+d) but not "
                "at one symbol -> the derivation is wrong in magnitude -> escalate." % diff)
    else:
        row = 4
        text = ("NOT REPRODUCED. mode(G)-mode(C)=%+d, outside {+1,+2,+3} -> the displacement is "
                "not a property of the synthetic chain -> it is signal- or population-dependent "
                "(C4 or unnamed) -> the convention explanation is DEAD; B3 returns as the "
                "leading candidate; escalate hard." % diff)
    log("\n  ROW %d FIRES: %s" % (row, text))
    return row, text


# =====================================================================================
# secondary readout (Sec.6.5) -- NOT gated, report only
# =====================================================================================

def secondary_sign_agreement(trials: list[dict], log) -> dict:
    """Per-bit sign-agreement rate between coherent @ (k+2+m) and grid @ (k+2), as a
    function of m. Confounded by C1 (LLR fusion across n_syms) -- report the curve, draw
    NO conclusion, do not let it influence the ROW (spec Sec.6.5)."""
    log("\n" + "-" * 90)
    log("SECONDARY (Sec.6.5, NOT GATED) -- sign-agreement rate: coherent @ (k+2+m) vs "
        "grid @ (k+2), as a function of m. Confounded by C1 fusion across n_syms -- "
        "report only, no conclusion drawn, does not influence the ROW.")
    log("-" * 90)
    curve = {}
    for m in SECONDARY_M_RANGE:
        per_trial_agree = []
        for tr in trials:
            q_grid_fixed = tr["k_true"] + 2
            q_coh_m = tr["k_true"] + 2 + m
            cg = tr["cells"].get(q_grid_fixed)
            cc = tr["cells"].get(q_coh_m)
            if cg is None or cc is None or cg["hd_grid"] is None or cc["hd_coh"] is None:
                continue
            hd_g, hd_c = cg["hd_grid"], cc["hd_coh"]
            agree = sum(1 for a, b in zip(hd_g, hd_c) if a == b) / len(hd_g)
            per_trial_agree.append(agree)
        if per_trial_agree:
            mean_agree = float(st.mean(per_trial_agree))
            curve[m] = {"mean_agreement": mean_agree, "n_trials": len(per_trial_agree)}
            log("  m=%+3d  mean_sign_agreement=%.4f  (n_trials=%d)"
                % (m, mean_agree, len(per_trial_agree)))
        else:
            curve[m] = {"mean_agreement": None, "n_trials": 0}
            log("  m=%+3d  no trials with valid cells at both required offsets" % m)
    peak_m = max((m for m in curve if curve[m]["mean_agreement"] is not None),
                 key=lambda m: curve[m]["mean_agreement"], default=None)
    if peak_m is not None:
        log("  peak at m=%+d (mean_agreement=%.4f) -- derivation predicts m=-2, reported for "
            "context ONLY, not scored, not gating." % (peak_m, curve[peak_m]["mean_agreement"]))
    return {"m_range": list(SECONDARY_M_RANGE), "curve": {str(k): v for k, v in curve.items()},
            "peak_m": peak_m}


# =====================================================================================
# main
# =====================================================================================

def main() -> int:
    out_dir = os.path.join(HERE, "results")
    os.makedirs(out_dir, exist_ok=True)
    log_lines: list[str] = []

    def log(msg: str = "") -> None:
        print(msg)
        log_lines.append(msg)

    def finish(bundle: dict, code: int) -> int:
        report_path = os.path.join(out_dir, "b_orig_a_report.json")
        log_path = os.path.join(out_dir, "b_orig_a_run.log")
        guard_paths([report_path, log_path], REPO_ROOT)  # N14
        P.write_json(report_path, bundle)
        with open(log_path, "w", encoding="ascii", errors="replace") as fh:
            fh.write("\n".join(log_lines) + "\n")
        return code

    log("=" * 90)
    log("B-ORIG-A -- the waterfall-origin-convention arm (GATED: ROW 1-4, Sec.6.4)")
    log("Spec: qa/rr-study/2026-08-21-1412-architect-to-qa-origin-convention-finding-and-"
        "spec-b-orig-a.md")
    log("ROW 0g stands FIRED. Task 4.3 stays VOID. Route B2 is NOT dead. Does NOT itself "
        "amend design.md D1 -- ROW 1 only readies the Sec.5 ruling text for the Captain.")
    log("Prediction (Sec.7, NON-SCORING -- blinding compromised by Phase A Sec.0.2): "
        "ROW 1 fires ~80%.")
    log("=" * 90)

    log("\nLoading DLL: %s (pinned to CURRENT merged binary, shim %d)"
        % (DEFAULT_DLL_PATH, CURRENT_SHIM_VERSION))
    try:
        ex = CoherentExtractLLRs(DEFAULT_DLL_PATH, verify=True, expected_sha256=CURRENT_DLL_SHA256,
                                  expected_shim_version=CURRENT_SHIM_VERSION)
    except (RuntimeError, AttributeError) as e:
        log("DLL pin FAILED: %s" % e)
        return finish({"final": "dll_pin_fail", "error": str(e)}, 2)
    log("DLL pin confirmed: SHA256 %s..., shim version %d" % (CURRENT_DLL_SHA256[:16], ex.version))
    bundle: dict = {"dll_pin": {"sha256_prefix": CURRENT_DLL_SHA256[:16], "shim_version": ex.version},
                    "seed": SEED, "noise_seed_base": NOISE_SEED_BASE, "n_trials": N_TRIALS,
                    "base_freq_hz": BASE_FREQ_HZ, "base_dt_s": BASE_DT_S,
                    "time_quantum_s": TIME_QUANTUM_S}

    t0 = time.time()

    log("\n" + "-" * 90)
    log("Building %d synthetic trials (dt_cmd spans a full %.2fs symbol, freq fixed at "
        "nominal lattice point n=0) ..." % (N_TRIALS, SYMBOL_PERIOD_S))
    log("-" * 90)
    trials = build_trials(log)

    log("\n" + "-" * 90)
    log("PRECONDITION ROW 0b -- truth axis measured (decoder-independent energy onset), "
        "not asserted from dt_cmd (HK-026)")
    log("-" * 90)
    row0b = check_row0b(trials, log)
    bundle["row0b"] = row0b
    if not row0b["passed"]:
        log("\nROW 0b FAILED -- VOID, ESCALATE. The truth axis is not identifiable; every "
            "downstream number would be meaningless. STOPPING.")
        bundle["final"] = "row0b_void_escalate"
        return finish(bundle, 3)
    log("\nROW 0b PASSED.")

    log("\n" + "-" * 90)
    log("Calibrating operating SNR (Phase A's own SNR-ladder function, reused verbatim, "
        "HK-018) ...")
    log("-" * 90)
    try:
        snr_db = PHASE_A.calibrate_operating_snr(ex, log)
    except RuntimeError as e:
        log("\nCALIBRATION FAILED: %s" % e)
        bundle["final"] = "calibration_fail"
        bundle["error"] = str(e)
        return finish(bundle, 4)
    bundle["operating_snr_db"] = snr_db

    log("\n" + "-" * 90)
    log("Sweeping the initial %d-point m-range over %d trials at snr_db=%.1f ..."
        % (len(M_RANGE_INITIAL), N_TRIALS, snr_db))
    log("-" * 90)
    sweep_all(ex, trials, snr_db, M_RANGE_INITIAL, log)

    log("\n" + "-" * 90)
    log("PRECONDITION ROW 0a -- argmin resolvable")
    log("-" * 90)
    row0a = compute_argmins(trials, log)
    remedy_attempted = False
    if not row0a["passed"]:
        log("\nROW 0a FAILED on first attempt (frac_undecidable=%.3f > %.2f). Pre-specified "
            "remedy (spec Sec.6.3, do not improvise): re-run the SNR-ladder calibration and "
            "repeat once. NOTE: the calibration function is deterministic given the fixed "
            "ladder/seed, so this retry is expected to reproduce the same operating point "
            "unless the tie source is something other than the operating point -- running it "
            "anyway, faithfully, per spec." % (row0a["frac_undecidable"], UNDECIDABLE_FRAC_MAX))
        remedy_attempted = True
        try:
            snr_db_retry = PHASE_A.calibrate_operating_snr(ex, log)
        except RuntimeError as e:
            log("\nREMEDY CALIBRATION FAILED: %s" % e)
            bundle["final"] = "row0a_remedy_calibration_fail"
            bundle["error"] = str(e)
            return finish(bundle, 5)
        snr_db = snr_db_retry
        bundle["operating_snr_db_after_remedy"] = snr_db
        for tr in trials:
            tr["cells"] = {}
        sweep_all(ex, trials, snr_db, M_RANGE_INITIAL, log)
        row0a = compute_argmins(trials, log)
        if not row0a["passed"]:
            log("\nROW 0a STILL FAILED after the pre-specified retry (frac_undecidable=%.3f > "
                "%.2f) -- VOID, ESCALATE. STOPPING." % (row0a["frac_undecidable"],
                                                          UNDECIDABLE_FRAC_MAX))
            bundle["row0a"] = row0a
            bundle["row0a_remedy_attempted"] = remedy_attempted
            bundle["final"] = "row0a_void_escalate"
            return finish(bundle, 6)
    log("\nROW 0a PASSED%s." % (" (after remedy)" if remedy_attempted else ""))
    bundle["row0a"] = row0a
    bundle["row0a_remedy_attempted"] = remedy_attempted

    log("\n" + "-" * 90)
    log("PRECONDITION ROW 0c -- optima interior")
    log("-" * 90)
    mode_g = mode_and_frac(trials, "G", log, "grid   (G = g_i - k_true_i)")
    mode_c = mode_and_frac(trials, "C", log, "coherent (C = c_i - k_true_i)")
    m_range_final = M_RANGE_INITIAL
    widened = False
    boundary = M_RANGE_INITIAL[-1]  # sweep is k_true +/- boundary, so |mode| cannot exceed this
    # spec Sec.6.3 ROW 0c: "if |mode(G)| or |mode(C)| > 3 (i.e. at the +/-4 boundary)" -- with a
    # +/-4 sweep, |mode| > 3 means |mode| == 4 == boundary, i.e. the mode landed exactly on the
    # swept edge (a wider sweep might have found something further out).
    if abs(mode_g["mode"]) >= boundary or abs(mode_c["mode"]) >= boundary:
        log("  ROW 0c: boundary optimum detected (mode_g=%+d mode_c=%+d, swept range +/-%d) -- "
            "widening by %d quanta each side and re-running ONCE (spec Sec.6.3)."
            % (mode_g["mode"], mode_c["mode"], boundary, WIDEN_BY))
        widened = True
        m_range_final = tuple(range(M_RANGE_INITIAL[0] - WIDEN_BY, M_RANGE_INITIAL[-1] + WIDEN_BY + 1))
        sweep_all(ex, trials, snr_db, m_range_final, log)
        row0a = compute_argmins(trials, log)
        mode_g = mode_and_frac(trials, "G", log, "grid   (G = g_i - k_true_i) [widened]")
        mode_c = mode_and_frac(trials, "C", log, "coherent (C = c_i - k_true_i) [widened]")
        new_boundary = m_range_final[-1]
        if abs(mode_g["mode"]) >= new_boundary or abs(mode_c["mode"]) >= new_boundary:
            log("\nROW 0c STILL at boundary after widening to +/-%d -- VOID, ESCALATE. "
                "STOPPING." % new_boundary)
            bundle["row0c"] = {"widened": True, "m_range_final": list(m_range_final),
                                "mode_g": mode_g, "mode_c": mode_c, "passed": False}
            bundle["row0a_after_widen"] = row0a
            bundle["final"] = "row0c_void_escalate"
            return finish(bundle, 7)
    log("\nROW 0c PASSED%s (final swept range +/-%d)."
        % (" (after widening)" if widened else "", m_range_final[-1]))
    bundle["row0c"] = {"widened": widened, "m_range_final": list(m_range_final), "passed": True}

    log("\n" + "=" * 90)
    log("ROW 1-4 EVALUATION (Sec.6.4)")
    log("=" * 90)
    log("  mode(G)=%+d frac_at_mode(G)=%.3f | mode(C)=%+d frac_at_mode(C)=%.3f | bar=%.2f"
        % (mode_g["mode"], mode_g["frac_at_mode"], mode_c["mode"], mode_c["frac_at_mode"],
           FRAC_AT_MODE_BAR))
    row, row_text = evaluate_row(mode_g["mode"], mode_g["frac_at_mode"],
                                  mode_c["mode"], mode_c["frac_at_mode"], log)
    bundle["mode_g"] = mode_g
    bundle["mode_c"] = mode_c
    bundle["row"] = row
    bundle["row_text"] = row_text

    secondary = secondary_sign_agreement(trials, log)
    bundle["secondary_sign_agreement"] = secondary

    elapsed = time.time() - t0
    log("\n" + "=" * 90)
    log("B-ORIG-A DONE (%.1fs). ROW %d fired. ROW 0g still stands FIRED; task 4.3 still VOID; "
        "Route B2 still not dead; design.md D1 still not amended (Sec.5 ruling still the "
        "Captain's)." % (elapsed, row))
    log("=" * 90)
    bundle["elapsed_s"] = elapsed
    bundle["final"] = "row_%d_fired" % row
    return finish(bundle, 0)


if __name__ == "__main__":
    raise SystemExit(main())
