#!/usr/bin/env python
"""DENSITY-REMEDY Stage 2 -- bench sweep over the (snr_min, snr_max, side_weight) cube.

================================================================================
PRE-REGISTRATION -- committed BEFORE any classification or measurement decode (HK-021: mechanical bars)
================================================================================
Spec  : qa/rr-study/2026-09-19-1228-architect-to-qa-spec-density-remedy-suppression.md S5, AS AMENDED BY S14 (arch/density 1134b5b0,
        Architect ruling 2026-09-20T13:32Z).  Where S5 and S14 disagree, S14 governs.  Captain's go: "start stage 2".
Binary: decoding_improvement fa8a56ae (PR #184), libft8.dll SHA-256 38a21f840b00af146348c166786cb54e178cd2201c5ed4dba3016a4c589a1cba,
        shim 20260054.  ONE DLL for every set and every job (ROW 0a).  Extracted with `git show`, never the working tree.
Params: ft8_set_decode_params(10, 0.10, 40) = the LIVE app's, set explicitly; READ BACK through ft8_get_decoder_params in every job
        (Stage 1's dividend: the run can PROVE the decoder ran with the parameters this document claims).
Scene : the 12-station S8HN scene (DENSITY-MECH/DENSITY-P1 verbatim), E at 1150 Hz, F at 1150 + Delta.  ONLY E's and F's message TEXT
        change (8 pairs, below).  One PRODUCTION decode per (scene, variant): G, H1, H2 and FPb all come from that one decode.

MESSAGE PAIRS (S14.6; frozen literal, generated by sha256("DENSITY-REMEDY-STAGE2-PAIRS-v1|i"), asserted equal to the generator in `preflight`):
  E = "<X> <Y> +05", F = "<Y> <X> RR73".  Q-prefix only (NFR-021).  Distinct from Q1ABC / Q1AW / Q9XYZ (the other ten stations) and from
  each other.  Both messages are the 77-bit standard type, i3 = 001, CHECKED against the decoder's own encoder in `preflight`.

CELLS (S14.2): 14 inherited VERBATIM (DENSITY-P1's build_cells(): 9 primary + 3 strong + 2 E+15; asserted == 14) PLUS 7 interior-of-ramp cells,
  all with X = E - F = +3 dB, at each Delta in {6.25, 12, 18.75}:
    half5   E nominal +5  (reported +6)     [+5,+9] "half"   -- one per Delta (3)
    heavy12 E nominal +12 (reported +13)    [+10,+14] "heavy" -- one per Delta (3)
    e15     E nominal +15 (reported +16), Delta 18.75 only (Delta 6.25 and 12 are inherited)   ("full", >= +15)          (1)
  = 21 cells.  Nominal -> reported mapping is MEASURED, not assumed: results/stage2_calibration.json (E reported SNR = nominal + 1 dB,
  deterministic, SATURATING at +16 for nominal >= +15; seeds 33000+, no F outcome recorded).  The sub-band of a cell is read from the
  REPORTED SNR (S11.3's "our SNR"): floor < +5, half [+5,+9], heavy [+10,+14], full >= +15.
  ROW 0f (QA-added, mechanical): every (Delta x {half, heavy, full}) is populated by >= 1 cell, using the E reported SNR MEDIAN measured on
  the CLASSIFICATION set's V0 decodes (not the calibration).  Unpopulated => the pre-registration is incomplete => STOP.
  This is a design, NOT a sample: no cell is weighted to live shares (S14.2).

SEEDS (S14.3; both sets committed BEFORE any variant decode; disjointness asserted, mechanically):
  seed = SR.trial_seed(t, part_index).  CLASSIFICATION: part_index = 31000 + 8*cell_idx + pair_idx, t = 0..99 (N_CLASS = 100).
  MEASUREMENT: part_index = 32000 + 8*cell_idx + pair_idx, t = 0..49 (N_MEAS = 50).  Calibration used 33000+.  All >= 30000, disjoint from
  every earlier arm's range (asserted: nothing below 30000 is used).  `preflight` writes the full seed table and its sha256 to
  results/stage2_prereg_manifest.json.

VARIANTS (S14.1): (snr_min, snr_max, s) in {-5,-10,-15} x {+15,+10,+5} x {1.0,0.5,0.0} = 27, MINUS exactly (-15, +5, 1.0) (H5's exact ramp;
  NEVER run by QA, governance) = 26 = V0 (-5,+15,1.0) + 25 variants.  The list is BUILT SORTED by the literal triple (never a set/dict).
  V0 is decoded in its OWN PROCESS with the setter NEVER called (the shipped path); the 25 variants and the null VN (explicit (-5,+15,1.0))
  are decoded in variant processes, setter called before each decode and READ BACK with ft8_get_supp_params (ROW 0a).
  distance_from_default = |d snr_min|/5 + |d snr_max|/5 + |d s|/0.5.

CLASSIFICATION (run FIRST, V0 only; then STOP-check ROW 0c / 0f before any variant is decoded):
  prod(cell,pair) = F recovery rate of V0 over N_CLASS (PC._f_recovered: |dfreq| <= 4 Hz, whitespace-normalised exact text).
  excluded  <=>  prod <= 0.20 (PROD_EXCLUDED, inherited).  Reported, gating nothing: #excluded, and how many sit within 1 classification SE
  (sqrt(0.2*0.8/100) = 0.04) of 0.20.

MEASURES (measurement set only; per variant v):
  G(v)     = pooled F recovery over the measurement trials of the cell x pair units V0 classified EXCLUDED  (sum hits / sum trials).
  H1(v,c)  = for cell c: pooled F recovery over the measurement trials of c's NON-EXCLUDED pairs.
             QA-FIXED (spec silent; S14 quantum note is per CELL): a cell is GATED iff it has >= 4 non-excluded pairs (>= 200 trials).  Cells with
             fewer are reported, never gated.  Reported: how many cells are gated.
  H2(v)    = pooled recovery of the scene's OTHER 11 stations (E included) over ALL measurement trials of v:  sum recovered / (11 * trials).
             A station is recovered iff PC._f_recovered(rows, its freq, its message) (same matcher as F).
  FPb(v)   = 1000 * (# emitted rows whose whitespace-normalised text is NOT in that scene's 12-station truth set) / (# measurement trials).
finalist(v) -- S5.4 UNCHANGED, first failing clause wins, each bar frozen:
    1. any gated cell c: H1(v,c) < H1(V0,c) - 0.05            => reject "H1"
    2. H2(v) < H2(V0) - 0.01                                   => reject "H2"
    3. FPb(v) > FPb(V0) + 1.0                                  => reject "FP"
    4. G(v) - G(V0) >= 0.10                                    => "PASS", else reject "GAIN"
  finalists = sorted PASS variants by (-G, distance_from_default, literal triple)[:2]; the 3rd-ranked PASS is reported explicitly.
  No PASS => report and STOP.  H5 CORNER: run (-15,+5,0.5), (-15,+5,0.0), (-10,+5,1.0), (-15,+10,1.0); if >= 2 of those four are PASS, report
  "H5 CORNER IMPLICATED" and STOP for the Captain; QA never runs (-15,+5,1.0).
  PAIRED SE (reporting only, NEVER a gate; the 0.05 bar does not move, S14.5): for a variant and a cell, over that cell's non-excluded-pair
  scenes, b = #(v hit, V0 miss), c = #(v miss, V0 hit), n = #scenes;  diff = (b-c)/n;  SE = sqrt(max(0, b + c - (b-c)^2/n)) / n  (discordant form).
  "Rejected by H1 ALONE" := clause 1 fails AND clauses 2 and 3 hold AND G-gain >= 0.10 (it would be PASS but for H1).  For each such variant the
  report gives the worst cell's (largest V0-minus-v drop) paired difference and paired SE.  If >= 3 such variants have |diff| <= 2*SE, report the
  INSTRUMENT NOTE (S14.5); it changes no verdict and licenses no re-run.
  MANDATORY: the full 26-row surface table (G, G-G0, worst-cell H1 drop + paired SE, H2, FPb, rejecting clause).

ROW 0 (any fires => STOP, report, NO re-cut; S14.4):
  0a  DLL SHA-256 == pin in EVERY job header, shim 20260054, the same DLL for classification and measurement; decode params read back through
      ft8_get_decoder_params == (10, 0.10f, 40) in every job; EVERY variant's triple read back with ft8_get_supp_params equals the registered
      triple bit-for-bit (V0's read-back equals the defaults); readback mismatches == 0.
  0b  V0 measurement run TWICE (own processes), the two record streams byte-identical.
  0c  the classified-EXCLUDED set has >= 24 cell x pair units, spanning >= 3 distinct cells and >= 4 distinct pairs.
  0d  [FIRED on the first evaluation, then RE-SPEC'D as 0d' by the Architect, spec S16.2 -- see the S16 ADDENDUM below; the original text follows, NOT edited away]
      the null VN (explicit (-5,+15,1.0), decoded in a variant process) has, for EVERY scene, a decode sha identical to V0's (V0 was decoded in a
      different process, so this also tests process-order independence); G(VN) - G(V0) == 0 EXACTLY; VN is absent from the finalists.
  0e  PER-LEVER sensitivity on the measurement set, evaluated on the SINGLE-LEVER variants: FLOOR {(-10,15,1),(-15,15,1)}, TOP {(-5,10,1),(-5,5,1)},
      FOOTPRINT {(-5,15,0.5),(-5,15,0.0)}: each family must have >= 1 variant with >= 1 scene whose decode sha differs from V0.  Differing-scene
      counts are reported per family (and per variant).  Any family inert => STOP.
  0f  (QA-added) the (Delta x sub-band) coverage above.   0g (QA-added) completeness: every job present, every record count == expected.
  0h  FP-CLAUSE PRECONDITION (QA-added; RE-DERIVED and BRANCHED by the Architect, spec S15.2; evaluated on the CLASSIFICATION set's V0 decodes, V0
      ONLY: no variant data, no G, no H1, so it is a true precondition).  It does NOT stop the arm: it SELECTS the FP clause, both pre-registered here.
      V0's FPb = 1000 * (junk rows) / (scenes) over the 16,800 classification scenes.  The +1.0 bar of S5.4 is exactly 2 SD of the scene-difference
      noise (1000*sqrt(2r/N), N = 8,400) at FPb = 1.05; above that it is noise-dominated.
        BRANCH A  (FPb_V0 < 0.95):  S5.4's clause EXACTLY as written: reject when FPb(v) > FPb(V0) + 1.0.
        BRANCH B  (FPb_V0 >= 0.95):  [TEXT-KEYED pairing below is SUPERSEDED by B' (S16.2): text is history-dependent] the clause is the SCENE-PAIRED one-sided discordant test below.  0.95-1.16 is NEAR-BAR (+-10% of 1.05) and takes
                  branch B by rule; QA reports that it was near-bar.  Also branch B whenever FPb_V0 > 1.05.
            A = junk rows in v absent from V0 on that SAME scene;  B = the reverse (multiset difference of junk-row hashes per scene);
            holds  <=>  (A + B < 25)  or  (A - B)/sqrt(A + B) <= 3.0          [one-sided, hard z = 3.0]
      For EVERY variant, whichever branch: report A, B, z AND the relative change (A - B)/V0_junk_total.
      Junk rows are stored ONLY as 12-hex sha1 hashes of the whitespace-normalised text (NFR-021: random decoder output can resemble a real callsign,
      and reports are committed) and reported as COUNTS.  The rate is a BENCH junk emission on synthetic AWGN with the offline normalisation: cite it only
      as "bench junk emission, Stage 2 classification set, V0"; NEVER a live FP rate, never comparable to any FP-WORKSTREAM figure (S15.3).
PHASES / ORDERING (S15.4): PHASE A (classification, V0 only) = 0c, 0f, 0h(branch).  PHASE B (26-variant measurement) = 0a, 0b, 0d, 0e, 0g.  The finalist
computation runs ONLY after every row is silent; if any row fires NO verdict is computed at all (variant measures are not even evaluated).  0d is
therefore checked as per-scene identity of sha AND f between VN and V0, which implies G(VN) - G(V0) == 0 exactly without evaluating G.
TRANSPARENCY (S15.1.2): per variant the report states how many non-excluded cells were GATED vs REPORTED-ONLY, and for every finalist (and the 3rd-ranked)
lists the UNGATED cells' V0-relative H1 differences, so a breach cannot hide behind the >= 4-pair gate.
SCOPE LIMITS printed beside any result (HK-026, S15.1.1): (i) reported SNR SATURATES at +16 for nominal >= +15, so the bench cannot show a blocker stronger
than the "full" band: any snr_max finding speaks to the RAMP INTERIOR only; (ii) bench FP is weak evidence, a gross-junk filter only (S5.3): Stage 3 is the FP primary.

================================================================================
ADDENDUM S16 -- ROW 0d FIRED; RE-SPEC (Architect ruling 2026-09-20T19:49Z, spec S16, arch/density b590aff0).  REGISTERED before any verdict measure was evaluated.
================================================================================
WHAT FIRED (recorded, never hidden): the first evaluation of phase B stopped at ROW 0d: VN differs from V0 on 2 of 8,400 scenes in `sha` and the junk-row
text-hash list ONLY; f, m, nfp, pc, e identical on all 8,400.  Cause verified in source: g_session_hash_table is process-global, never re-initialised, and a
hashed-callsign junk row's TEXT depends on decode history.  No variant measure (G/H1/H2/FP) had been evaluated: ROW 0 is checked first and the measures after.
0d' (re-spec'd):  VN == V0 per scene on f, m, nfp, pc, e -- every field any measure reads (RULE: 0d's guarded set is a SUPERSET of the fields any measure
   reads).  `sha` and the junk text-hash list are EXCLUDED from the assertion and DISCLOSED in the report as their own section (the differing scenes named
   by cell/pair/trial, counts only).  Fires => STOP.  The 2 scenes STAY in the measurement set.  The report says ROW 0d FIRED.
Branch B' (the FP clause, re-keyed to COUNTS; text is never read):
   d_s = nfp(v,s) - nfp(V0,s) per scene;  S = sum d;  q = sqrt(sum d^2);   holds  <=>  S <= 0  or  (q > 0 and S/q <= 3.0)   [one-sided, hard z = 3.0]
   Reported for EVERY variant: V0's and v's junk per 1,000 scenes, S, q, z = S/q, the relative change S/V0_junk_total.
   Reported, NEVER gated: a frequency-bucket breakdown of added/removed junk (buckets of 500 Hz on the candidate's frequency, which is history-free).
   QA GAP, disclosed: the job records store the junk COUNT and text hashes but NOT junk frequencies, so the breakdown cannot come from the stored data.  It is
   produced AFTER the verdict, for V0 and the finalists / 3rd-ranked only, by a targeted re-decode of the same scenes with the same seeds (`junkfreq`), whose
   per-scene junk COUNTS must equal the stored counts (asserted).  Reporting only; it changes no verdict.
S16.3 standing guard carried: compare OUTCOME FIELDS, never rendered text, across processes.
Phase B ordering unchanged (S15.4): rows first; if any row fires, no measure is evaluated.

NOT-A-GATE / REPORTING: #excluded units and the near-boundary count; #gated cells; per-family differing-scene counts; which clause rejected each variant.

WHAT THIS CANNOT SEE (S7 + QA): one synthetic 12-station AWGN scene, 8 message pairs; the bench FP is weak evidence (S5.4: it filters gross FP only;
Stage 3 is the FP primary); the reported-SNR saturation at +16 means the bench cannot present a blocker stronger than the top of the "full" band;
cells are a design, not a sample, so NO number here is a live estimate; the noise-floor percentile (S13) is not swept; Windows DLL only.
NFR-021: every callsign here is synthetic Q-prefix; artefacts/ is gitignored; committed results hold counts and hashes only.
"""
import argparse
import hashlib
import json
import math
import os
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import stage1_accept_readout as H  # noqa: E402  (re-pinned instrument; sets sys.path for the rr-study helpers)

S1, DM, DP, SR, PC = H.S1, H.DM, H.DP, H.DM.SR, H.DM.PC
REPO_ROOT = H.REPO_ROOT
OUT_DIR = os.path.join(REPO_ROOT, "artefacts", "density-remedy-stage2")
RESULTS = os.path.join(HERE, "results")

BUILD_COMMIT = "fa8a56ae"                       # decoding_improvement, PR #184 (resolved to a full SHA in preflight)
DLL_SHA, DLL_VER = H.NEW_SHA, H.NEW_VER
N_CLASS, N_MEAS = 100, 50
CLASS_BASE, MEAS_BASE, CAL_BASE = 31000, 32000, 33000
PROD_EXCLUDED = 0.20
H1_BAR, H2_BAR, FP_BAR, GAIN_BAR_BENCH = 0.05, 0.01, 1.0, 0.10
MIN_EXCL_UNITS, MIN_EXCL_CELLS, MIN_EXCL_PAIRS = 24, 3, 4
H1_GATE_MIN_PAIRS = 4
FP_BRANCH_B_FROM = 0.95     # ROW 0h: FPb_V0 >= this takes branch B (0.95-1.16 near-bar, and > 1.05); below it, branch A
FP_NEAR_LO, FP_NEAR_HI = 0.95, 1.16
FP_Z = 3.0
DEFAULT_TRIPLE = (-5.0, 15.0, 1.0)
H5_TRIPLE = (-15.0, 5.0, 1.0)
H5_BRACKET = [(-15.0, 5.0, 0.5), (-15.0, 5.0, 0.0), (-10.0, 5.0, 1.0), (-15.0, 10.0, 1.0)]
FAMILIES = {"FLOOR": [(-10.0, 15.0, 1.0), (-15.0, 15.0, 1.0)], "TOP": [(-5.0, 10.0, 1.0), (-5.0, 5.0, 1.0)],
            "FOOTPRINT": [(-5.0, 15.0, 0.5), (-5.0, 15.0, 0.0)]}
INHERITED_CELLS = 14
DELTAS = (6.25, 12.0, 18.75)
X_NEW_DB = 3.0
SUBBANDS = ("half", "heavy", "full")
ORIGINAL_CALLS = {"Q1ABC", "Q1AW", "Q9XYZ"}

PAIRS = [("Q9UY", "Q6LJ"), ("Q2EW", "Q5OL"), ("Q7FIN", "Q3MID"), ("Q4FA", "Q0RZ"),
         ("Q7ZH", "Q9IP"), ("Q7XY", "Q2BM"), ("Q3HO", "Q1WN"), ("Q3OH", "Q1UO")]
N_PAIRS = len(PAIRS)
OTHER_STATIONS = ["A", "B", "C", "D", "E", "G", "H", "I", "J", "K", "L"]      # the scene's 12 minus F

# PLUMBING SMOKE ONLY (env STAGE2_SMOKE=1): other seeds, another output directory, tiny N, a few cells/pairs, relaxed thresholds, ROW 0 forced to pass
# so the surface code runs.  NEVER a verdict; the committed pre-registration above is what governs.  (Precedent: DENSITY_P1_OUT smoke override.)
SMOKE = os.environ.get("STAGE2_SMOKE") == "1"
SMOKE_CELLS = (0, 9, 12, 14)
if SMOKE:
    CLASS_BASE, MEAS_BASE = 90000, 91000
    N_CLASS, N_MEAS = 4, 2
    N_PAIRS = 2
    OUT_DIR = OUT_DIR + "-smoke"
    MIN_EXCL_UNITS = MIN_EXCL_CELLS = MIN_EXCL_PAIRS = H1_GATE_MIN_PAIRS = 1


def log(m):
    print(m, flush=True)


def pair_msgs(k):
    x, y = PAIRS[k]
    return "%s %s +05" % (x, y), "%s %s RR73" % (y, x)


def gen_pairs():
    """The generator the frozen literal must equal (hash-based: independent of Python's random)."""
    LET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    calls, i = [], 0
    while len(calls) < 16:
        h = hashlib.sha256(("DENSITY-REMEDY-STAGE2-PAIRS-v1|%d" % i).encode()).digest()
        i += 1
        n = 2 + (h[1] % 2)
        c = "Q%d%s" % (h[0] % 10, "".join(LET[h[2 + k] % 26] for k in range(n)))
        if c in ORIGINAL_CALLS or c in calls:
            continue
        calls.append(c)
    return [(calls[2 * k], calls[2 * k + 1]) for k in range(8)]


# ── cells ──────────────────────────────────────────────────────────────────────
def build_cells():
    inherited = [dict(c) for c in DP.build_cells()]
    cells = inherited
    for d in DELTAS:
        cells.append({"group": "half5", "delta_hz": d, "x_db": X_NEW_DB, "e_snr_db": 5.0, "f_snr_db": 2.0})
        cells.append({"group": "heavy12", "delta_hz": d, "x_db": X_NEW_DB, "e_snr_db": 12.0, "f_snr_db": 9.0})
    cells.append({"group": "e15", "delta_hz": 18.75, "x_db": X_NEW_DB, "e_snr_db": 15.0, "f_snr_db": 12.0})
    for i, c in enumerate(cells):
        c["idx"] = i
        c["key"] = "%s,%.2f,%.1f,E%+.0f" % (c["group"], c["delta_hz"], c["x_db"], c["e_snr_db"])
    assert len({c["key"] for c in cells}) == len(cells), "cell keys not unique"
    if SMOKE:
        cells = [cells[i] for i in SMOKE_CELLS]
    return cells


def reported_snr(nominal_e_db):
    """From results/stage2_calibration.json (MEASURED), not from a formula."""
    with open(os.path.join(RESULTS, "stage2_calibration.json")) as f:
        cal = json.load(f)
    for lv in cal["levels"]:
        if lv["nominal_e_db"] == nominal_e_db:
            return lv["reported_snr_median"]
    raise KeyError("nominal E %r not calibrated" % nominal_e_db)


def subband(snr):
    if snr >= 15:
        return "full"
    if snr >= 10:
        return "heavy"
    if snr >= 5:
        return "half"
    return "floor"


def part_index(base, cell_idx, pair_idx):
    return base + 8 * cell_idx + pair_idx


def signals_for(cell, pair_idx):
    e_msg, f_msg = pair_msgs(pair_idx)
    base = SR.load_s8hn_signals()
    for s in base:
        if s["station"] == SR.STATION_E:
            s["message_text"] = e_msg
        elif s["station"] == SR.STATION_F:
            s["message_text"] = f_msg
    base = SR.set_station_snr(base, SR.STATION_E, cell["e_snr_db"])
    base = SR.set_station_snr(base, SR.STATION_F, cell["f_snr_db"])
    target = SR.E_FREQ_HZ + cell["delta_hz"]
    sig = SR.move_station_freq(base, SR.STATION_F, target)
    others = [(s["station"], float(s["freq_hz"]), s["message_text"]) for s in sig if s["station"] != SR.STATION_F]
    assert [o[0] for o in others] == OTHER_STATIONS, [o[0] for o in others]
    truth = {" ".join(s["message_text"].split()) for s in sig}
    assert len(truth) >= 11, "truth set collapsed: %r" % truth
    return sig, target, f_msg, others, truth


def variants():
    """SORTED by the literal triple; V0 included; H5's exact ramp excluded.  Never built from a set or dict."""
    out = []
    for lo in (-15.0, -10.0, -5.0):
        for hi in (5.0, 10.0, 15.0):
            for s in (0.0, 0.5, 1.0):
                if (lo, hi, s) != H5_TRIPLE:
                    out.append((lo, hi, s))
    out.sort()
    assert len(out) == 26 and DEFAULT_TRIPLE in out and H5_TRIPLE not in out
    return out


def distance(v):
    return abs(v[0] - DEFAULT_TRIPLE[0]) / 5.0 + abs(v[1] - DEFAULT_TRIPLE[1]) / 5.0 + abs(v[2] - DEFAULT_TRIPLE[2]) / 0.5


def vname(v):
    return "(%+g,%+g,%g)" % v


def seed_table():
    rows = []
    for setname, base, n in (("class", CLASS_BASE, N_CLASS), ("meas", MEAS_BASE, N_MEAS), ("cal", CAL_BASE, 12)):
        for ci in range(len(build_cells())):
            for p in range(N_PAIRS):
                pi = part_index(base, ci, p) if setname != "cal" else None
                if pi is None:
                    continue
                for t in range(n):
                    rows.append((setname, ci, p, t, SR.trial_seed(t, pi)))
    return rows


# ── preflight: everything mechanical that can be checked before any decode ─────────────
def cmd_preflight(a):
    from ldpc_decode_ctypes import LdpcDecodeLLRs
    fails = []
    chk = lambda cond, msg: (fails.append(msg) if not cond else None) or bool(cond)
    full = subprocess.run(["git", "-C", REPO_ROOT, "rev-parse", BUILD_COMMIT], capture_output=True).stdout.decode().strip()
    chk(len(full) == 40, "cannot resolve %s" % BUILD_COMMIT)
    blob = subprocess.run(["git", "-C", REPO_ROOT, "show", "%s:src/OpenWSFZ.Ft8/Native/win-x64/libft8.dll" % full], capture_output=True).stdout
    chk(hashlib.sha256(blob).hexdigest() == DLL_SHA, "DLL at %s is not the pin" % full[:8])
    chk(S1.sha256_file(os.path.join(H.BIN_DIR, "libft8_NEW.dll")) == DLL_SHA, "extracted DLL is not the pin")
    # pairs
    chk(PAIRS == gen_pairs(), "frozen pair literal != generator")
    calls = [c for pr in PAIRS for c in pr]
    chk(len(set(calls)) == 16 and not (set(calls) & ORIGINAL_CALLS) and all(c.startswith("Q") for c in calls), "pair pool constraints")
    dec = LdpcDecodeLLRs(os.path.join(H.BIN_DIR, "libft8_NEW.dll"), verify=True, expected_sha256=DLL_SHA, expected_shim_version=DLL_VER)
    for k in range(N_PAIRS):
        for m in pair_msgs(k):
            b = dec.true_codeword(m)
            chk(b is not None and list(b[74:77]) == [0, 0, 1], "pair %d message %r is not i3=001" % (k, m))
    # cells
    cells = build_cells()
    chk(len(cells) == INHERITED_CELLS + 7, "cell count %d != 21" % len(cells))
    chk(sum(1 for c in cells[:INHERITED_CELLS] if c["group"] == "primary") == 9 and sum(1 for c in cells[:INHERITED_CELLS] if c["group"] == "strong") == 3
        and sum(1 for c in cells[:INHERITED_CELLS] if c["group"] == "e15") == 2, "inherited composition != 9+3+2")
    cov = {}
    for c in cells:
        sb = subband(reported_snr(c["e_snr_db"]))
        c["reported_e_snr_calibrated"], c["subband_calibrated"] = reported_snr(c["e_snr_db"]), sb
        cov.setdefault((c["delta_hz"], sb), []).append(c["key"])
    for d in DELTAS:
        for sb in SUBBANDS:
            chk((d, sb) in cov, "no cell at delta %s in sub-band %s" % (d, sb))
    # variants
    vs = variants()
    chk(len(vs) == 26, "variant count")
    # seeds
    rows = seed_table()
    seeds = [r[4] for r in rows]
    chk(len(set(seeds)) == len(seeds), "seed collision inside the seed table")
    parts = {(r[0], r[1], r[2]): part_index({"class": CLASS_BASE, "meas": MEAS_BASE}[r[0]], r[1], r[2]) for r in rows}
    chk(min(parts.values()) >= 30000, "a part_index below 30000")
    chk(len(set(parts.values())) == len(parts), "part_index collision between sets/cells/pairs")
    chk(max(p for (s, _, _), p in parts.items() if s == "class") < MEAS_BASE and MEAS_BASE + 8 * len(cells) <= CAL_BASE, "set ranges overlap")
    digest = hashlib.sha256(("\n".join("%s,%d,%d,%d,%d" % r for r in rows)).encode()).hexdigest()
    man = {"build_commit": full, "dll_sha256": DLL_SHA, "shim_version": DLL_VER, "pairs": PAIRS, "n_cells": len(cells), "n_variants": len(vs),
           "variants_sorted": [list(v) for v in vs], "cells": [{k: c[k] for k in ("idx", "key", "group", "delta_hz", "e_snr_db", "f_snr_db",
                                                                                  "reported_e_snr_calibrated", "subband_calibrated")} for c in cells],
           "coverage": {"%s|%s" % k: v for k, v in sorted(cov.items())}, "n_seed_rows": len(rows), "seed_table_sha256": digest,
           "n_class_scenes": len(cells) * N_PAIRS * N_CLASS, "n_meas_scenes": len(cells) * N_PAIRS * N_MEAS,
           "jobs": {"class_v0": len(cells) * N_PAIRS, "meas_v0": len(cells) * N_PAIRS, "meas_v0_rerun": len(cells) * N_PAIRS, "meas_var": len(cells) * N_PAIRS},
           "failures": fails}
    p = os.path.join(RESULTS, "stage2_prereg_manifest.json")
    with open(p, "w") as f:
        json.dump(man, f, indent=1)
    log("preflight: %s (%d failures)  cells=%d variants=%d seed_rows=%d seed_sha=%s" % ("PASS" if not fails else "FAIL", len(fails), len(cells), len(vs), len(rows), digest[:16]))
    for m in fails:
        log("  FAIL: " + m)
    for d in DELTAS:
        log("  delta %5.2f: %s" % (d, "  ".join("%s=%d" % (sb, len(cov.get((d, sb), []))) for sb in SUBBANDS)))
    sys.exit(1 if fails else 0)


# ── jobs ───────────────────────────────────────────────────────────────────────
def fbits(x):
    return struct.pack("<f", float(x)).hex()


def cmd_job(a):
    cells = build_cells()
    cell, p = cells[a.cell], a.pair
    setname, kind = a.set, a.kind
    n = N_CLASS if setname == "class" else N_MEAS
    base = CLASS_BASE if setname == "class" else MEAS_BASE
    assert kind in ("v0", "var") and not (setname == "class" and kind == "var")
    out = os.path.join(OUT_DIR, "%s_%s_c%02d_p%d.jsonl" % (setname, kind, a.cell, p))
    os.makedirs(OUT_DIR, exist_ok=True)
    S1.ensure_ignored(out)
    d, sha = H.load_new_dll()                       # SHA + version pin, or ROW 0a STOP
    H.CFG["supp"] = None
    sh = S1.Shim(os.path.join(H.BIN_DIR, "libft8_NEW.dll"), "NEW", has_probe=False)
    S1.LIVE_NHARD = 40
    sh.set_params(S1.LIVE_PASS2)                    # (10, 0.10, 40); the SUPPRESSION setter is not touched here
    tbl = {e["name"]: e for e in H.read_table(d)}
    table_ok = (tbl["k_min_score_pass2"]["value"] == 10.0 and tbl["osd_nhard_max"]["value"] == 40.0
                and tbl["osd_corr_threshold"]["value"] == H.f32(0.10))
    rc, sp = H.get_supp(d)
    defaults_ok = (rc == 0 and H.bits3(sp) == H.bits3(DEFAULT_TRIPLE))
    sig, target, f_msg, others, truth = signals_for(cell, p)
    todo = [None] if kind == "v0" else [v for v in variants() if v != DEFAULT_TRIPLE] + ["VN"]
    n_rb_bad, nrec = 0, 0
    with open(out, "w", newline="\n") as fo:
        fo.write(json.dumps({"hdr": 1, "set": setname, "kind": kind, "cell": a.cell, "pair": p, "sha": sha, "version": DLL_VER, "build": BUILD_COMMIT,
                             "table_ok": bool(table_ok), "defaults_ok": bool(defaults_ok), "n": n}) + "\n")
        for t in range(n):
            pcm = SR.render_scene(sig, SR.trial_seed(t, part_index(base, a.cell, p)))
            for v in todo:
                if v is None:
                    tri, vi = DEFAULT_TRIPLE, "V0"
                    rc, got = H.get_supp(d)                         # setter never called: must read the defaults
                else:
                    tri = DEFAULT_TRIPLE if v == "VN" else v
                    vi = "VN" if v == "VN" else vname(v)
                    assert H.set_supp(d, *tri) == 0
                    rc, got = H.get_supp(d)
                if rc != 0 or H.bits3(got) != H.bits3(tri):
                    n_rb_bad += 1
                _n, rows, pcl, canon = DP.decode(sh, pcm)
                f = int(PC._f_recovered(rows, target, f_msg))
                mask = 0
                for bi, (_st, fq, msg) in enumerate(others):
                    if PC._f_recovered(rows, fq, msg):
                        mask |= 1 << bi
                fp = [hashlib.sha1(" ".join(r["message"].split()).encode()).hexdigest()[:12] for r in rows if " ".join(r["message"].split()) not in truth]
                e_row = [r for r in rows if abs(r["freq_hz"] - SR.E_FREQ_HZ) <= PC.FREQ_TOLERANCE_HZ and PC._text_matches(r["message"], pair_msgs(p)[0])]
                fo.write(json.dumps({"t": t, "v": vi, "f": f, "m": mask, "nfp": len(fp), "fp": fp, "pc": pcl, "e": (e_row[0]["snr"] if e_row else None),
                                     "sha": hashlib.sha256(canon.encode()).hexdigest()[:16]}) + "\n")
                nrec += 1
        fo.write(json.dumps({"trailer": 1, "readback_mismatch": n_rb_bad, "records": nrec}) + "\n")


def cmd_plan(a):
    """Prints the job list for a phase: 'class' (V0 only, classification) or 'meas' (V0, V0 rerun, variants)."""
    cells = build_cells()
    lines = []
    for c in range(len(cells)):
        for p in range(N_PAIRS):
            if a.phase == "class":
                lines.append("job --set class --kind v0 --cell %d --pair %d" % (c, p))
            else:
                lines.append("job --set meas --kind v0 --cell %d --pair %d" % (c, p))
                lines.append("job --set meas2 --kind v0 --cell %d --pair %d" % (c, p))
                lines.append("job --set meas --kind var --cell %d --pair %d" % (c, p))
    print("\n".join(lines))


# ── loading ────────────────────────────────────────────────────────────────────
def load_job(setname, kind, c, p):
    path = os.path.join(OUT_DIR, "%s_%s_c%02d_p%d.jsonl" % (setname, kind, c, p))
    if not os.path.exists(path):
        return None
    hdr, trailer, recs = None, None, []
    with open(path) as f:
        for line in f:
            o = json.loads(line)
            if "hdr" in o:
                hdr = o
            elif "trailer" in o:
                trailer = o
            else:
                recs.append(o)
    return {"hdr": hdr, "trailer": trailer, "recs": recs, "path": path}


def file_sha(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()


def median(xs):
    xs = sorted(xs)
    return xs[len(xs) // 2] if xs else None


# ── classify (phase A gate) ────────────────────────────────────────────────────
def cmd_classify(a):
    cells = build_cells()
    R = {"build": BUILD_COMMIT, "dll_sha256": DLL_SHA, "excluded": {}, "prod": {}, "e_reported_median": {}}
    fails, missing = [], []
    excl_units = []
    near = 0
    fp_rows = fp_scenes = 0
    se1 = math.sqrt(PROD_EXCLUDED * (1 - PROD_EXCLUDED) / N_CLASS)
    e_by_cell = {}
    for c in range(len(cells)):
        for p in range(N_PAIRS):
            j = load_job("class", "v0", c, p)
            if j is None or j["trailer"] is None or len(j["recs"]) != N_CLASS:
                missing.append((c, p)); continue
            if j["hdr"]["sha"] != DLL_SHA or not j["hdr"]["table_ok"] or not j["hdr"]["defaults_ok"] or j["trailer"]["readback_mismatch"] != 0:
                fails.append("ROW 0a: class c%d p%d header/readback" % (c, p))
            prod = sum(r["f"] for r in j["recs"]) / float(N_CLASS)
            fp_rows += sum(r["nfp"] for r in j["recs"]); fp_scenes += len(j["recs"])
            R["prod"]["%d,%d" % (c, p)] = prod
            if prod <= PROD_EXCLUDED:
                excl_units.append((c, p))
            if abs(prod - PROD_EXCLUDED) <= se1:
                near += 1
            e_by_cell.setdefault(c, []).extend(r["e"] for r in j["recs"] if r["e"] is not None)
    if missing:
        log("INCOMPLETE: %d class jobs missing/short: %r" % (len(missing), missing[:6])); sys.exit(3)
    cov = {}
    for c, lst in e_by_cell.items():
        med = median(lst)
        R["e_reported_median"][cells[c]["key"]] = med
        cov.setdefault((cells[c]["delta_hz"], subband(med)), []).append(cells[c]["key"])
    row0 = {}
    row0["0a"] = not fails
    row0["0c"] = (len(excl_units) >= MIN_EXCL_UNITS and len({c for c, _ in excl_units}) >= MIN_EXCL_CELLS and len({p for _, p in excl_units}) >= MIN_EXCL_PAIRS)
    row0["0f"] = SMOKE or all((d, sb) in cov for d in DELTAS for sb in SUBBANDS)
    fpb_v0 = 1000.0 * fp_rows / fp_scenes
    fp_branch = "B" if fpb_v0 >= FP_BRANCH_B_FROM else "A"
    fp_near_bar = FP_NEAR_LO <= fpb_v0 <= FP_NEAR_HI
    R["fp_branch"], R["fp_near_bar"] = fp_branch, fp_near_bar
    R["v0_class_fpb_per_1000"], R["v0_class_fp_rows"], R["v0_class_scenes"] = fpb_v0, fp_rows, fp_scenes
    R["row0"] = row0
    R["excluded_units"] = [[c, p] for c, p in excl_units]
    R["n_excluded_units"], R["n_excluded_cells"], R["n_excluded_pairs"] = len(excl_units), len({c for c, _ in excl_units}), len({p for _, p in excl_units})
    R["n_within_1se_of_boundary"] = near
    R["boundary_1se"] = se1
    R["coverage_measured"] = {"%s|%s" % k: v for k, v in sorted(cov.items())}
    R["fails"] = fails
    R["verdict"] = "CLASSIFICATION OK - measurement may be armed" if all(row0.values()) else "ROW 0 STOP: " + ",".join(k for k, v in row0.items() if not v)
    p = os.path.join(OUT_DIR, "classification.json")
    S1.ensure_ignored(p)
    with open(p, "w") as f:
        json.dump(R, f, indent=1)
    log(R["verdict"])
    log("V0 classification FPb = %.2f per 1,000 scenes (%d junk rows in %d scenes) -> FP clause BRANCH %s%s" % (fpb_v0, fp_rows, fp_scenes, fp_branch, " (NEAR-BAR 0.95-1.16, resolves to B)" if fp_near_bar else ""))
    log("excluded units %d (cells %d, pairs %d); within 1 SE (%.3f) of 0.20: %d of %d units" % (R["n_excluded_units"], R["n_excluded_cells"], R["n_excluded_pairs"], se1, near, len(cells) * N_PAIRS))
    for d in DELTAS:
        log("  delta %5.2f: %s" % (d, "  ".join("%s=%d" % (sb, len(cov.get((d, sb), []))) for sb in SUBBANDS)))
    per_cell = {}
    for c, p_ in excl_units:
        per_cell[c] = per_cell.get(c, 0) + 1
    log("  excluded pairs per cell: " + ", ".join("%s:%d" % (cells[c]["key"], k) for c, k in sorted(per_cell.items())))
    sys.exit(0 if all(row0.values()) else 1)


# ── verdict (phase B) ──────────────────────────────────────────────────────────
def cmd_verdict(a):
    cells = build_cells()
    vs = variants()
    with open(os.path.join(OUT_DIR, "classification.json")) as f:
        CL = json.load(f)
    excl = {(c, p) for c, p in CL["excluded_units"]}
    R = {"build": BUILD_COMMIT, "dll_sha256": DLL_SHA, "classification": {k: CL[k] for k in ("n_excluded_units", "n_excluded_cells", "n_excluded_pairs", "n_within_1se_of_boundary")}}
    # ---- load
    V0, V0B, VAR = {}, {}, {}
    fails, hdr_bad, rb_bad, short = [], 0, 0, []
    for c in range(len(cells)):
        for p in range(N_PAIRS):
            j0, j1, jv = load_job("meas", "v0", c, p), load_job("meas2", "v0", c, p), load_job("meas", "var", c, p)
            for tag, j, exp in (("v0", j0, N_MEAS), ("v0b", j1, N_MEAS), ("var", jv, N_MEAS * 26)):
                if j is None or j["trailer"] is None or len(j["recs"]) != exp:
                    short.append((tag, c, p)); continue
                if j["hdr"]["sha"] != DLL_SHA or not j["hdr"]["table_ok"] or not j["hdr"]["defaults_ok"]:
                    hdr_bad += 1
                rb_bad += j["trailer"]["readback_mismatch"]
            if j0 and j1 and jv:
                V0[(c, p)], V0B[(c, p)], VAR[(c, p)] = j0, j1, jv
    R["row0_detail"] = {"jobs_short_or_missing": len(short), "hdr_bad": hdr_bad, "readback_mismatch": rb_bad}
    row0 = {"0g": not short}
    if short:
        R["row0"] = row0; R["verdict"] = "ROW 0 STOP: 0g (incomplete: %r)" % short[:5]
        print(json.dumps(R, indent=1)); sys.exit(3)
    row0["0a"] = (hdr_bad == 0 and rb_bad == 0)
    row0["0b"] = all(file_sha(V0[k]["path"]) == file_sha(V0B[k]["path"]) or
                     [json.dumps(r, sort_keys=True) for r in V0[k]["recs"]] == [json.dumps(r, sort_keys=True) for r in V0B[k]["recs"]] for k in V0)
    # index: per (c,p): v -> {t: rec}
    IDX = {}
    for k, j in VAR.items():
        d = {}
        for r in j["recs"]:
            d.setdefault(r["v"], {})[r["t"]] = r
        IDX[k] = d
    base = {k: {r["t"]: r for r in V0[k]["recs"]} for k in V0}
    # ---- 0c/0f were checked at classification; re-assert
    row0["0c"] = CL["row0"]["0c"]
    row0["0f"] = CL["row0"]["0f"]
    fp_branch = CL["fp_branch"]
    # ---- 0d: per-scene identity of decode sha AND of F recovery between VN and V0 (=> G(VN) - G(V0) == 0 EXACTLY, without evaluating any G)
    D_FIELDS = ("f", "m", "nfp", "pc", "e")          # 0d': every field any measure reads (S16.2)
    row0["0d"] = bool(all(IDX[k]["VN"][t][fld] == base[k][t][fld] for k in IDX for t in range(N_MEAS) for fld in D_FIELDS))
    # DISCLOSURE (S16.2): the ORIGINAL 0d (decode sha) fired; name the scenes (counts only, no text)
    orig_diff = [(cells[k[0]]["key"], k[1], t, [fld for fld in ("sha", "fp") if IDX[k]["VN"][t][fld] != base[k][t][fld]])
                 for k in sorted(IDX) for t in range(N_MEAS) if IDX[k]["VN"][t]["sha"] != base[k][t]["sha"]]
    R["row0d_original_fired"] = len(orig_diff) > 0
    R["row0d_original_differing_scenes"] = [{"cell": c_, "pair": p_, "t": t_, "fields": f_} for c_, p_, t_, f_ in orig_diff]
    R["row0d_original_n_differing"], R["row0d_original_n_compared"] = len(orig_diff), sum(len(IDX[k]["VN"]) for k in IDX)
    # ---- 0e: per-lever sensitivity, from decode-stream identity only (no outcome measure)
    diff_counts = {}
    for v in vs:
        if v == DEFAULT_TRIPLE:
            continue
        diff_counts[v] = sum(1 for k in IDX for t in range(N_MEAS) if IDX[k][vname(v)][t]["sha"] != base[k][t]["sha"])
    fam = {f: {vname(v): diff_counts[v] for v in vl} for f, vl in FAMILIES.items()}
    row0["0e"] = all(any(n > 0 for n in fam[f].values()) for f in fam)
    R["0e_family_differing_scenes"] = fam
    R["0e_all_variant_differing_scenes"] = {vname(v): diff_counts[v] for v in sorted(diff_counts)}
    R["row0"] = row0
    if SMOKE:
        log("SMOKE: ROW 0 as computed = %r -- FORCED to pass so the surface code runs; NOT a verdict" % (row0,))
        row0 = {k: True for k in row0}
    if not all(row0.values()):
        # S15.4: if any row fires, NO verdict is computed at all -- no G, H1, H2 or FP of any variant has been evaluated up to here.
        R["verdict"] = "ROW 0 STOP: " + ",".join(k for k, v in row0.items() if not v) + " (no verdict computed)"
        print(json.dumps(R, indent=1, default=str)); sys.exit(1)

    # ---- every row silent: only NOW are the measures evaluated
    def rates(name_of):
        """returns G, H1[c], H2, FPb for a variant key (None => V0)"""
        hits_ex = trials_ex = 0
        h1n, h1d = {}, {}
        rec_sum = trials = fp = 0
        for (c, p), _j in base.items():
            recs = base[(c, p)] if name_of is None else IDX[(c, p)][name_of]
            for t in range(N_MEAS):
                r = recs[t]
                trials += 1
                rec_sum += bin(r["m"]).count("1")
                fp += r["nfp"]
                if (c, p) in excl:
                    hits_ex += r["f"]; trials_ex += 1
                else:
                    h1n[c] = h1n.get(c, 0) + r["f"]; h1d[c] = h1d.get(c, 0) + 1
        return {"G": hits_ex / float(trials_ex), "H1": {c: h1n[c] / float(h1d[c]) for c in h1d}, "H1_n": h1d,
                "H2": rec_sum / (11.0 * trials), "FPb": 1000.0 * fp / trials, "trials": trials, "trials_ex": trials_ex}
    M = {"V0": rates(None)}
    for v in vs:
        if v != DEFAULT_TRIPLE:
            M[vname(v)] = rates(vname(v))
    nonex_pairs = {c: sum(1 for p in range(N_PAIRS) if (c, p) not in excl) for c in range(len(cells))}
    gated = sorted(c for c in range(len(cells)) if nonex_pairs[c] >= H1_GATE_MIN_PAIRS)
    reported_only = sorted(c for c in range(len(cells)) if 1 <= nonex_pairs[c] < H1_GATE_MIN_PAIRS)
    R["h1_gated_cells"], R["h1_reported_only_cells"] = len(gated), len(reported_only)
    R["h1_cells_not_gated"] = [cells[c]["key"] for c in range(len(cells)) if c not in gated]

    import collections

    def junk_counts(vkey):
        """B' (S16.2): scene-paired COUNT differences only; text is never read."""
        S = q2 = 0
        for k in base:
            for t in range(N_MEAS):
                dd = IDX[k][vkey][t]["nfp"] - base[k][t]["nfp"]
                S += dd
                q2 += dd * dd
        return S, math.sqrt(q2)
    v0_junk_total = sum(base[k][t]["nfp"] for k in base for t in range(N_MEAS))
    R["fp_branch"], R["v0_measurement_junk_rows"] = "B-prime (counts, S16.2)" if fp_branch == "B" else "A", v0_junk_total

    def paired(v, c):
        b = c_ = n = 0
        for p in range(N_PAIRS):
            if (c, p) in excl:
                continue
            for t in range(N_MEAS):
                fv, f0 = IDX[(c, p)][vname(v)][t]["f"], base[(c, p)][t]["f"]
                n += 1
                b += (fv == 1 and f0 == 0)
                c_ += (fv == 0 and f0 == 1)
        diff = (b - c_) / float(n)
        se = math.sqrt(max(0.0, b + c_ - (b - c_) ** 2 / float(n))) / n
        return diff, se

    rows, finals = [], []
    v0 = M["V0"]
    for v in vs:
        if v == DEFAULT_TRIPLE:
            continue
        m = M[vname(v)]
        drops = {c: v0["H1"][c] - m["H1"][c] for c in gated}
        worst_c = max(drops, key=lambda c: (drops[c], -c)) if drops else None
        h1_fail = any(m["H1"][c] < v0["H1"][c] - H1_BAR for c in gated)
        h2_fail = m["H2"] < v0["H2"] - H2_BAR
        jS, jq = junk_counts(vname(v))
        jz = (jS / jq) if jq > 0 else 0.0
        jrel = jS / float(v0_junk_total) if v0_junk_total else None
        if fp_branch == "A":
            fp_fail = m["FPb"] > v0["FPb"] + FP_BAR                                   # S5.4 exactly as written (not the branch that governs here)
        else:
            fp_fail = not (jS <= 0 or (jq > 0 and jS / jq <= FP_Z))                  # S16.2 branch B': counts, one-sided, hard z = 3.0
        gain_ok = (m["G"] - v0["G"]) >= GAIN_BAR_BENCH
        clause = "H1" if h1_fail else "H2" if h2_fail else "FP" if fp_fail else "PASS" if gain_ok else "GAIN"
        wd, wse = paired(v, worst_c) if worst_c is not None else (None, None)
        rows.append({"variant": v, "G": m["G"], "dG": m["G"] - v0["G"], "worst_cell": (cells[worst_c]["key"] if worst_c is not None else None),
                     "worst_drop": (drops[worst_c] if worst_c is not None else None), "paired_diff": wd, "paired_se": wse, "H2": m["H2"], "dH2": m["H2"] - v0["H2"],
                     "FPb": m["FPb"], "dFPb": m["FPb"] - v0["FPb"], "junk_S": jS, "junk_q": jq, "junk_z": jz, "junk_rel": jrel,
                     "clause": clause, "distance": distance(v),
                     "h1_alone": bool(h1_fail and not h2_fail and not fp_fail and gain_ok)})
        if clause == "PASS":
            finals.append(v)
    ranked = sorted(finals, key=lambda v: (-M[vname(v)]["G"], distance(v), v))
    R["finalists"] = [list(v) for v in ranked[:2]]
    R["third_ranked"] = list(ranked[2]) if len(ranked) > 2 else None
    R["n_pass"] = len(ranked)
    R["ranked_pass"] = [list(v) for v in ranked]
    R["vn_in_finalists"] = False
    br = sum(1 for v in H5_BRACKET if v in ranked)
    R["h5_bracket_pass_count"] = br
    R["h5_corner_implicated"] = br >= 2
    h1a = [r for r in rows if r["h1_alone"]]
    within = [r for r in h1a if r["paired_se"] is not None and abs(r["paired_diff"]) <= 2 * r["paired_se"]]
    R["h1_alone_count"], R["h1_alone_within_2se"] = len(h1a), len(within)
    R["instrument_note_fires"] = len(within) >= 3
    R["V0"] = {"G": v0["G"], "H2": v0["H2"], "FPb": v0["FPb"], "trials_excluded": v0["trials_ex"]}
    R["surface"] = sorted(rows, key=lambda r: r["variant"])
    ung = [c for c in range(len(cells)) if c not in gated and c in v0["H1"]]
    R["finalist_ungated_cell_h1_diffs"] = {vname(v): {cells[c]["key"]: M[vname(v)]["H1"][c] - v0["H1"][c] for c in ung} for v in ranked[:3]}
    R["scope_limits"] = ["reported SNR saturates at +16 (nominal >= +15): the bench cannot show a blocker stronger than the 'full' band, so any snr_max finding "
                         "speaks to the RAMP INTERIOR only (HK-026)",
                         "bench FP is weak evidence, a gross-junk filter only (S5.3); Stage 3 is the FP primary; bench junk emission is NOT a live FP rate",
                         "one synthetic 12-station AWGN scene, 8 message pairs; cells are a design, not a sample: no number here is a live estimate"]
    R["prediction_inputs"] = {"p1_0e_all_three": row0["0e"], "p2_0c": row0["0c"], "p3_any_finalist": len(ranked) >= 1,
                              "p4_finalist_with_snr_max_below_15": any(v[1] < 15.0 for v in ranked[:2]) if ranked else None,
                              "p5_footprint_only_(-5,15,0)_pass": (-5.0, 15.0, 0.0) in ranked, "p6_h1_alone_within_2se_ge3": len(within) >= 3}
    if R["h5_corner_implicated"]:
        R["verdict"] = "H5 CORNER IMPLICATED - STOP for the Captain (report the surface)"
    elif not ranked:
        R["verdict"] = "NO FINALIST - report and stop"
    else:
        R["verdict"] = "FINALISTS: " + ", ".join(vname(v) for v in ranked[:2])
    out = os.path.join(OUT_DIR, "verdict.json")
    S1.ensure_ignored(out)
    with open(out, "w") as f:
        json.dump(R, f, indent=1, default=str)
    print(json.dumps({k: R[k] for k in ("verdict", "row0", "n_pass", "finalists", "third_ranked", "h5_bracket_pass_count", "h1_alone_count", "h1_alone_within_2se",
                                        "instrument_note_fires", "h1_gated_cells", "h1_reported_only_cells", "fp_branch", "scope_limits", "finalist_ungated_cell_h1_diffs", "prediction_inputs")}, indent=1, default=str))
    print("V0 bench junk emission (measurement set): %.2f per 1,000 scenes (%d junk rows); FP clause = %s" % (v0["FPb"], v0_junk_total, R["fp_branch"]))
    print("row 0d ORIGINAL (decode sha) FIRED: %s  (%d of %d scenes differ; disclosed, not gated)" % (R["row0d_original_fired"], R["row0d_original_n_differing"], R["row0d_original_n_compared"]))
    print("%-22s %7s %7s  %-30s %7s %6s %8s %6s %6s %7s %6s %s" % ("variant", "G", "dG", "worst-cell H1 (drop, paired diff+/-SE)", "H2", "dH2", "junk/1k", "S", "q", "z", "dist", "clause"))
    print("%-22s %7.3f %7s  %-30s %7.3f %6s %8.2f %6s %6s %7s %6s %s" % ("V0 " + vname(DEFAULT_TRIPLE), v0["G"], "-", "-", v0["H2"], "-", v0["FPb"], "-", "-", "-", "0", "-"))
    for r in R["surface"]:
        print("%-22s %7.3f %+7.3f  %-30s %7.3f %+6.3f %8.2f %+6d %6.1f %+7.2f %6.2f %s" % (vname(r["variant"]), r["G"], r["dG"],
              ("%s %.3f %+.3f/%.3f" % (r["worst_cell"][:14], r["worst_drop"], r["paired_diff"], r["paired_se"])) if r["worst_cell"] else "-",
              r["H2"], r["dH2"], r["FPb"], r["junk_S"], r["junk_q"], r["junk_z"], r["distance"], r["clause"]))


# ── junkfreq: REPORTING-ONLY junk frequency breakdown for V0 + the finalists (registered in the S16 addendum) ─────────
JF_BUCKET_HZ, JF_NB = 500.0, 7


def cmd_jobf(a):
    """One (cell, pair): re-decode the SAME scenes for V0 (setter untouched) then each finalist; record per-scene junk counts per 500 Hz bucket of the
    candidate's frequency (history-free) and assert the per-scene junk COUNT equals the stored measurement-set count (integrity of the re-decode)."""
    with open(os.path.join(OUT_DIR, "verdict.json")) as f:
        fin = [tuple(v) for v in json.load(f)["finalists"]]
    cells = build_cells()
    cell, p = cells[a.cell], a.pair
    out = os.path.join(OUT_DIR, "junkfreq_c%02d_p%d.jsonl" % (a.cell, p))
    S1.ensure_ignored(out)
    d, sha = H.load_new_dll()
    H.CFG["supp"] = None
    sh = S1.Shim(os.path.join(H.BIN_DIR, "libft8_NEW.dll"), "NEW", has_probe=False)
    S1.LIVE_NHARD = 40
    sh.set_params(S1.LIVE_PASS2)
    sig, target, f_msg, others, truth = signals_for(cell, p)
    stored_v0 = {r["t"]: r for r in load_job("meas", "v0", a.cell, p)["recs"]}
    stored_var = {}
    for r in load_job("meas", "var", a.cell, p)["recs"]:
        stored_var[(r["v"], r["t"])] = r
    pcms = [SR.render_scene(sig, SR.trial_seed(t, part_index(MEAS_BASE, a.cell, p))) for t in range(N_MEAS)]
    mism = 0
    with open(out, "w", newline="\n") as fo:
        for name, tri in [("V0", None)] + [(vname(v), v) for v in fin]:
            for t in range(N_MEAS):
                if tri is not None:
                    assert H.set_supp(d, *tri) == 0
                _n, rows, _pcl, _c = DP.decode(sh, pcms[t])
                b = [0] * JF_NB
                for r in rows:
                    if " ".join(r["message"].split()) not in truth:
                        b[min(JF_NB - 1, int(r["freq_hz"] // JF_BUCKET_HZ))] += 1
                exp = stored_v0[t]["nfp"] if tri is None else stored_var[(name, t)]["nfp"]
                mism += (sum(b) != exp)
                fo.write(json.dumps({"v": name, "t": t, "b": b, "count_matches_stored": sum(b) == exp}) + "\n")
        fo.write(json.dumps({"trailer": 1, "count_mismatch": mism, "sha": sha}) + "\n")


def cmd_junkfreq_report(a):
    cells = build_cells()
    with open(os.path.join(OUT_DIR, "verdict.json")) as f:
        fin = [vname(tuple(v)) for v in json.load(f)["finalists"]]
    tot = {v: [0] * JF_NB for v in ["V0"] + fin}
    added = {v: [0] * JF_NB for v in fin}
    removed = {v: [0] * JF_NB for v in fin}
    mism = jobs = 0
    for c in range(len(cells)):
        for p in range(N_PAIRS):
            path = os.path.join(OUT_DIR, "junkfreq_c%02d_p%d.jsonl" % (c, p))
            if not os.path.exists(path):
                log("MISSING " + path); sys.exit(3)
            per = {}
            for line in open(path):
                o = json.loads(line)
                if "trailer" in o:
                    mism += o["count_mismatch"]; jobs += 1
                else:
                    per[(o["v"], o["t"])] = o["b"]
            for t in range(N_MEAS):
                for v in ["V0"] + fin:
                    for k in range(JF_NB):
                        tot[v][k] += per[(v, t)][k]
                for v in fin:
                    for k in range(JF_NB):
                        dd = per[(v, t)][k] - per[("V0", t)][k]
                        added[v][k] += max(dd, 0); removed[v][k] += max(-dd, 0)
    R = {"bucket_hz": JF_BUCKET_HZ, "jobs": jobs, "count_mismatch_vs_stored": mism, "junk_rows_per_bucket": tot, "added_per_bucket": added, "removed_per_bucket": removed}
    p_ = os.path.join(OUT_DIR, "junkfreq.json")
    S1.ensure_ignored(p_)
    json.dump(R, open(p_, "w"), indent=1)
    print("junkfreq: %d jobs, per-scene count mismatches vs stored: %d" % (jobs, mism))
    print("bucket (Hz):        " + " ".join("%5d" % (k * JF_BUCKET_HZ) for k in range(JF_NB)))
    for v in ["V0"] + fin:
        print("junk rows %-14s" % v + " ".join("%5d" % x for x in tot[v]))
    for v in fin:
        print("  added   %-14s" % v + " ".join("%5d" % x for x in added[v]) + "   total %d" % sum(added[v]))
        print("  removed %-14s" % v + " ".join("%5d" % x for x in removed[v]) + "   total %d" % sum(removed[v]))


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("preflight").set_defaults(fn=cmd_preflight)
    j = sub.add_parser("job")
    j.add_argument("--set", choices=["class", "meas", "meas2"], required=True)
    j.add_argument("--kind", choices=["v0", "var"], required=True)
    j.add_argument("--cell", type=int, required=True)
    j.add_argument("--pair", type=int, required=True)
    j.set_defaults(fn=cmd_job)
    pl = sub.add_parser("plan")
    pl.add_argument("--phase", choices=["class", "meas"], required=True)
    pl.set_defaults(fn=cmd_plan)
    sub.add_parser("classify").set_defaults(fn=cmd_classify)
    jf = sub.add_parser("jobf")
    jf.add_argument("--cell", type=int, required=True)
    jf.add_argument("--pair", type=int, required=True)
    jf.set_defaults(fn=cmd_jobf)
    sub.add_parser("junkfreq-report").set_defaults(fn=cmd_junkfreq_report)
    sub.add_parser("verdict").set_defaults(fn=cmd_verdict)
    a = ap.parse_args()
    a.fn(a)


if __name__ == "__main__":
    main()
