"""L7 — message packing tests.

Verifies pack_message against the acceptance criteria in the QA briefing
(DEV-BRIEFING-L7-L8.md §3.4):

  1. Returns exactly 77 elements, all ∈ {0, 1}.
  2. Bit-exact against an independently-derived worked example.
  3. Deterministic: same input → same output.
  4. All supported forms (§3.2) pack without error; unsupported forms raise.
  5. (Bonus) round-trip via unpack agrees with input.

The "independently-derived worked example" uses the field-level computation
from the published reference programs (std_call_to_c28.f90, grid4_to_g15.f90)
rather than output generated by ft8_lib.  Each field value is computed
step-by-step below and cited against its source.
"""
import pytest

from synth import packing
from synth.constants import MESSAGE_BITS
from synth.packing import (
    NTOKENS, MAX22, MAXGRID4,
    _N28_CQ, _N28_DE, _N28_QRZ,
    _G15_RRR, _G15_RR73, _G15_73,
    _pack_callsign, _pack_grid_field, _pack_basecall, _normalize_to_c6,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _bits_to_int(bits: list[int]) -> int:
    """Convert an MSB-first bit list to an integer."""
    n = 0
    for b in bits:
        n = (n << 1) | b
    return n


# ---------------------------------------------------------------------------
# 1. Width and binary-ness
# ---------------------------------------------------------------------------

class TestWidth:
    def test_cq_call_grid_is_77_bits(self):
        bits = packing.pack_message("CQ Q1ABC FN42")
        assert len(bits) == MESSAGE_BITS

    def test_all_values_are_zero_or_one(self):
        bits = packing.pack_message("CQ Q1ABC FN42")
        assert all(b in (0, 1) for b in bits)

    def test_various_forms_all_77(self):
        messages = [
            "CQ Q9XYZ EN37",
            "Q1ABC Q9XYZ EN37",
            "Q1ABC Q9XYZ -10",
            "Q1ABC Q9XYZ R-10",
            "Q1ABC Q9XYZ RRR",
            "Q1ABC Q9XYZ RR73",
            "Q1ABC Q9XYZ 73",
            "Q1ABC Q9XYZ +05",
        ]
        for msg in messages:
            bits = packing.pack_message(msg)
            assert len(bits) == MESSAGE_BITS, f"Failed for {msg!r}"
            assert all(b in (0, 1) for b in bits), f"Non-binary bit for {msg!r}"


# ---------------------------------------------------------------------------
# 2. Bit-exact worked example
# ---------------------------------------------------------------------------
# Reference: field values computed step-by-step from the published algorithm
# (std_call_to_c28.f90, grid4_to_g15.f90; ft8_lib/ft8/message.c).
#
# Message: "CQ Q1ABC FN42"
#
# Field 1 — call_to = "CQ"
#   Special token CQ → n28a = 2  (source: message.c unpack28, n28 == 2 → "CQ")
#   ipa = 0  (no /R or /P suffix)
#
# Field 2 — call_de = "Q1ABC"
#   Digit at position 1 → pad left: c6 = " Q1ABC"
#   i0 = index(' ', a1) - 1 = 0   (a1 = " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ")
#   i1 = index('K', a2) - 1 = 20  (a2 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ", K is 10+10)
#   i2 = index('1', a3) - 1 = 1
#   i3 = index('A', a4) - 1 = 1   (a4 = " ABCDEFGHIJKLMNOPQRSTUVWXYZ", space=0, A=1)
#   i4 = index('B', a4) - 1 = 2
#   i5 = index('C', a4) - 1 = 3
#   n_base = ((((0*36+20)*10+1)*27+1)*27+2)*27+3 = 3957069
#   n28b = NTOKENS + MAX22 + 3957069 = 2063592 + 4194304 + 3957069 = 10214965
#   ipb = 0
#
# Field 3 — grid = "FN42"
#   Standard 4-char Maidenhead grid:
#   igrid4 = (ord('F')-ord('A'))*18*100 + (ord('N')-ord('A'))*100 + 4*10 + 2
#          = 5 * 1800 + 13 * 100 + 42
#          = 9000 + 1300 + 42 = 10342
#   ir = 0
#
# i3 = 1 (standard message type)
#
# 77-bit layout (MSB first):  n28a(28) | ipa(1) | n28b(28) | ipb(1) | ir(1) | igrid4(15) | i3(3)
#
# Bit positions (0 = MSB of 77-bit word):
#   n28a  bits  0-27 → shift = 77-28   = 49
#   ipa   bit  28    → shift = 77-29   = 48
#   n28b  bits 29-56 → shift = 77-57   = 20
#   ipb   bit  57    → shift = 77-58   = 19
#   ir    bit  58    → shift = 77-59   = 18
#   igrid4 bits 59-73 → shift = 77-74  =  3
#   i3    bits 74-76 → shift = 0
#
# As integer:
#   word = (2<<49) | (10214965<<20) | (0<<19) | (0<<18) | (10342<<3) | 1
#        = 1125899906842624 + 10711167139840 + 82736 + 1
#        = 1136611074065201
#
# (The final integer is what _bits_to_int on the returned bit-list should equal.)
_CQ_Q1ABC_FN42_EXPECTED_INT = (
    (2 << 49)
    | (10214965 << 20)
    | (0 << 19)
    | (0 << 18)
    | (10342 << 3)
    | 1
)


class TestBitExact:
    def test_cq_k1abc_fn42_field_values(self):
        """Verify each sub-field against the published algorithm derivation above."""
        # callsign 1
        n28a, ipa = _pack_callsign("CQ")
        assert n28a == _N28_CQ == 2
        assert ipa == 0

        # callsign 2
        n28b, ipb = _pack_callsign("Q1ABC")
        c6 = _normalize_to_c6("Q1ABC")
        n_base = _pack_basecall(c6)
        assert c6 == " Q1ABC"
        assert n_base == 3_957_069
        assert n28b == NTOKENS + MAX22 + 3_957_069 == 10_214_965
        assert ipb == 0

        # grid
        ir, igrid4 = _pack_grid_field("FN42")
        assert ir == 0
        assert igrid4 == 10_342

    def test_cq_k1abc_fn42_full_77_bits(self):
        """Full bit-vector must equal the step-by-step derivation."""
        bits = packing.pack_message("CQ Q1ABC FN42")
        assert _bits_to_int(bits) == _CQ_Q1ABC_FN42_EXPECTED_INT

    def test_i3_field_is_always_1(self):
        """The 3 LSBs (i3) must be 0,0,1 for every standard message."""
        for msg in ["CQ Q1ABC FN42", "Q9XYZ Q1ABC -10", "Q1ABC Q9XYZ RRR"]:
            bits = packing.pack_message(msg)
            assert bits[-3:] == [0, 0, 1], f"i3 ≠ 1 for {msg!r}"


# ---------------------------------------------------------------------------
# 3. Determinism
# ---------------------------------------------------------------------------

class TestDeterminism:
    def test_same_message_gives_same_bits(self):
        msg = "Q1ABC Q9XYZ EN37"
        assert packing.pack_message(msg) == packing.pack_message(msg)

    def test_case_insensitive(self):
        assert packing.pack_message("CQ Q1ABC FN42") == packing.pack_message("cq k1abc fn42")


# ---------------------------------------------------------------------------
# 4. All supported forms pack without error; unsupported forms raise
# ---------------------------------------------------------------------------

class TestSupportedForms:
    """Every form listed in §3.2 of the briefing must succeed."""

    def test_cq_call_grid(self):
        packing.pack_message("CQ Q1ABC FN42")

    def test_call1_call2_grid(self):
        packing.pack_message("Q1ABC Q9XYZ EN37")

    def test_signal_report_positive(self):
        packing.pack_message("Q1ABC Q9XYZ +05")

    def test_signal_report_negative(self):
        packing.pack_message("Q1ABC Q9XYZ -10")

    def test_r_prefixed_report(self):
        packing.pack_message("Q1ABC Q9XYZ R-10")

    def test_r_prefixed_positive(self):
        packing.pack_message("Q1ABC Q9XYZ R+05")

    def test_rrr(self):
        packing.pack_message("Q1ABC Q9XYZ RRR")

    def test_rr73(self):
        packing.pack_message("Q1ABC Q9XYZ RR73")

    def test_73(self):
        packing.pack_message("Q1ABC Q9XYZ 73")

    def test_de_token(self):
        packing.pack_message("DE Q1ABC FN42")

    def test_qrz_token(self):
        packing.pack_message("QRZ Q1ABC FN42")

    def test_rover_suffix(self):
        packing.pack_message("Q1ABC Q9XYZ/R EN37")


class TestSpecialTokenValues:
    """Spot-check that special token n28 values match the published assignment."""

    def test_cq_n28_is_2(self):
        n28, ipa = _pack_callsign("CQ")
        assert n28 == 2

    def test_de_n28_is_0(self):
        n28, _ = _pack_callsign("DE")
        assert n28 == 0

    def test_qrz_n28_is_1(self):
        n28, _ = _pack_callsign("QRZ")
        assert n28 == 1

    def test_standard_call_above_threshold(self):
        n28, _ = _pack_callsign("Q1ABC")
        assert n28 >= NTOKENS + MAX22

    def test_grid_fn42_value(self):
        _, igrid4 = _pack_grid_field("FN42")
        assert igrid4 == 10_342

    def test_grid_aa00_is_zero(self):
        _, igrid4 = _pack_grid_field("AA00")
        assert igrid4 == 0

    def test_rrr_g15_value(self):
        ir, g15 = _pack_grid_field("RRR")
        assert ir == 0
        assert g15 == _G15_RRR

    def test_rr73_g15_value(self):
        ir, g15 = _pack_grid_field("RR73")
        assert ir == 0
        assert g15 == _G15_RR73

    def test_73_g15_value(self):
        ir, g15 = _pack_grid_field("73")
        assert ir == 0
        assert g15 == _G15_73

    def test_report_minus10_ir_and_g15(self):
        ir, g15 = _pack_grid_field("-10")
        assert ir == 0
        assert g15 == MAXGRID4 + (35 + (-10))   # = 32425

    def test_r_report_sets_ir(self):
        ir, g15 = _pack_grid_field("R-10")
        assert ir == 1
        assert g15 == MAXGRID4 + (35 + (-10))   # same g15 value, ir differs


class TestUnsupportedForms:
    def test_two_fields_raises(self):
        with pytest.raises(ValueError):
            packing.pack_message("CQ Q1ABC")

    def test_four_fields_raises(self):
        with pytest.raises(ValueError):
            packing.pack_message("CQ Q1ABC FN42 EXTRA")

    def test_bad_grid_raises(self):
        with pytest.raises(ValueError):
            packing.pack_message("Q1ABC Q9XYZ ZZZZ")

    def test_invalid_callsign_format_raises(self):
        """A callsign with no recognisable digit position raises."""
        with pytest.raises(ValueError):
            packing.pack_message("Q1ABC AAAAA FN42")  # AAAAA has no digit at pos 1 or 2


# ---------------------------------------------------------------------------
# 5. Various callsign forms normalise correctly
# ---------------------------------------------------------------------------

class TestCallsignNormalise:
    def test_5char_digit_at_1(self):
        assert _normalize_to_c6("Q1ABC") == " Q1ABC"

    def test_5char_digit_at_1_w9(self):
        assert _normalize_to_c6("Q9XYZ") == " Q9XYZ"

    def test_6char_digit_at_2(self):
        assert _normalize_to_c6("QK4AAA") == "QK4AAA"

    def test_4char_digit_at_1(self):
        # Q5OK → " Q5OK " (trailing space)
        assert _normalize_to_c6("Q5OK") == " Q5OK "

    def test_5char_digit_at_2(self):
        # QG5AB → "QG5AB " (trailing space)
        assert _normalize_to_c6("QG5AB") == "QG5AB "
