"""Cross-platform Gauge R&R analyser — Windows (WASAPI) vs Linux/WSL2 vs WSJT-X.

Usage:
    python harness/analyse_xplat.py --run-dir <dir> [--scenario S1,S2]

Reads *_matched.csv files generated by harness/matcher_xplat.py (appraiser
names "Windows", "Linux", and optionally "WSJT-X"), computes ANOVA-method
Gauge R&R variance components, cross-platform bias, McNemar's test, FP
parity, DT jitter, and writes report.md + PNG charts.

Three-appraiser operation:
  When wsjt-all.txt is present in the run directory, WSJT-X is included as
  a third appraiser and all pairwise metrics (bias, McNemar, Fisher, kappa)
  are computed for all N*(N-1)/2 = 3 pairs.

Graceful degradation:
  If WSJT-X rows are absent from the matched CSVs (because wsjt-all.txt was
  not available during matching), all WSJT-X-related pair metrics return NaN
  and the report omits the affected rows — no crash.

Key differences from harness/analyse.py:
  - Appraisers: "Windows" / "Linux" / "WSJT-X" (Windows+Linux only if WSJT-X absent)
  - No WSJT-X DT convention correction (all platforms use UTC-boundary DT)
  - Added: platform SNR/DT/freq bias gate for all pairs, DT jitter time-series,
    McNemar's test for all pairs, Fisher's exact FP parity for all pairs
  - report.md uses NFR-023 five-section structure (Sections 1 & 5 QA-authored)
"""
from __future__ import annotations

import argparse
import itertools
import math
import subprocess
import sys
from pathlib import Path
from typing import Any

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from scipy.stats import t as tdist, chi2 as chi2dist, fisher_exact

# Resolve qa/rr-study as package root
_QA_ROOT = Path(__file__).resolve().parent.parent
if str(_QA_ROOT) not in sys.path:
    sys.path.insert(0, str(_QA_ROOT))

# ---------------------------------------------------------------------------
# Import appraiser-agnostic functions from analyse.py
# ---------------------------------------------------------------------------
from harness.analyse import (
    _git_sha,
    _verdict_grr, _verdict_ndc, _verdict_kappa, _verdict_fp, _verdict_bias,
    _fmt_num,
    _load_scenario_meta, _load_matched_csvs,
    _two_way_anova, _derived_metrics,
    _plot_grr_panel,
    _cohen_kappa_ci,
    CONTINUOUS_SCENARIOS, ATTRIBUTE_SCENARIOS, DECODE_RATE_SCENARIOS,
    DECODE_RATE_CONFIG, RESPONSE_VAR, TOLERANCE_HALF, REQUIRED_COLUMNS,
    THRESH_GRR_PASS, THRESH_GRR_MARGINAL, NDC_FAIL, NDC_PASS,
    THRESH_KAPPA_PASS, THRESH_KAPPA_MARGINAL, THRESH_BIAS_PASS,
)

# ---------------------------------------------------------------------------
# Cross-platform appraiser labels and thresholds
# ---------------------------------------------------------------------------

APPRAISERS = ("Windows", "Linux", "WSJT-X")

# STUDY-SPEC-XPLAT §8.1 — platform bias gates
THRESH_PLATFORM_SNR_PASS      = 1.0    # dB — PASS
THRESH_PLATFORM_SNR_MARGINAL  = 2.0    # dB — MARGINAL; > 2 dB → FAIL
THRESH_PLATFORM_DT_PASS       = 0.1    # s
THRESH_PLATFORM_DT_MARGINAL   = 0.2    # s
THRESH_PLATFORM_FREQ_PASS     = 2.0    # Hz
THRESH_PLATFORM_FREQ_MARGINAL = 4.0    # Hz

# STUDY-SPEC-XPLAT §8.2 — attribute gates
THRESH_KAPPA_XPLAT_PASS      = 0.90
THRESH_KAPPA_XPLAT_MARGINAL  = 0.75   # between-platform kappa
THRESH_MCNEMAR_P             = 0.05   # McNemar α

# ---------------------------------------------------------------------------
# Verdict helpers (platform bias)
# ---------------------------------------------------------------------------

def _verdict_platform_bias(bias: float, pass_thr: float, marginal_thr: float) -> str:
    if abs(bias) <= pass_thr:
        return "PASS"
    if abs(bias) <= marginal_thr:
        return "MARGINAL"
    return "FAIL"


def _verdict_kappa_xplat(kappa: float) -> str:
    if kappa >= THRESH_KAPPA_XPLAT_PASS:
        return "PASS"
    if kappa >= THRESH_KAPPA_XPLAT_MARGINAL:
        return "MARGINAL"
    return "FAIL"


def _verdict_mcnemar(p: float) -> str:
    return "PASS" if p >= THRESH_MCNEMAR_P else "FAIL"


def _verdict_fisher(p: float) -> str:
    return "PASS" if p >= THRESH_MCNEMAR_P else "FAIL"


# ---------------------------------------------------------------------------
# Bias & linearity (local version: uses module-level APPRAISERS)
# ---------------------------------------------------------------------------

def _bias_linearity(df_matched: pd.DataFrame, run_dir: Path) -> dict:
    df = df_matched[df_matched["matched"] == True].copy()
    df["reported_snr_db"] = pd.to_numeric(df["reported_snr_db"], errors="coerce")
    df["true_snr_db"] = pd.to_numeric(df["true_snr_db"], errors="coerce")
    df = df.dropna(subset=["reported_snr_db", "true_snr_db"])
    df["bias"] = df["reported_snr_db"] - df["true_snr_db"]

    results: dict[str, dict] = {}

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.axhline(0, color="black", linestyle="--", lw=0.8)

    appraisers_in_data = [a for a in APPRAISERS if a in df["appraiser"].values]
    for appr in appraisers_in_data:
        sub = df[df["appraiser"] == appr]
        if sub.empty:
            continue
        x = sub["true_snr_db"].values
        y = sub["bias"].values
        mean_bias = float(np.mean(y))
        coeffs = np.polyfit(x, y, 1)
        slope, intercept = float(coeffs[0]), float(coeffs[1])
        y_pred = np.polyval(coeffs, x)
        ss_res = float(np.sum((y - y_pred) ** 2))
        ss_tot = float(np.sum((y - np.mean(y)) ** 2))
        r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else 0.0

        results[appr] = {"mean_bias": mean_bias, "slope": slope,
                         "intercept": intercept, "r2": r2}

        x_line = np.linspace(x.min(), x.max(), 50)
        ax.scatter(x, y, label=f"{appr} (bias)", alpha=0.6, s=20)
        ax.plot(x_line, np.polyval(coeffs, x_line),
                label=f"{appr} fit (slope={slope:.3f})")

    ax.set_xlabel("True SNR (dB)")
    ax.set_ylabel("Bias = Reported - True (dB)")
    ax.set_title("S1 Bias & Linearity")
    ax.legend(fontsize=8)
    plt.tight_layout()
    out_path = run_dir / "S1_bias_linearity.png"
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return results


# ---------------------------------------------------------------------------
# Platform bias metrics — all N*(N-1)/2 appraiser pairs
# ---------------------------------------------------------------------------

def _platform_bias_metrics_all(
    df_matched: pd.DataFrame,
    response: str,
    appraisers: tuple[str, ...] = APPRAISERS,
) -> dict[tuple[str, str], dict]:
    """Compute pairwise (B − A) bias for every appraiser combination.

    Returns ``{(A, B): bias_dict}`` for all i<j pairs in *appraisers*.
    ``bias = appraiser_B − appraiser_A`` (same sign convention as the
    original Linux−Windows analysis).  Pairs where either appraiser has no
    data return NaN metrics — the caller must handle these gracefully.
    """
    df = df_matched[df_matched["matched"] == True].copy()
    df[response] = pd.to_numeric(df[response], errors="coerce")
    df = df.dropna(subset=[response, "part_index", "trial_index", "appraiser"])

    pivot = df.pivot_table(
        index=["part_index", "trial_index"],
        columns="appraiser",
        values=response,
        aggfunc="mean",
    )

    _nan_row: dict = {"mean_bias": float("nan"), "t_stat": float("nan"),
                      "p_value": float("nan"), "n_pairs": 0, "verdict": "—"}
    results: dict[tuple[str, str], dict] = {}

    for a, b in itertools.combinations(appraisers, 2):
        if a not in pivot.columns or b not in pivot.columns:
            results[(a, b)] = dict(_nan_row)
            continue
        paired = pivot[[a, b]].dropna()
        n = len(paired)
        if n < 2:
            results[(a, b)] = {**_nan_row, "n_pairs": n}
            continue
        diffs = paired[b] - paired[a]
        mean_bias = float(diffs.mean())
        se = float(diffs.std(ddof=1) / np.sqrt(n))
        t_stat = mean_bias / se if se > 0 else float("inf")
        p_value = float(2 * (1 - tdist.cdf(abs(t_stat), df=n - 1)))
        results[(a, b)] = {
            "mean_bias": mean_bias, "t_stat": t_stat,
            "p_value": p_value, "n_pairs": n, "verdict": "—",
        }
    return results


# ---------------------------------------------------------------------------
# Platform bias chart — multi-panel, one panel per appraiser pair
# ---------------------------------------------------------------------------

def _platform_bias_chart(
    df_s1: pd.DataFrame,
    run_dir: Path,
    appraisers: tuple[str, ...] = APPRAISERS,
) -> Path | None:
    """Scatter plots of (SNR_B − SNR_A) vs true SNR for every appraiser pair.

    Generates a single PNG with one subplot per pair.  Returns None if no
    pair has sufficient data.
    """
    pairs = list(itertools.combinations(appraisers, 2))
    if not pairs:
        return None

    df = df_s1[df_s1["matched"] == True].copy()
    df["reported_snr_db"] = pd.to_numeric(df["reported_snr_db"], errors="coerce")
    df["true_snr_db"] = pd.to_numeric(df["true_snr_db"], errors="coerce")
    df = df.dropna(subset=["reported_snr_db", "true_snr_db", "part_index", "trial_index"])

    pivot = df.pivot_table(
        index=["part_index", "trial_index"],
        columns="appraiser",
        values="reported_snr_db",
        aggfunc="mean",
    )
    true_snr = df.groupby(["part_index", "trial_index"])["true_snr_db"].mean()
    pivot = pivot.join(true_snr, how="inner")

    n_pairs = len(pairs)
    fig, axes = plt.subplots(1, n_pairs, figsize=(7 * n_pairs, 5), squeeze=False)
    any_data = False

    for idx, (a, b) in enumerate(pairs):
        ax = axes[0][idx]
        if a not in pivot.columns or b not in pivot.columns:
            ax.text(0.5, 0.5, f"No data\n{b} − {a}",
                    transform=ax.transAxes, ha="center", va="center")
            ax.set_title(f"S1 SNR Bias ({b} − {a})")
            continue
        paired = pivot[[a, b, "true_snr_db"]].dropna()
        if len(paired) < 2:
            continue
        diffs = (paired[b] - paired[a]).values
        x = paired["true_snr_db"].values
        coeffs = np.polyfit(x, diffs, 1)
        x_line = np.linspace(x.min(), x.max(), 50)

        ax.axhline(0, color="black", linestyle="--", lw=0.8, label="Zero bias")
        ax.axhline( 2, color="red", linestyle=":", lw=0.8, label="+2 dB gate")
        ax.axhline(-2, color="red", linestyle=":", lw=0.8, label="-2 dB gate")
        ax.scatter(x, diffs, alpha=0.7, s=25, label=f"{b}−{a} (n={len(diffs)})")
        ax.plot(x_line, np.polyval(coeffs, x_line), color="orange",
                label=f"Fit: slope={coeffs[0]:.3f}")
        ax.set_xlabel("True SNR (dB)")
        ax.set_ylabel(f"SNR_{b} − SNR_{a} (dB)")
        ax.set_title(f"S1 Platform SNR Bias ({b} − {a})")
        ax.legend(fontsize=7)
        any_data = True

    if not any_data:
        plt.close(fig)
        return None

    plt.tight_layout()
    out_path = run_dir / "S1_platform_bias.png"
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return out_path


# ---------------------------------------------------------------------------
# DT jitter time-series — all appraiser pairs on one chart
# ---------------------------------------------------------------------------

def _dt_jitter_timeseries(
    df_s3: pd.DataFrame,
    run_dir: Path,
    appraisers: tuple[str, ...] = APPRAISERS,
) -> Path | None:
    """Time-series of DT_B − DT_A for all appraiser pairs across S3 trials."""
    pairs = list(itertools.combinations(appraisers, 2))
    if not pairs:
        return None

    df = df_s3[df_s3["matched"] == True].copy()
    df["reported_dt_s"] = pd.to_numeric(df["reported_dt_s"], errors="coerce")
    df = df.dropna(subset=["reported_dt_s", "part_index", "trial_index",
                            "appraiser", "cycle_utc"])

    pivot = df.pivot_table(
        index=["cycle_utc", "part_index", "trial_index"],
        columns="appraiser",
        values="reported_dt_s",
        aggfunc="mean",
    ).reset_index().sort_values("cycle_utc")

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.axhline(0, color="black", linestyle="--", lw=0.8)
    ax.axhline( 0.1, color="orange", linestyle=":", lw=0.8, label="±0.1 s PASS gate")
    ax.axhline(-0.1, color="orange", linestyle=":", lw=0.8)
    ax.axhline( 0.2, color="red",    linestyle=":", lw=0.8, label="±0.2 s MARGINAL gate")
    ax.axhline(-0.2, color="red",    linestyle=":", lw=0.8)

    any_data = False
    for a, b in pairs:
        if a not in pivot.columns or b not in pivot.columns:
            continue
        paired = pivot[[a, b, "cycle_utc"]].dropna()
        if len(paired) < 2:
            continue
        diffs = (paired[b] - paired[a]).values
        x = np.arange(len(diffs))
        ax.plot(x, diffs, marker="o", ms=3, label=f"DT_{b} − DT_{a}")
        if len(diffs) >= 5:
            rm = pd.Series(diffs).rolling(5, center=True).mean()
            ax.plot(x, rm, lw=1.5, linestyle="--",
                    label=f"Rolling mean ({b}−{a})")
        any_data = True

    if not any_data:
        plt.close(fig)
        return None

    ax.set_xlabel("Trial (cycle order)")
    ax.set_ylabel("DT difference (s)")
    ax.set_title("S3 DT Jitter Time-Series (all pairs)")
    ax.legend(fontsize=8)
    plt.tight_layout()
    out_path = run_dir / "S3_dt_jitter.png"
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return out_path


# ---------------------------------------------------------------------------
# McNemar's test — all appraiser pairs
# ---------------------------------------------------------------------------

def _mcnemar_test(
    df_all: dict[str, pd.DataFrame],
    appraisers: tuple[str, ...] = APPRAISERS,
) -> dict[tuple[str, str], dict]:
    """McNemar's test on pooled binary decode decisions for every appraiser pair.

    Returns ``{(A, B): result_dict}`` for all i<j pairs.
    *n_ab* = A decoded, B did not; *n_ba* = B decoded, A did not.
    """
    counts: dict[tuple[str, str], list[int]] = {
        (a, b): [0, 0] for a, b in itertools.combinations(appraisers, 2)
    }

    for scen_id, df in df_all.items():
        df_sub = df[df["false_positive"] == False].copy()
        if df_sub.empty:
            continue
        pivot = df_sub.pivot_table(
            index=["part_index", "trial_index", "message_text", "cycle_utc"],
            columns="appraiser",
            values="matched",
            aggfunc="any",
        )
        for (a, b), cnt in counts.items():
            if a not in pivot.columns or b not in pivot.columns:
                continue
            paired = pivot[[a, b]].dropna()
            cnt[0] += int(((paired[a] == True) & (paired[b] == False)).sum())
            cnt[1] += int(((paired[a] == False) & (paired[b] == True)).sum())

    results: dict[tuple[str, str], dict] = {}
    for (a, b), (n_ab, n_ba) in counts.items():
        total = n_ab + n_ba
        if total == 0:
            results[(a, b)] = {"n_ab": 0, "n_ba": 0, "chi2": float("nan"),
                               "p_value": float("nan"), "verdict": "PASS"}
            continue
        chi2 = (abs(n_ab - n_ba) - 1) ** 2 / total
        p_value = float(1 - chi2dist.cdf(chi2, df=1))
        results[(a, b)] = {
            "n_ab": n_ab, "n_ba": n_ba,
            "chi2": chi2, "p_value": p_value,
            "verdict": _verdict_mcnemar(p_value),
        }
    return results


# ---------------------------------------------------------------------------
# False-positive rate (local version using module-level APPRAISERS)
# ---------------------------------------------------------------------------

def _fp_rate(df_matched: pd.DataFrame) -> dict[str, dict]:
    """FP rate per appraiser for S5 (scoped to S5 injection window)."""
    _NAN: dict = {
        "decode_rate": float("nan"), "event_rate": float("nan"),
        "n_fp_events": float("nan"), "n_fp_decodes": float("nan"),
        "n_slots": 0, "rob_95": None,
    }
    results: dict[str, dict] = {}

    s5_truth_rows = df_matched[df_matched["false_positive"] == False]
    s5_cycles: set = set(s5_truth_rows["cycle_utc"].dropna().unique())

    for appr in APPRAISERS:
        sub = df_matched[df_matched["appraiser"] == appr]
        if sub.empty:
            results[appr] = _NAN.copy()
            continue
        truth_sub = sub[sub["false_positive"] == False]
        fp_sub = sub[sub["false_positive"] == True]
        n_slots = int(len(truth_sub))
        fp_in_window = fp_sub[fp_sub["cycle_utc"].isin(s5_cycles)] if s5_cycles else fp_sub

        if n_slots == 0:
            results[appr] = _NAN.copy()
            continue

        n_fp_decodes = int(len(fp_in_window))
        n_fp_events  = int(fp_in_window["cycle_utc"].nunique())
        decode_rate  = 100.0 * n_fp_decodes / n_slots
        event_rate   = 100.0 * n_fp_events  / n_slots
        rob_95       = (300.0 / n_slots) if n_fp_events == 0 else None

        results[appr] = {
            "decode_rate": decode_rate, "event_rate": event_rate,
            "n_fp_events": n_fp_events, "n_fp_decodes": n_fp_decodes,
            "n_slots": n_slots, "rob_95": rob_95,
        }
    return results


# ---------------------------------------------------------------------------
# Fisher's exact FP parity — all appraiser pairs
# ---------------------------------------------------------------------------

def _fp_parity_fisher(
    fp_results: dict,
    appraisers: tuple[str, ...] = APPRAISERS,
) -> dict[tuple[str, str], dict]:
    """Fisher's exact test on FP event counts for every appraiser pair."""
    results: dict[tuple[str, str], dict] = {}

    for a, b in itertools.combinations(appraisers, 2):
        info_a = fp_results.get(a, {})
        info_b = fp_results.get(b, {})
        events_a = info_a.get("n_fp_events", float("nan"))
        events_b = info_b.get("n_fp_events", float("nan"))
        slots_a  = info_a.get("n_slots", 0)
        slots_b  = info_b.get("n_slots", 0)

        if (isinstance(events_a, float) and math.isnan(events_a)) \
                or slots_a == 0 or slots_b == 0:
            results[(a, b)] = {"p_value": float("nan"), "verdict": "—"}
            continue

        table = [[int(events_a), int(events_b)],
                 [slots_a - int(events_a), slots_b - int(events_b)]]
        try:
            _, p = fisher_exact(table)
            results[(a, b)] = {"p_value": float(p), "verdict": _verdict_fisher(p)}
        except Exception:
            results[(a, b)] = {"p_value": float("nan"), "verdict": "—"}

    return results


# ---------------------------------------------------------------------------
# Attribute agreement (local version — pairwise kappa for all N*(N-1)/2 pairs)
# ---------------------------------------------------------------------------

def _attribute_agreement(matched: dict[str, pd.DataFrame], run_dir: Path) -> dict:
    """Pooled attribute agreement: S4 positives + S5 negatives."""
    pos_df = matched.get("S4")
    neg_df = matched.get("S5")

    units: dict[str, dict[tuple, tuple]] = {a: {} for a in APPRAISERS}

    if pos_df is not None:
        d = pos_df[pos_df["false_positive"] == False]
        for _, r in d.iterrows():
            appr = r["appraiser"]
            if appr not in units:
                continue
            key   = ("S4", r["part_index"], r["trial_index"], r["cycle_utc"], r["message_text"])
            group = ("S4", r["part_index"], r["message_text"])
            units[appr][key] = (True, bool(r["matched"]), group)

    if neg_df is not None:
        truth_rows = neg_df[neg_df["false_positive"] == False]
        s5_cycles  = set(truth_rows["cycle_utc"].dropna().unique())
        for appr in APPRAISERS:
            sub = neg_df[neg_df["appraiser"] == appr]
            if sub.empty:
                continue
            fp_cycles = set(sub[sub["false_positive"] == True]["cycle_utc"]) & s5_cycles
            for _, r in sub[sub["false_positive"] == False].iterrows():
                cyc   = r["cycle_utc"]
                key   = ("S5", r["part_index"], r["trial_index"], cyc, "")
                group = ("S5", r["part_index"], "")
                units[appr][key] = (False, cyc in fp_cycles, group)

    confusion: dict[str, dict] = {}
    for appr in APPRAISERS:
        tp = fp = fn = tn = 0
        for truth, call, _ in units[appr].values():
            if truth and call:
                tp += 1
            elif truth and not call:
                fn += 1
            elif (not truth) and call:
                fp += 1
            else:
                tn += 1
        confusion[appr] = {"TP": tp, "FN": fn, "FP": fp, "TN": tn,
                           "n_pos": tp + fn, "n_neg": fp + tn}

    kappa: dict[str, dict] = {}
    # Each appraiser vs truth
    for appr in APPRAISERS:
        if not units[appr]:
            kappa[f"{appr}_vs_truth"] = {"kappa": float("nan"),
                                         "ci_lo": float("nan"), "ci_hi": float("nan")}
            continue
        keys  = sorted(units[appr].keys())
        truth = [units[appr][k][0] for k in keys]
        call  = [units[appr][k][1] for k in keys]
        kappa[f"{appr}_vs_truth"] = _cohen_kappa_ci(truth, call)

    # All pairwise between-appraiser kappas
    for a0, a1 in itertools.combinations(APPRAISERS, 2):
        common = sorted(set(units.get(a0, {}).keys()) & set(units.get(a1, {}).keys()))
        if not common:
            kappa[f"{a0}_vs_{a1}"] = {"kappa": float("nan"),
                                      "ci_lo": float("nan"), "ci_hi": float("nan")}
            continue
        c0 = [units[a0][k][1] for k in common]
        c1 = [units[a1][k][1] for k in common]
        ba = _cohen_kappa_ci(c0, c1)
        kappa[f"{a0}_vs_{a1}"] = {"kappa": ba.get("kappa", float("nan")),
                                  "ci_lo": ba.get("ci_lo", float("nan")),
                                  "ci_hi": ba.get("ci_hi", float("nan"))}

    repeatability: dict[str, float] = {}
    for appr in APPRAISERS:
        groups: dict[tuple, list[bool]] = {}
        for truth, call, grp in units[appr].values():
            groups.setdefault(grp, []).append(call)
        if groups:
            consistent = sum(1 for v in groups.values() if len(set(v)) == 1)
            repeatability[appr] = 100.0 * consistent / len(groups)
        else:
            repeatability[appr] = float("nan")

    return {"kappa": kappa, "repeatability": repeatability, "confusion": confusion}


def _attribute_report_lines(attr: dict) -> list[str]:
    lines: list[str] = ["## Attribute Agreement Analysis (S4 positives + S5 negatives)", ""]
    lines += [
        "_Pooled attribute agreement: S4 injected messages (truth = present) "
        "and S5 signal-free slots (truth = absent)._",
        "",
    ]

    lines += ["### Confusion vs truth", ""]
    lines += [f"| Appraiser | TP | FN | FP | TN | Recovery | Specificity |",
              "|---|---|---|---|---|---|---|"]
    for appr in APPRAISERS:
        c = attr["confusion"].get(appr, {})
        tp, fn, fp, tn = c.get("TP", 0), c.get("FN", 0), c.get("FP", 0), c.get("TN", 0)
        rec  = 100.0 * tp / (tp + fn) if (tp + fn) else float("nan")
        spec = 100.0 * tn / (tn + fp) if (tn + fp) else float("nan")
        lines.append(
            f"| {appr} | {tp} | {fn} | {fp} | {tn} | "
            f"{_fmt_num(rec)}% | {_fmt_num(spec)}% |"
        )
    lines += [""]

    lines += ["### Kappa", ""]
    lines += ["| Pair | kappa | 95% CI | Gate | Verdict |", "|---|---|---|---|---|"]
    for label, info in sorted(attr["kappa"].items()):
        k     = info.get("kappa", float("nan"))
        ci_lo = info.get("ci_lo", float("nan"))
        ci_hi = info.get("ci_hi", float("nan"))
        if not (isinstance(ci_lo, float) and math.isnan(ci_lo)):
            ci = f"[{_fmt_num(ci_lo)}, {_fmt_num(ci_hi)}]"
        else:
            ci = "—"
        if "_vs_truth" in label:
            gate = f">= {THRESH_KAPPA_PASS}"
            v    = _verdict_kappa(k) if not math.isnan(k) else "—"
        else:
            gate = f">= {THRESH_KAPPA_XPLAT_PASS}"
            v    = _verdict_kappa_xplat(k) if not math.isnan(k) else "—"
        lines.append(f"| {label} | {_fmt_num(k, '.3f')} | {ci} | {gate} | {v} |")
    lines += [""]

    lines += ["### Within-platform repeatability (decision consistency across trials)", ""]
    lines += ["| Platform | Consistent groups |", "|---|---|"]
    for appr in APPRAISERS:
        lines.append(f"| {appr} | {_fmt_num(attr['repeatability'].get(appr, float('nan')))}% |")
    lines += [""]
    return lines


# ---------------------------------------------------------------------------
# S7 — Co-channel / compounding (generalised to N appraisers)
# ---------------------------------------------------------------------------

def _analyse_compounding(
    df_matched: pd.DataFrame,
    scen_meta: dict | None,
    run_dir: Path,
) -> dict:
    df = df_matched[df_matched["false_positive"] == False].copy()
    df["matched"]     = df["matched"].astype(bool)
    df["part_index"]  = pd.to_numeric(df["part_index"],  errors="coerce")
    df["true_snr_db"] = pd.to_numeric(df["true_snr_db"], errors="coerce")

    part_meta: dict[int, dict] = {}
    for p in (scen_meta or {}).get("parts", []):
        part_meta[int(p["part_index"])] = {
            "overlap_type": p.get("overlap_type", "?"),
            "label":        p.get("label", ""),
            "n_signals":    len(p.get("signals", [])),
        }

    df["overlap_type"] = df["part_index"].map(
        lambda i: part_meta.get(int(i), {}).get("overlap_type", "?")
        if pd.notna(i) else "?"
    )

    # Only include appraisers present in the data
    appraisers_in = [a for a in APPRAISERS if a in df["appraiser"].unique()]

    overall: dict[str, float] = {}
    for appr in appraisers_in:
        sub = df[df["appraiser"] == appr]
        overall[appr] = 100.0 * sub["matched"].mean() if len(sub) else float("nan")

    by_type: dict[str, dict[str, float]] = {}
    for ot in sorted(df["overlap_type"].unique()):
        by_type[ot] = {}
        for appr in appraisers_in:
            sub = df[(df["overlap_type"] == ot) & (df["appraiser"] == appr)]
            by_type[ot][appr] = 100.0 * sub["matched"].mean() if len(sub) else float("nan")

    per_part: list[dict] = []
    for pi in sorted(df["part_index"].dropna().unique()):
        meta = part_meta.get(int(pi), {})
        row: dict = {
            "part_index":   int(pi),
            "overlap_type": meta.get("overlap_type", "?"),
            "label":        meta.get("label", ""),
        }
        for appr in appraisers_in:
            sub = df[(df["part_index"] == pi) & (df["appraiser"] == appr)]
            row[appr] = (int(sub["matched"].sum()), int(len(sub)))
        per_part.append(row)

    capture: dict[str, dict[str, float]] = {}
    df_cap = df[df["overlap_type"] == "capture"].copy()
    if not df_cap.empty:
        part_max       = df_cap.groupby("part_index")["true_snr_db"].transform("max")
        df_cap["role"] = np.where(np.isclose(df_cap["true_snr_db"], part_max), "strong", "weak")
        for appr in appraisers_in:
            capture[appr] = {}
            for role in ("strong", "weak"):
                sub = df_cap[(df_cap["appraiser"] == appr) & (df_cap["role"] == role)]
                capture[appr][role] = 100.0 * sub["matched"].mean() if len(sub) else float("nan")

    # Pairwise between-appraiser per-signal agreement
    keyed: dict[str, dict[tuple, bool]] = {}
    for appr in appraisers_in:
        sub = df[df["appraiser"] == appr]
        d: dict[tuple, bool] = {}
        for _, r in sub.iterrows():
            key = (r["part_index"], r["trial_index"], r["message_text"], r["true_freq_hz"])
            d[key] = bool(r["matched"])
        keyed[appr] = d

    between_app: dict[str, float] = {}
    for a0, a1 in itertools.combinations(appraisers_in, 2):
        common = set(keyed.get(a0, {})) & set(keyed.get(a1, {}))
        if common:
            agree = sum(1 for k in common if keyed[a0][k] == keyed[a1][k])
            between_app[f"{a0} vs {a1}"] = 100.0 * agree / len(common)

    chart_path = None
    if per_part and appraisers_in:
        n_appr = len(appraisers_in)
        width  = 0.8 / n_appr
        fig, ax = plt.subplots(figsize=(13, 5))
        x = np.arange(len(per_part))
        for i, appr in enumerate(appraisers_in):
            offset = (i - (n_appr - 1) / 2.0) * width
            vals = [
                (100.0 * r[appr][0] / r[appr][1]) if r.get(appr) and r[appr][1] else 0.0
                for r in per_part
            ]
            ax.bar(x + offset, vals, width, label=appr)
        ax.set_xticks(x)
        ax.set_xticklabels(
            [f"P{r['part_index']}\n{r['overlap_type']}\n{r['label']}" for r in per_part],
            fontsize=6.5,
        )
        ax.set_ylabel("Per-message recovery (%)")
        ax.set_ylim(0, 105)
        ax.set_title(f"S7 — Co-channel per-message recovery ({' / '.join(appraisers_in)})")
        ax.legend(fontsize=8)
        ax.grid(axis="y", linestyle=":", lw=0.5)
        plt.tight_layout()
        chart_path = run_dir / "S7_recovery.png"
        fig.savefig(chart_path, dpi=150)
        plt.close(fig)

    return {
        "overall": overall, "by_type": by_type, "per_part": per_part,
        "capture": capture, "between_app": between_app,
        "chart": chart_path.name if chart_path else None,
        "appraisers_in": appraisers_in,
    }


def _compounding_report_lines(results: dict) -> list[str]:
    appraisers_in = results.get("appraisers_in", list(APPRAISERS))
    col_heads = " | ".join(appraisers_in)
    col_seps  = "|".join("---" for _ in appraisers_in)

    lines: list[str] = ["## S7 — Compounding / co-channel overlap", ""]
    lines += ["_Per-message recovery (informational — no PASS/FAIL gate)._", ""]

    lines += ["### Recovery by overlap family", ""]
    lines += [f"| Overlap family | {col_heads} |", f"|---| {col_seps} |"]
    for ot, d in results["by_type"].items():
        vals = " | ".join(
            f"{_fmt_num(d.get(a, float('nan')))}%" for a in appraisers_in
        )
        lines.append(f"| {ot} | {vals} |")
    ov      = results["overall"]
    ov_vals = " | ".join(
        f"**{_fmt_num(ov.get(a, float('nan')))}%**" for a in appraisers_in
    )
    lines.append(f"| **all** | {ov_vals} |")
    lines += [""]

    cap = results.get("capture") or {}
    if cap:
        lines += ["### Capture effect", ""]
        lines += [f"| Signal | {col_heads} |", f"|---| {col_seps} |"]
        for role in ("strong", "weak"):
            vals = " | ".join(
                f"{_fmt_num(cap.get(a, {}).get(role, float('nan')))}%"
                for a in appraisers_in
            )
            lines.append(f"| {role} | {vals} |")
        lines += [""]

    ba = results.get("between_app") or {}
    if isinstance(ba, dict):
        for pair_label, pct in ba.items():
            lines += [f"**Between-appraiser per-signal agreement ({pair_label}):** "
                      f"{_fmt_num(pct)}%", ""]
    elif isinstance(ba, float) and not math.isnan(ba):
        lines += [f"**Between-appraiser per-signal agreement:** {_fmt_num(ba)}%", ""]

    lines += ["### Per-part detail", ""]
    lines += [f"| Part | Family | Condition | {col_heads} |",
              f"|---|---|---| {col_seps} |"]
    for r in results["per_part"]:
        vals = " | ".join(
            f"{r.get(a, (0, 0))[0]}/{r.get(a, (0, 0))[1]}" for a in appraisers_in
        )
        lines.append(
            f"| P{r['part_index']} | {r['overlap_type']} | {r['label']} | {vals} |"
        )
    lines += [""]
    if results.get("chart"):
        lines += [f"![S7 recovery]({results['chart']})", ""]
    return lines


# ---------------------------------------------------------------------------
# Decode-rate scenarios (S1b, S3b) — generalised to N appraisers
# ---------------------------------------------------------------------------

def _analyse_decode_rate(
    df_matched: pd.DataFrame,
    scen_id: str,
    run_dir: Path,
    part_var: str = "true_dt_s",
    part_label: str = "True DT (s)",
) -> dict:
    df = df_matched[df_matched["false_positive"] == False].copy()
    df["matched"]     = df["matched"].astype(bool)
    df["part_index"]  = pd.to_numeric(df["part_index"],  errors="coerce")
    df[part_var]      = pd.to_numeric(df[part_var],       errors="coerce")

    parts = sorted(df["part_index"].dropna().unique())
    per_part: list[dict] = []
    for pi in parts:
        part_sub = df[df["part_index"] == pi]
        part_val = part_sub[part_var].dropna().iloc[0] if not part_sub.empty else float("nan")
        row: dict = {"part_index": int(pi), "part_val": part_val}
        for appr in APPRAISERS:
            sub       = part_sub[part_sub["appraiser"] == appr]
            n_total   = len(sub)
            n_matched = int(sub["matched"].sum())
            rate      = 100.0 * n_matched / n_total if n_total > 0 else float("nan")
            row[f"{appr}_decoded"] = n_matched
            row[f"{appr}_total"]   = n_total
            row[f"{appr}_rate"]    = rate
        per_part.append(row)

    overall: dict[str, float] = {}
    for appr in APPRAISERS:
        sub = df[df["appraiser"] == appr]
        overall[appr] = 100.0 * sub["matched"].mean() if len(sub) else float("nan")

    chart_path = None
    if per_part:
        fig, ax = plt.subplots(figsize=(10, 5))
        x_vals = [r["part_val"] for r in per_part]
        for appr in APPRAISERS:
            rates = [r[f"{appr}_rate"] for r in per_part]
            if any(not (isinstance(v, float) and math.isnan(v)) for v in rates):
                ax.plot(x_vals, rates, marker="o", label=appr)
        ax.set_xlabel(part_label)
        ax.set_ylabel("Decode rate (%)")
        ax.set_ylim(-5, 105)
        ax.set_title(f"{scen_id} — Decode rate vs {part_label}")
        ax.legend(fontsize=9)
        cfg = DECODE_RATE_CONFIG.get(scen_id, {})
        if cfg.get("chart_ref_line") is not None:
            ax.axvline(cfg["chart_ref_line"], color="grey", linestyle=":", lw=0.8)
        ax.grid(axis="y", linestyle=":", lw=0.5)
        plt.tight_layout()
        chart_path = run_dir / f"{scen_id}_decode_rate.png"
        fig.savefig(chart_path, dpi=150)
        plt.close(fig)

    return {
        "scenario_id": scen_id, "part_var": part_var,
        "part_label": part_label, "per_part": per_part,
        "overall": overall, "chart": chart_path.name if chart_path else None,
    }


def _decode_rate_report_lines(results: dict) -> list[str]:
    scen_id    = results["scenario_id"]
    part_label = results.get("part_label", "Part value")
    cfg        = DECODE_RATE_CONFIG.get(scen_id, {})
    section_title = cfg.get("section_title", f"{scen_id} decode-rate study")
    section_intro = cfg.get("section_intro",
                            "Decode rate (informational — no AIAG threshold).")

    # Only include appraisers that actually have data in any part
    per_part = results.get("per_part", [])
    appraisers_in = [
        a for a in APPRAISERS
        if any(r.get(f"{a}_total", 0) > 0 for r in per_part)
    ] or list(APPRAISERS)

    col_headers = " | ".join(f"{a} decoded | {a} rate" for a in appraisers_in)
    col_seps    = " | ".join("|---|---" for _ in appraisers_in)

    lines: list[str] = [
        f"## {scen_id} — {section_title}", "",
        f"_{section_intro}_", "",
        "### Per-part decode rate", "",
        f"| Part | {part_label} | {col_headers} |",
        f"|---|---| {col_seps} |",
    ]
    for r in per_part:
        cols = " | ".join(
            f"{r.get(f'{a}_decoded', '—')}/{r.get(f'{a}_total', '—')} | "
            f"{_fmt_num(r.get(f'{a}_rate', float('nan')))}%"
            for a in appraisers_in
        )
        lines.append(f"| P{r['part_index']} | {_fmt_num(r['part_val'])} | {cols} |")

    ov = results["overall"]
    overall_parts = "  ".join(
        f"{a}: {_fmt_num(ov.get(a, float('nan')))}%"
        for a in appraisers_in
    )
    lines += ["", f"**Overall decode rate — {overall_parts}**", ""]
    if results.get("chart"):
        lines += [f"![{scen_id} decode rate]({results['chart']})", ""]
    return lines


# ---------------------------------------------------------------------------
# Verdict collection (extended for all pairs)
# ---------------------------------------------------------------------------

def _collect_verdicts(
    continuous_results: dict,
    kappa_results: dict,
    fp_results: dict,
    bias_results: dict,
    platform_bias: dict,
    mcnemar: dict,
    fisher_fp: dict,
) -> tuple[list[tuple], str, list[str]]:
    """Return (verdict_rows, overall_verdict, fail_messages).

    *platform_bias* : ``{scen_id: {(A, B): bias_dict}}``
    *mcnemar*       : ``{(A, B): mcnemar_dict}``
    *fisher_fp*     : ``{(A, B): fisher_dict}``
    """
    verdict_rows: list[tuple] = []
    fails:     list[str] = []
    marginals: list[str] = []

    # ── Continuous GR&R ──────────────────────────────────────────────────────
    for scen_id, res in continuous_results.items():
        if res is None:
            continue
        pct_grr = res["metrics"]["pct_contribution_grr"]
        ndc     = res["metrics"]["ndc"]
        v_grr   = _verdict_grr(pct_grr)
        v_ndc   = _verdict_ndc(ndc)
        verdict_rows.append(("%GR&R",  scen_id, f"{pct_grr:.1f}%", v_grr))
        verdict_rows.append(("ndc",    scen_id, str(ndc),           v_ndc))
        if v_grr == "FAIL":
            fails.append(f"%GR&R ({scen_id}) = {pct_grr:.1f}% (threshold < {THRESH_GRR_PASS}%)")
        elif v_grr == "MARGINAL":
            marginals.append(f"%GR&R ({scen_id}) = {pct_grr:.1f}%")

    # ── Platform bias gates — all pairs (STUDY-SPEC-XPLAT §8.1) ─────────────
    scen_bias_config = {
        "S1": ("SNR bias", "dB",
               THRESH_PLATFORM_SNR_PASS, THRESH_PLATFORM_SNR_MARGINAL),
        "S2": ("Freq bias", "Hz",
               THRESH_PLATFORM_FREQ_PASS, THRESH_PLATFORM_FREQ_MARGINAL),
        "S3": ("DT bias",  "s",
               THRESH_PLATFORM_DT_PASS,  THRESH_PLATFORM_DT_MARGINAL),
    }
    for scen_id, (label_base, unit, pass_t, marg_t) in scen_bias_config.items():
        if scen_id not in platform_bias:
            continue
        for (a, b), pb in platform_bias[scen_id].items():
            b_val = pb.get("mean_bias", float("nan"))
            if math.isnan(b_val):
                continue
            label = f"{label_base} |{b}−{a}|"
            v = _verdict_platform_bias(b_val, pass_t, marg_t)
            verdict_rows.append((label, scen_id, f"{b_val:+.3f} {unit}", v))
            if v == "FAIL":
                fails.append(
                    f"{label} ({scen_id}) = {b_val:+.3f} {unit} (gate: <= {marg_t} {unit})"
                )
            elif v == "MARGINAL":
                marginals.append(f"{label} ({scen_id}) = {b_val:+.3f} {unit}")

    # ── Kappa ────────────────────────────────────────────────────────────────
    for label, info in kappa_results.items():
        k = info.get("kappa", float("nan"))
        if math.isnan(k):
            continue
        if "_vs_truth" in label:
            v = _verdict_kappa(k)
            verdict_rows.append((f"Kappa {label}", "S4+S5", f"{k:.3f}", v))
            if v == "FAIL":
                fails.append(f"Kappa ({label}) = {k:.3f}")
        else:
            # Between-appraiser kappa
            v = _verdict_kappa_xplat(k)
            verdict_rows.append((f"Between-appraiser kappa {label}", "S4+S5", f"{k:.3f}", v))
            if v == "FAIL":
                fails.append(
                    f"Between-appraiser kappa ({label}) = {k:.3f} "
                    f"(gate >= {THRESH_KAPPA_XPLAT_PASS})"
                )
            elif v == "MARGINAL":
                marginals.append(f"Between-appraiser kappa ({label}) = {k:.3f}")

    # ── FP event count ───────────────────────────────────────────────────────
    for appr, info in fp_results.items():
        n_events = info.get("n_fp_events", float("nan"))
        if isinstance(n_events, float) and math.isnan(n_events):
            continue
        event_rate = info["event_rate"]
        rob_95     = info["rob_95"]
        rob_str    = f"; 95% UB <= {rob_95:.2f}%" if rob_95 is not None else ""
        v          = _verdict_fp(info)
        value_str  = (
            f"{int(n_events)}/{info['n_slots']} slots "
            f"(event {event_rate:.1f}%{rob_str})"
        )
        verdict_rows.append(("FP event count", f"S5/{appr}", value_str, v))
        if v == "FAIL":
            fails.append(f"FP event count ({appr}): {int(n_events)} events (gate = 0)")

    # ── SNR bias per appraiser vs truth ──────────────────────────────────────
    for appr, info in bias_results.items():
        b = info.get("mean_bias", float("nan"))
        if math.isnan(b):
            continue
        v = _verdict_bias(b)
        verdict_rows.append(("SNR bias vs truth", f"S1/{appr}", f"{b:+.2f} dB", v))
        if v == "FAIL":
            fails.append(f"SNR bias ({appr}) = {b:+.2f} dB (gate <= {THRESH_BIAS_PASS} dB)")

    # ── McNemar — all pairs ──────────────────────────────────────────────────
    for (a, b), mc in mcnemar.items():
        p_mc = mc.get("p_value", float("nan"))
        if math.isnan(p_mc):
            continue
        v = mc.get("verdict", "—")
        verdict_rows.append((f"McNemar chi2 p-value ({a} vs {b})", "all",
                             f"p={p_mc:.4f}", v))
        if v == "FAIL":
            fails.append(
                f"McNemar test ({a} vs {b}) rejected at p={p_mc:.4f} "
                f"(alpha={THRESH_MCNEMAR_P})"
            )

    # ── Fisher FP parity — all pairs ─────────────────────────────────────────
    for (a, b), fish in fisher_fp.items():
        p_fisher = fish.get("p_value", float("nan"))
        if math.isnan(p_fisher):
            continue
        v = fish.get("verdict", "—")
        verdict_rows.append((f"FP parity Fisher p ({a} vs {b})", "S5",
                             f"p={p_fisher:.4f}", v))
        if v == "FAIL":
            fails.append(
                f"FP parity Fisher ({a} vs {b}) rejected at p={p_fisher:.4f}"
            )

    overall = "FAIL" if fails else ("MARGINAL" if marginals else "PASS")
    return verdict_rows, overall, fails


# ---------------------------------------------------------------------------
# Report writer (NFR-023 five-section structure)
# ---------------------------------------------------------------------------

def _write_report(
    run_dir: Path,
    git_sha: str,
    continuous_results: dict,
    kappa_results: dict,
    fp_results: dict,
    bias_results: dict,
    platform_bias: dict,
    mcnemar: dict,
    fisher_fp: dict,
    verdict_rows: list,
    overall: str,
    fails: list[str],
    attr_results: dict | None = None,
    s7_results: dict | None = None,
    decode_rate_results: list[dict] | None = None,
) -> Path:
    lines: list[str] = []
    run_date_parts = run_dir.name.split("-")[0:3]
    run_date_str   = "-".join(run_date_parts) if len(run_date_parts) >= 3 else run_dir.name

    # ── Section 1 — Study hypothesis (QA-authored placeholder) ──────────────
    lines += [
        "# OpenWSFZ Cross-Platform R&R Study Report",
        "",
        "## Section 1 — Study Hypothesis",
        "",
        "> **[QA-authored — required by HK-001]**",
        ">",
        "> _Insert: which shim version is under test; whether this is a parity confirmation",
        "> or regression investigation; which hypotheses (H0_DEC through H0_COMP) are live;",
        "> what outcome would constitute a significant finding._",
        "",
    ]

    # ── Section 2 — Data summary (generated) ────────────────────────────────
    _all_scenarios = (
        set(continuous_results.keys())
        | ({"S5"} if fp_results else set())
        | ({"S4"} if attr_results else set())
    )
    if decode_rate_results:
        _all_scenarios |= {r["scenario_id"] for r in decode_rate_results}
    if s7_results:
        _all_scenarios.add("S7")

    # Which appraisers are actually present in this run?
    appraisers_present = list(APPRAISERS)   # default; refined below if FP data is available
    if fp_results:
        appraisers_present = [a for a in APPRAISERS if a in fp_results
                              and fp_results[a].get("n_slots", 0) > 0]
    if not appraisers_present:
        appraisers_present = list(APPRAISERS)

    lines += [
        "## Section 2 — Data Summary",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Run date | {run_date_str} |",
        f"| OpenWSFZ git SHA | `{git_sha}` |",
        f"| Shim version (both platforms) | *(verify via GET /api/v1/status)* |",
        f"| Windows platform | win-x64, WASAPI, `libft8.dll` shim 20260030 |",
        f"| Linux platform | WSL2 linux-x64, ALSA-PulseAudio, `libft8.so` shim 20260030 |",
        f"| WSJT-X | {'included' if 'WSJT-X' in appraisers_present else 'not included (wsjt-all.txt absent)'} |",
        f"| Scenarios run | {', '.join(sorted(_all_scenarios))} |",
        "",
    ]

    # ── Section 3 — Results (generated) ─────────────────────────────────────
    lines += ["## Section 3 — Results", ""]

    # Per-scenario bias config for report tables
    _scen_bias_cfg = {
        "S1": ("SNR bias", "dB",
               THRESH_PLATFORM_SNR_PASS, THRESH_PLATFORM_SNR_MARGINAL),
        "S2": ("Freq bias", "Hz",
               THRESH_PLATFORM_FREQ_PASS, THRESH_PLATFORM_FREQ_MARGINAL),
        "S3": ("DT bias", "s",
               THRESH_PLATFORM_DT_PASS, THRESH_PLATFORM_DT_MARGINAL),
    }

    for scen_id, res in sorted(continuous_results.items()):
        if res is None:
            lines += [f"### {scen_id}", "", "_Insufficient data — skipped._", ""]
            continue
        anova   = res["anova"]
        metrics = res["metrics"]
        response = res["response"]

        lines += [
            f"### {scen_id} — {response}",
            "",
            "#### Variance Components",
            "",
            "| Component | sigma^2 | %Contribution |",
            "|---|---|---|",
            f"| Repeatability | {_fmt_num(anova['var_repeatability'])} | {_fmt_num(metrics['pct_contribution_repeat'])}% |",
            f"| Reproducibility (platform) | {_fmt_num(anova['var_reproducibility'])} | {_fmt_num(metrics['pct_contribution_reprod'])}% |",
            f"| Part-to-Part | {_fmt_num(anova['var_part'])} | {_fmt_num(metrics['pct_contribution_part'])}% |",
            f"| Total GR&R | {_fmt_num(anova['var_grr'])} | {_fmt_num(metrics['pct_contribution_grr'])}% |",
            f"| Total | {_fmt_num(anova['var_total'])} | 100.00% |",
            "",
            "#### Study Metrics",
            "",
            "| Metric | Value | Verdict |",
            "|---|---|---|",
            f"| %Tolerance (GR&R) | {_fmt_num(metrics['pct_tolerance'])}% | {_verdict_grr(metrics['pct_contribution_grr'])} |",
            f"| %Study Var (GR&R) | {_fmt_num(metrics['pct_study_var_grr'])}% | — |",
            f"| ndc | {metrics['ndc']} | {_verdict_ndc(metrics['ndc'])} |",
            "",
        ]
        png_name = f"{scen_id}_grr_panel.png"
        lines += [f"![{scen_id} GR&R panel]({png_name})", ""]

        if scen_id == "S1" and bias_results:
            lines += ["#### Bias & Linearity (individual appraiser vs truth)", ""]
            lines += ["| Appraiser | Mean Bias (dB) | Slope | R^2 | Verdict |",
                      "|---|---|---|---|---|"]
            for appr, bi in bias_results.items():
                v = _verdict_bias(bi["mean_bias"])
                lines.append(
                    f"| {appr} | {bi['mean_bias']:+.2f} | {bi['slope']:.3f} | "
                    f"{bi['r2']:.3f} | {v} |"
                )
            lines += ["", "![S1 Bias & Linearity](S1_bias_linearity.png)", ""]

        # Platform bias — all pairs for this scenario
        if scen_id in platform_bias and scen_id in _scen_bias_cfg:
            blabel_base, bunit, bpass, bmarg = _scen_bias_cfg[scen_id]
            pairs_data = [
                ((a, b), pb)
                for (a, b), pb in platform_bias[scen_id].items()
                if not math.isnan(pb.get("mean_bias", float("nan")))
            ]
            if pairs_data:
                lines += [
                    f"#### Platform Bias — all pairs (gate <= {bmarg} {bunit})", "",
                    "| Pair (B − A) | Mean bias | n pairs | t-test p | Verdict |",
                    "|---|---|---|---|---|",
                ]
                for (a, b), pb in pairs_data:
                    b_val   = pb.get("mean_bias", float("nan"))
                    p_val   = pb.get("p_value",   float("nan"))
                    n_pairs = pb.get("n_pairs",   0)
                    bv      = _verdict_platform_bias(b_val, bpass, bmarg)
                    lines.append(
                        f"| {b} − {a} | {_fmt_num(b_val, '+.3f')} {bunit} "
                        f"| {n_pairs} | {_fmt_num(p_val, '.4f')} | {bv} |"
                    )
                lines += [""]

        if scen_id == "S1":
            lines += ["![S1 Platform Bias](S1_platform_bias.png)", ""]

        if scen_id == "S3":
            lines += [
                "#### DT Jitter Time-Series", "",
                "![S3 DT Jitter](S3_dt_jitter.png)", "",
            ]

    # Decode-rate companion studies
    for dr in (decode_rate_results or []):
        lines += _decode_rate_report_lines(dr)

    # Attribute agreement
    if attr_results:
        lines += _attribute_report_lines(attr_results)

    # FP rate + cross-platform attribute parity
    if fp_results:
        lines += ["### False-positive rate (S5)", ""]
        lines += ["| Appraiser | FP events / slots | Event rate | 95% UB | Verdict |",
                  "|---|---|---|---|---|"]
        for appr, info in fp_results.items():
            n_events = info.get("n_fp_events", float("nan"))
            if isinstance(n_events, float) and math.isnan(n_events):
                lines.append(f"| {appr} | — | — | — | — |")
                continue
            n_slots    = info["n_slots"]
            event_rate = info["event_rate"]
            rob_95     = info["rob_95"]
            rob_str    = f"<= {rob_95:.2f}%" if rob_95 is not None else "—"
            v          = _verdict_fp(info)
            lines.append(
                f"| {appr} | {int(n_events)} / {n_slots} "
                f"| {_fmt_num(event_rate)}% | {rob_str} | {v} |"
            )
        lines += [""]

        # McNemar and Fisher — all pairs
        lines += ["### Cross-platform attribute parity", ""]
        lines += [
            "| Test | Pair | Statistic | p-value | Verdict |",
            "|---|---|---|---|---|",
        ]
        for (a, b), mc in mcnemar.items():
            mc_chi2 = mc.get("chi2",    float("nan"))
            mc_p    = mc.get("p_value", float("nan"))
            mc_n_ab = mc.get("n_ab", 0)
            mc_n_ba = mc.get("n_ba", 0)
            mc_v    = mc.get("verdict", "—")
            lines.append(
                f"| McNemar ({mc_n_ab}/{mc_n_ba}) | {a} vs {b} "
                f"| chi2 = {_fmt_num(mc_chi2, '.3f')} | {_fmt_num(mc_p, '.4f')} | {mc_v} |"
            )
        for (a, b), fish in fisher_fp.items():
            fp_p = fish.get("p_value", float("nan"))
            fp_v = fish.get("verdict", "—")
            lines.append(
                f"| Fisher FP parity | S5 {a} vs {b} | — | {_fmt_num(fp_p, '.4f')} | {fp_v} |"
            )
        lines += [""]

    # S7
    if s7_results:
        lines += _compounding_report_lines(s7_results)

    # ── Section 4 — Summary verdict table (generated) ────────────────────────
    lines += [
        "## Section 4 — Summary Verdict",
        "",
        "| Metric | Scope | Value | Verdict |",
        "|---|---|---|---|",
    ]
    for row in verdict_rows:
        lines.append(f"| {row[0]} | {row[1]} | {row[2]} | {row[3]} |")
    lines += ["", f"**Overall verdict: {overall}**", ""]

    if fails:
        lines += ["### Defect Notices", ""]
        for f in fails:
            lines.append(f"- FAIL — {f}")
        lines += [""]

    # ── Section 5 — Recommendations (QA-authored placeholder) ───────────────
    lines += [
        "## Section 5 — Recommendations",
        "",
        "> **[QA-authored — required by HK-001]**",
        ">",
        "> _For each FAIL or MARGINAL metric: state the hypothesis rejected, the most",
        "> probable physical cause (audio latency, floating-point divergence, sample-rate",
        "> mismatch, decoder algorithm), and the recommended next diagnostic step. If all",
        "> metrics PASS, write: 'No further investigation required.'_",
        "",
    ]

    report_path = run_dir / "report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


# ---------------------------------------------------------------------------
# Trend CSV (cross-platform variant — extended for WSJT-X columns)
# ---------------------------------------------------------------------------

_TREND_COLUMNS_XPLAT = [
    "run_date", "git_sha",
    "pct_grr_snr", "ndc_snr",
    "platform_snr_bias_db",      # bias: Linux − Windows (backward compat)
    "win_wsjt_snr_bias_db",      # bias: WSJT-X − Windows
    "linux_wsjt_snr_bias_db",    # bias: WSJT-X − Linux
    "between_platform_kappa",
    "fp_events_windows", "fp_events_linux", "fp_events_wsjt",
    "mcnemar_p",                 # Windows vs Linux McNemar p-value
    "overall",
]


def _append_trend(
    qa_rr_root: Path,
    run_dir: Path,
    git_sha: str,
    continuous_results: dict,
    kappa_results: dict,
    fp_results: dict,
    platform_bias: dict,
    mcnemar: dict,
    overall: str,
) -> None:
    import csv as _csv
    trend_path = qa_rr_root / "trend_xplat.csv"
    write_header = not trend_path.exists()

    run_date_parts = run_dir.name.split("-")[0:3]
    run_date_str   = "-".join(run_date_parts) if len(run_date_parts) >= 3 else run_dir.name

    def _safe(v: Any) -> str:
        if v is None or (isinstance(v, float) and math.isnan(v)):
            return ""
        return str(round(v, 4) if isinstance(v, float) else v)

    pct_grr_snr = ndc_snr = ""
    if "S1" in continuous_results and continuous_results["S1"] is not None:
        pct_grr_snr = _safe(continuous_results["S1"]["metrics"]["pct_contribution_grr"])
        ndc_snr     = _safe(continuous_results["S1"]["metrics"]["ndc"])

    # S1 pairwise biases
    s1_bias = platform_bias.get("S1", {})
    platform_snr_bias_db    = _safe(s1_bias.get(("Windows", "Linux"),  {}).get("mean_bias", float("nan")))
    win_wsjt_snr_bias_db    = _safe(s1_bias.get(("Windows", "WSJT-X"), {}).get("mean_bias", float("nan")))
    linux_wsjt_snr_bias_db  = _safe(s1_bias.get(("Linux",   "WSJT-X"), {}).get("mean_bias", float("nan")))

    # Between-appraiser kappa (prefer Windows vs Linux for backward compat)
    bk_label = "Windows_vs_Linux"
    bk = kappa_results.get(bk_label, kappa_results.get("between_platforms", {}))
    between_kappa = _safe(bk.get("kappa", float("nan")))

    win_fp   = _safe(fp_results.get("Windows", {}).get("n_fp_events", float("nan")))
    lin_fp   = _safe(fp_results.get("Linux",   {}).get("n_fp_events", float("nan")))
    wsjt_fp  = _safe(fp_results.get("WSJT-X",  {}).get("n_fp_events", float("nan")))

    # McNemar p for Windows vs Linux pair (backward compat)
    mc_p = _safe(mcnemar.get(("Windows", "Linux"), {}).get("p_value", float("nan")))

    row = {
        "run_date":             run_date_str,
        "git_sha":              git_sha,
        "pct_grr_snr":          pct_grr_snr,
        "ndc_snr":              ndc_snr,
        "platform_snr_bias_db": platform_snr_bias_db,
        "win_wsjt_snr_bias_db": win_wsjt_snr_bias_db,
        "linux_wsjt_snr_bias_db": linux_wsjt_snr_bias_db,
        "between_platform_kappa": between_kappa,
        "fp_events_windows":    win_fp,
        "fp_events_linux":      lin_fp,
        "fp_events_wsjt":       wsjt_fp,
        "mcnemar_p":            mc_p,
        "overall":              overall,
    }

    with open(trend_path, "a", newline="", encoding="utf-8") as fh:
        writer = _csv.DictWriter(fh, fieldnames=_TREND_COLUMNS_XPLAT)
        if write_header:
            writer.writeheader()
        writer.writerow(row)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Cross-platform R&R analyser (Windows / Linux / WSJT-X)"
    )
    parser.add_argument("--run-dir", required=True,
                        help="Run directory containing *_matched.csv files")
    parser.add_argument("--scenario",
                        help="Comma-separated scenario IDs to analyse (default: all found)")
    args = parser.parse_args()

    run_dir = Path(args.run_dir)
    if not run_dir.exists():
        sys.exit(f"ERROR: run directory does not exist: {run_dir}")

    scenario_filter = [s.strip() for s in args.scenario.split(",")] if args.scenario else None
    scenarios_dir   = _QA_ROOT / "scenarios"

    matched = _load_matched_csvs(run_dir, scenario_filter, scenarios_dir)
    if not matched:
        sys.exit(f"ERROR: no *_matched.csv files found in {run_dir}")

    print(f"Analysing: {', '.join(sorted(matched.keys()))}")

    # Check which appraisers are present
    all_appraisers_in_data: set[str] = set()
    for df in matched.values():
        all_appraisers_in_data.update(df["appraiser"].unique())
    appraisers_active = tuple(a for a in APPRAISERS if a in all_appraisers_in_data)
    if "WSJT-X" not in appraisers_active:
        print("  Note: WSJT-X not present in matched data — running 2-appraiser analysis")
    print(f"  Active appraisers: {', '.join(appraisers_active)}")

    git_sha       = _git_sha()
    scenario_meta = _load_scenario_meta(scenarios_dir)

    continuous_results: dict = {}
    kappa_results:      dict = {}
    fp_results:         dict = {}
    bias_results:       dict = {}
    platform_bias:      dict = {}

    # ── Continuous GR&R (S1, S2, S3) ────────────────────────────────────────
    for scen_id, df in matched.items():
        if scen_id not in CONTINUOUS_SCENARIOS:
            continue
        response = RESPONSE_VAR[scen_id]
        tol_half = TOLERANCE_HALF[scen_id]

        # NOTE: No DT correction in xplat study — all platforms use UTC convention.

        anova = _two_way_anova(df, response, scen_id)
        if anova is None:
            continuous_results[scen_id] = None
            continue
        metrics = _derived_metrics(anova, tol_half)
        continuous_results[scen_id] = {
            "anova": anova, "metrics": metrics,
            "response": response, "tol_half": tol_half,
        }
        print(f"  {scen_id}: %GR&R={metrics['pct_contribution_grr']:.1f}%  ndc={metrics['ndc']}")
        png = _plot_grr_panel(df, response, anova, metrics, scen_id, run_dir)
        print(f"    -> {png.name}")

        # Platform bias — all pairs
        pb_all = _platform_bias_metrics_all(df, response, appraisers_active)
        platform_bias[scen_id] = pb_all
        for (a, b), pb in pb_all.items():
            if not math.isnan(pb.get("mean_bias", float("nan"))):
                unit = response.split("_")[1] if "_" in response else ""
                print(
                    f"  {scen_id} bias ({b}−{a}): "
                    f"{_fmt_num(pb['mean_bias'], '+.3f')} {unit}  "
                    f"p={_fmt_num(pb['p_value'], '.4f')}  n={pb['n_pairs']}"
                )

    # ── S1 Bias & Linearity ──────────────────────────────────────────────────
    if "S1" in matched and continuous_results.get("S1") is not None:
        bias_results = _bias_linearity(matched["S1"], run_dir)
        for appr, info in bias_results.items():
            print(f"  S1 bias ({appr}): {info['mean_bias']:+.2f} dB  slope={info['slope']:.3f}")
        chart = _platform_bias_chart(matched["S1"], run_dir, appraisers_active)
        if chart:
            print(f"    -> {chart.name}")

    # ── S3 DT jitter time-series ─────────────────────────────────────────────
    if "S3" in matched and continuous_results.get("S3") is not None:
        jitter_chart = _dt_jitter_timeseries(matched["S3"], run_dir, appraisers_active)
        if jitter_chart:
            print(f"  S3 DT jitter time-series -> {jitter_chart.name}")

    # ── Decode-rate companions (S1b, S3b) ────────────────────────────────────
    decode_rate_results: list[dict] = []
    for sid in sorted(DECODE_RATE_SCENARIOS):
        if sid not in matched:
            continue
        cfg = DECODE_RATE_CONFIG[sid]
        dr  = _analyse_decode_rate(
            matched[sid], sid, run_dir,
            part_var=cfg["part_var"],
            part_label=cfg["part_label"],
        )
        decode_rate_results.append(dr)
        for appr in appraisers_active:
            rate = dr["overall"].get(appr, float("nan"))
            print(f"  {sid} decode rate ({appr}): {_fmt_num(rate)}%  (informational)")

    # ── Attribute (S4 + S5) ──────────────────────────────────────────────────
    attr_results: dict | None = None
    if "S4" in matched or "S5" in matched:
        attr_results  = _attribute_agreement(matched, run_dir)
        kappa_results = attr_results["kappa"]
        for label, info in kappa_results.items():
            print(f"  Kappa {label}: {_fmt_num(info.get('kappa', float('nan')), '.3f')}")

    # ── FP rate (S5) ─────────────────────────────────────────────────────────
    if "S5" in matched:
        fp_results = _fp_rate(matched["S5"])
        for appr, info in fp_results.items():
            n_events = info.get("n_fp_events", float("nan"))
            if isinstance(n_events, float) and math.isnan(n_events):
                continue
            print(
                f"  S5 FP ({appr}): {int(n_events)}/{info['n_slots']} events "
                f"(event rate {_fmt_num(info['event_rate'])}%)"
            )

    # ── McNemar's test — all pairs ───────────────────────────────────────────
    mcnemar = _mcnemar_test(matched, appraisers_active)
    for (a, b), mc in mcnemar.items():
        print(
            f"  McNemar ({a} vs {b}): n_ab={mc['n_ab']} n_ba={mc['n_ba']} "
            f"chi2={_fmt_num(mc['chi2'], '.3f')} p={_fmt_num(mc['p_value'], '.4f')} "
            f"-> {mc['verdict']}"
        )

    # ── Fisher FP parity — all pairs ─────────────────────────────────────────
    fisher_fp = (
        _fp_parity_fisher(fp_results, appraisers_active)
        if fp_results
        else {(a, b): {"p_value": float("nan"), "verdict": "—"}
              for a, b in itertools.combinations(appraisers_active, 2)}
    )
    for (a, b), fish in fisher_fp.items():
        p = fish.get("p_value", float("nan"))
        if not math.isnan(p):
            print(f"  Fisher FP parity ({a} vs {b}): p={_fmt_num(p, '.4f')} -> {fish['verdict']}")

    # ── S7 co-channel ────────────────────────────────────────────────────────
    s7_results: dict | None = None
    if "S7" in matched:
        s7_results = _analyse_compounding(matched["S7"], scenario_meta.get("S7"), run_dir)
        for appr in appraisers_active:
            rate = s7_results["overall"].get(appr, float("nan"))
            print(f"  S7 recovery ({appr}): {_fmt_num(rate)}%")

    # ── Verdicts ─────────────────────────────────────────────────────────────
    verdict_rows, overall, fails = _collect_verdicts(
        continuous_results, kappa_results, fp_results, bias_results,
        platform_bias, mcnemar, fisher_fp,
    )

    # ── Report ───────────────────────────────────────────────────────────────
    report_path = _write_report(
        run_dir, git_sha, continuous_results, kappa_results,
        fp_results, bias_results, platform_bias, mcnemar, fisher_fp,
        verdict_rows, overall, fails,
        attr_results=attr_results,
        s7_results=s7_results,
        decode_rate_results=decode_rate_results,
    )
    print(f"\nReport written: {report_path}")
    print(f"Overall verdict: {overall}")

    if fails:
        print("\n[!] DEFECT NOTICES:")
        for f in fails:
            print(f"  FAIL — {f}")

    _append_trend(
        _QA_ROOT, run_dir, git_sha,
        continuous_results, kappa_results, fp_results,
        platform_bias, mcnemar, overall,
    )
    print(f"Trend row appended: {_QA_ROOT / 'trend_xplat.csv'}")
    print(f"\nRemember (HK-001): complete Sections 1 and 5 in {report_path}")


if __name__ == "__main__":
    main()
