"""Cross-platform Gauge R&R analyser — Windows (WASAPI) vs Linux/WSL2 (ALSA-PulseAudio).

Usage:
    python harness/analyse_xplat.py --run-dir <dir> [--scenario S1,S2]

Reads *_matched.csv files generated by harness/matcher_xplat.py (appraiser
names "Windows" and "Linux"), computes ANOVA-method Gauge R&R variance
components, cross-platform bias, McNemar's test, FP parity, DT jitter, and
writes report.md + PNG charts.

Key differences from harness/analyse.py:
  - Appraisers: "Windows" / "Linux" (not WSJT-X / OpenWSFZ)
  - No WSJT-X DT convention correction (both platforms use UTC-boundary DT)
  - Added: platform SNR/DT/freq bias gate, DT jitter time-series, McNemar's
    test, Fisher's exact FP parity test
  - report.md uses NFR-023 five-section structure (Sections 1 & 5 QA-authored)
"""
from __future__ import annotations

import argparse
import math
import subprocess
import sys
from pathlib import Path
from typing import Any

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from scipy.stats import t as tdist, chi2 as chi2dist, fisher_exact

# Resolve qa/rr-study as package root
_QA_ROOT = Path(__file__).resolve().parent.parent
if str(_QA_ROOT) not in sys.path:
    sys.path.insert(0, str(_QA_ROOT))

# ---------------------------------------------------------------------------
# Import appraiser-agnostic functions from analyse.py
# ---------------------------------------------------------------------------
from harness.analyse import (
    _git_sha,
    _verdict_grr, _verdict_ndc, _verdict_kappa, _verdict_fp, _verdict_bias,
    _fmt_num,
    _load_scenario_meta, _load_matched_csvs,
    _two_way_anova, _derived_metrics,
    _plot_grr_panel,
    _cohen_kappa_ci,
    CONTINUOUS_SCENARIOS, ATTRIBUTE_SCENARIOS, DECODE_RATE_SCENARIOS,
    DECODE_RATE_CONFIG, RESPONSE_VAR, TOLERANCE_HALF, REQUIRED_COLUMNS,
    THRESH_GRR_PASS, THRESH_GRR_MARGINAL, NDC_FAIL, NDC_PASS,
    THRESH_KAPPA_PASS, THRESH_KAPPA_MARGINAL, THRESH_BIAS_PASS,
)

# ---------------------------------------------------------------------------
# Cross-platform appraiser labels and thresholds
# ---------------------------------------------------------------------------

APPRAISERS = ("Windows", "Linux")

# STUDY-SPEC-XPLAT §8.1 — platform bias gates (|Linux − Windows|)
THRESH_PLATFORM_SNR_PASS     = 1.0    # dB — PASS
THRESH_PLATFORM_SNR_MARGINAL = 2.0    # dB — MARGINAL; > 2 dB → FAIL
THRESH_PLATFORM_DT_PASS      = 0.1    # s
THRESH_PLATFORM_DT_MARGINAL  = 0.2    # s
THRESH_PLATFORM_FREQ_PASS    = 2.0    # Hz
THRESH_PLATFORM_FREQ_MARGINAL = 4.0   # Hz

# STUDY-SPEC-XPLAT §8.2 — attribute gates
THRESH_KAPPA_XPLAT_PASS      = 0.90
THRESH_KAPPA_XPLAT_MARGINAL  = 0.75   # between-platform kappa
THRESH_MCNEMAR_P             = 0.05   # McNemar α

# ---------------------------------------------------------------------------
# Verdict helpers (platform bias)
# ---------------------------------------------------------------------------

def _verdict_platform_bias(bias: float, pass_thr: float, marginal_thr: float) -> str:
    if abs(bias) <= pass_thr:
        return "PASS"
    if abs(bias) <= marginal_thr:
        return "MARGINAL"
    return "FAIL"


def _verdict_kappa_xplat(kappa: float) -> str:
    if kappa >= THRESH_KAPPA_XPLAT_PASS:
        return "PASS"
    if kappa >= THRESH_KAPPA_XPLAT_MARGINAL:
        return "MARGINAL"
    return "FAIL"


def _verdict_mcnemar(p: float) -> str:
    return "PASS" if p >= THRESH_MCNEMAR_P else "FAIL"


def _verdict_fisher(p: float) -> str:
    return "PASS" if p >= THRESH_MCNEMAR_P else "FAIL"


# ---------------------------------------------------------------------------
# Bias & linearity (local version: uses module-level APPRAISERS)
# ---------------------------------------------------------------------------

def _bias_linearity(df_matched: pd.DataFrame, run_dir: Path) -> dict:
    df = df_matched[df_matched["matched"] == True].copy()
    df["reported_snr_db"] = pd.to_numeric(df["reported_snr_db"], errors="coerce")
    df["true_snr_db"] = pd.to_numeric(df["true_snr_db"], errors="coerce")
    df = df.dropna(subset=["reported_snr_db", "true_snr_db"])
    df["bias"] = df["reported_snr_db"] - df["true_snr_db"]

    results: dict[str, dict] = {}

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.axhline(0, color="black", linestyle="--", lw=0.8)

    appraisers_in_data = [a for a in APPRAISERS if a in df["appraiser"].values]
    for appr in appraisers_in_data:
        sub = df[df["appraiser"] == appr]
        if sub.empty:
            continue
        x = sub["true_snr_db"].values
        y = sub["bias"].values
        mean_bias = float(np.mean(y))
        coeffs = np.polyfit(x, y, 1)
        slope, intercept = float(coeffs[0]), float(coeffs[1])
        y_pred = np.polyval(coeffs, x)
        ss_res = float(np.sum((y - y_pred) ** 2))
        ss_tot = float(np.sum((y - np.mean(y)) ** 2))
        r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else 0.0

        results[appr] = {"mean_bias": mean_bias, "slope": slope,
                         "intercept": intercept, "r2": r2}

        x_line = np.linspace(x.min(), x.max(), 50)
        ax.scatter(x, y, label=f"{appr} (bias)", alpha=0.6, s=20)
        ax.plot(x_line, np.polyval(coeffs, x_line),
                label=f"{appr} fit (slope={slope:.3f})")

    ax.set_xlabel("True SNR (dB)")
    ax.set_ylabel("Bias = Reported - True (dB)")
    ax.set_title("S1 Bias & Linearity")
    ax.legend(fontsize=8)
    plt.tight_layout()
    out_path = run_dir / "S1_bias_linearity.png"
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return results


# ---------------------------------------------------------------------------
# Platform bias metrics (SNR, DT, freq)  — cross-platform only
# ---------------------------------------------------------------------------

def _platform_bias_metrics(df_matched: pd.DataFrame, response: str) -> dict:
    """Compute Linux − Windows bias for a continuous response variable.

    Requires both appraisers to have decoded the same (part, trial) cell.
    Returns dict with mean_bias, t_stat, p_value, n_pairs, and verdict.
    """
    df = df_matched[df_matched["matched"] == True].copy()
    df[response] = pd.to_numeric(df[response], errors="coerce")
    df = df.dropna(subset=[response, "part_index", "trial_index", "appraiser"])

    # Pivot to wide: one row per (part, trial), columns Windows / Linux
    pivot = df.pivot_table(
        index=["part_index", "trial_index"],
        columns="appraiser",
        values=response,
        aggfunc="mean",
    )
    if "Windows" not in pivot.columns or "Linux" not in pivot.columns:
        return {"mean_bias": float("nan"), "t_stat": float("nan"),
                "p_value": float("nan"), "n_pairs": 0, "verdict": "—"}

    paired = pivot[["Windows", "Linux"]].dropna()
    n = len(paired)
    if n < 2:
        return {"mean_bias": float("nan"), "t_stat": float("nan"),
                "p_value": float("nan"), "n_pairs": n, "verdict": "—"}

    diffs = paired["Linux"] - paired["Windows"]
    mean_bias = float(diffs.mean())
    se = float(diffs.std(ddof=1) / np.sqrt(n))
    t_stat = mean_bias / se if se > 0 else float("inf")
    p_value = float(2 * (1 - tdist.cdf(abs(t_stat), df=n - 1)))

    return {
        "mean_bias": mean_bias,
        "t_stat": t_stat,
        "p_value": p_value,
        "n_pairs": n,
        "verdict": "—",  # caller applies gate
    }


def _platform_bias_chart(df_s1: pd.DataFrame, run_dir: Path) -> Path | None:
    """Scatter plot of (SNR_Linux - SNR_Windows) vs true SNR with 95% CI band."""
    df = df_s1[df_s1["matched"] == True].copy()
    df["reported_snr_db"] = pd.to_numeric(df["reported_snr_db"], errors="coerce")
    df["true_snr_db"] = pd.to_numeric(df["true_snr_db"], errors="coerce")
    df = df.dropna(subset=["reported_snr_db", "true_snr_db", "part_index", "trial_index"])

    pivot = df.pivot_table(
        index=["part_index", "trial_index"],
        columns="appraiser",
        values="reported_snr_db",
        aggfunc="mean",
    )
    if "Windows" not in pivot.columns or "Linux" not in pivot.columns:
        return None

    paired = pivot[["Windows", "Linux"]].dropna()
    if len(paired) < 2:
        return None

    # Merge true_snr_db
    true_snr = df.groupby(["part_index", "trial_index"])["true_snr_db"].mean()
    paired = paired.join(true_snr, how="inner")
    diffs = paired["Linux"] - paired["Windows"]
    x = paired["true_snr_db"].values
    y = diffs.values

    coeffs = np.polyfit(x, y, 1)
    x_line = np.linspace(x.min(), x.max(), 50)

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.axhline(0, color="black", linestyle="--", lw=0.8, label="Zero bias")
    ax.axhline(2, color="red", linestyle=":", lw=0.8, label="+2 dB gate")
    ax.axhline(-2, color="red", linestyle=":", lw=0.8, label="-2 dB gate")
    ax.scatter(x, y, alpha=0.7, s=25, label=f"Linux-Windows (n={len(y)})")
    ax.plot(x_line, np.polyval(coeffs, x_line), color="orange",
            label=f"Fit: slope={coeffs[0]:.3f}")
    ax.set_xlabel("True SNR (dB)")
    ax.set_ylabel("SNR_Linux - SNR_Windows (dB)")
    ax.set_title("S1 Platform SNR Bias (Linux - Windows)")
    ax.legend(fontsize=8)
    plt.tight_layout()
    out_path = run_dir / "S1_platform_bias.png"
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return out_path


def _dt_jitter_timeseries(df_s3: pd.DataFrame, run_dir: Path) -> Path | None:
    """Time-series of DT_Linux - DT_Windows across all S3 trials (in cycle order)."""
    df = df_s3[df_s3["matched"] == True].copy()
    df["reported_dt_s"] = pd.to_numeric(df["reported_dt_s"], errors="coerce")
    df = df.dropna(subset=["reported_dt_s", "part_index", "trial_index",
                            "appraiser", "cycle_utc"])

    pivot = df.pivot_table(
        index=["cycle_utc", "part_index", "trial_index"],
        columns="appraiser",
        values="reported_dt_s",
        aggfunc="mean",
    ).reset_index()

    if "Windows" not in pivot.columns or "Linux" not in pivot.columns:
        return None

    paired = pivot[["cycle_utc", "part_index", "trial_index",
                    "Windows", "Linux"]].dropna()
    if len(paired) < 2:
        return None

    paired = paired.sort_values("cycle_utc")
    diffs = (paired["Linux"] - paired["Windows"]).values
    x = np.arange(len(diffs))

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.axhline(0, color="black", linestyle="--", lw=0.8)
    ax.axhline(0.1, color="orange", linestyle=":", lw=0.8, label="±0.1 s PASS gate")
    ax.axhline(-0.1, color="orange", linestyle=":", lw=0.8)
    ax.axhline(0.2, color="red", linestyle=":", lw=0.8, label="±0.2 s MARGINAL gate")
    ax.axhline(-0.2, color="red", linestyle=":", lw=0.8)
    ax.plot(x, diffs, marker="o", ms=4, label="DT_Linux - DT_Windows")
    # Rolling mean (window 5)
    if len(diffs) >= 5:
        rm = pd.Series(diffs).rolling(5, center=True).mean()
        ax.plot(x, rm, color="navy", lw=1.5, label="Rolling mean (w=5)")
    ax.set_xlabel("Trial (cycle order)")
    ax.set_ylabel("DT_Linux - DT_Windows (s)")
    ax.set_title("S3 DT Jitter Time-Series (Linux - Windows)")
    ax.legend(fontsize=8)
    plt.tight_layout()
    out_path = run_dir / "S3_dt_jitter.png"
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return out_path


# ---------------------------------------------------------------------------
# McNemar's test
# ---------------------------------------------------------------------------

def _mcnemar_test(df_all: dict[str, pd.DataFrame]) -> dict:
    """McNemar's test on pooled binary decode decisions (all non-FP scenarios).

    Returns dict with n12 (Win+, Lin-), n21 (Win-, Lin+), chi2, p_value, verdict.
    """
    n12 = 0  # Windows decoded, Linux did not
    n21 = 0  # Linux decoded, Windows did not

    for scen_id, df in df_all.items():
        df_sub = df[df["false_positive"] == False].copy()
        if df_sub.empty:
            continue
        pivot = df_sub.pivot_table(
            index=["part_index", "trial_index", "message_text", "cycle_utc"],
            columns="appraiser",
            values="matched",
            aggfunc="any",
        )
        if "Windows" not in pivot.columns or "Linux" not in pivot.columns:
            continue
        paired = pivot[["Windows", "Linux"]].dropna()
        n12 += int(((paired["Windows"] == True) & (paired["Linux"] == False)).sum())
        n21 += int(((paired["Windows"] == False) & (paired["Linux"] == True)).sum())

    total = n12 + n21
    if total == 0:
        return {"n12": 0, "n21": 0, "chi2": float("nan"),
                "p_value": float("nan"), "verdict": "PASS"}

    # McNemar's with continuity correction
    chi2 = (abs(n12 - n21) - 1) ** 2 / total
    p_value = float(1 - chi2dist.cdf(chi2, df=1))
    return {
        "n12": n12, "n21": n21,
        "chi2": chi2, "p_value": p_value,
        "verdict": _verdict_mcnemar(p_value),
    }


# ---------------------------------------------------------------------------
# False-positive rate (local version using module-level APPRAISERS)
# ---------------------------------------------------------------------------

def _fp_rate(df_matched: pd.DataFrame) -> dict[str, dict]:
    """FP rate per appraiser for S5 (scoped to S5 injection window)."""
    _NAN: dict = {
        "decode_rate": float("nan"), "event_rate": float("nan"),
        "n_fp_events": float("nan"), "n_fp_decodes": float("nan"),
        "n_slots": 0, "rob_95": None,
    }
    results: dict[str, dict] = {}

    s5_truth_rows = df_matched[df_matched["false_positive"] == False]
    s5_cycles: set = set(s5_truth_rows["cycle_utc"].dropna().unique())

    for appr in APPRAISERS:
        sub = df_matched[df_matched["appraiser"] == appr]
        truth_sub = sub[sub["false_positive"] == False]
        fp_sub = sub[sub["false_positive"] == True]
        n_slots = int(len(truth_sub))
        fp_in_window = fp_sub[fp_sub["cycle_utc"].isin(s5_cycles)] if s5_cycles else fp_sub

        if n_slots == 0:
            results[appr] = _NAN.copy()
            continue

        n_fp_decodes = int(len(fp_in_window))
        n_fp_events = int(fp_in_window["cycle_utc"].nunique())
        decode_rate = 100.0 * n_fp_decodes / n_slots
        event_rate = 100.0 * n_fp_events / n_slots
        rob_95 = (300.0 / n_slots) if n_fp_events == 0 else None

        results[appr] = {
            "decode_rate": decode_rate, "event_rate": event_rate,
            "n_fp_events": n_fp_events, "n_fp_decodes": n_fp_decodes,
            "n_slots": n_slots, "rob_95": rob_95,
        }
    return results


def _fp_parity_fisher(fp_results: dict) -> dict:
    """Fisher's exact test on FP count: Linux vs Windows."""
    win = fp_results.get("Windows", {})
    lin = fp_results.get("Linux", {})
    win_events = win.get("n_fp_events", float("nan"))
    lin_events = lin.get("n_fp_events", float("nan"))
    win_slots = win.get("n_slots", 0)
    lin_slots = lin.get("n_slots", 0)

    if (isinstance(win_events, float) and math.isnan(win_events)) or win_slots == 0 or lin_slots == 0:
        return {"p_value": float("nan"), "verdict": "—"}

    # 2x2 table: rows=FP/noFP, cols=Windows/Linux
    table = [[int(win_events), int(lin_events)],
             [win_slots - int(win_events), lin_slots - int(lin_events)]]
    try:
        _, p = fisher_exact(table)
        return {"p_value": float(p), "verdict": _verdict_fisher(p)}
    except Exception:
        return {"p_value": float("nan"), "verdict": "—"}


# ---------------------------------------------------------------------------
# Attribute agreement (local version)
# ---------------------------------------------------------------------------

def _attribute_agreement(matched: dict[str, pd.DataFrame], run_dir: Path) -> dict:
    """Pooled attribute agreement: S4 positives + S5 negatives."""
    pos_df = matched.get("S4")
    neg_df = matched.get("S5")

    units: dict[str, dict[tuple, tuple]] = {a: {} for a in APPRAISERS}

    if pos_df is not None:
        d = pos_df[pos_df["false_positive"] == False]
        for _, r in d.iterrows():
            appr = r["appraiser"]
            if appr not in units:
                continue
            key = ("S4", r["part_index"], r["trial_index"], r["cycle_utc"], r["message_text"])
            group = ("S4", r["part_index"], r["message_text"])
            units[appr][key] = (True, bool(r["matched"]), group)

    if neg_df is not None:
        truth_rows = neg_df[neg_df["false_positive"] == False]
        s5_cycles = set(truth_rows["cycle_utc"].dropna().unique())
        for appr in APPRAISERS:
            sub = neg_df[neg_df["appraiser"] == appr]
            fp_cycles = set(sub[sub["false_positive"] == True]["cycle_utc"]) & s5_cycles
            for _, r in sub[sub["false_positive"] == False].iterrows():
                cyc = r["cycle_utc"]
                key = ("S5", r["part_index"], r["trial_index"], cyc, "")
                group = ("S5", r["part_index"], "")
                units[appr][key] = (False, cyc in fp_cycles, group)

    confusion: dict[str, dict] = {}
    for appr in APPRAISERS:
        tp = fp = fn = tn = 0
        for truth, call, _ in units[appr].values():
            if truth and call:
                tp += 1
            elif truth and not call:
                fn += 1
            elif (not truth) and call:
                fp += 1
            else:
                tn += 1
        confusion[appr] = {"TP": tp, "FN": fn, "FP": fp, "TN": tn,
                           "n_pos": tp + fn, "n_neg": fp + tn}

    kappa: dict[str, dict] = {}
    for appr in APPRAISERS:
        keys = sorted(units[appr].keys())
        truth = [units[appr][k][0] for k in keys]
        call = [units[appr][k][1] for k in keys]
        kappa[f"{appr}_vs_truth"] = _cohen_kappa_ci(truth, call)

    a0, a1 = APPRAISERS[0], APPRAISERS[1]
    common = sorted(set(units[a0].keys()) & set(units[a1].keys()))
    c0 = [units[a0][k][1] for k in common]
    c1 = [units[a1][k][1] for k in common]
    ba = _cohen_kappa_ci(c0, c1)
    kappa["between_platforms"] = {"kappa": ba["kappa"],
                                  "ci_lo": ba.get("ci_lo", float("nan")),
                                  "ci_hi": ba.get("ci_hi", float("nan"))}

    repeatability: dict[str, float] = {}
    for appr in APPRAISERS:
        groups: dict[tuple, list[bool]] = {}
        for truth, call, grp in units[appr].values():
            groups.setdefault(grp, []).append(call)
        if groups:
            consistent = sum(1 for v in groups.values() if len(set(v)) == 1)
            repeatability[appr] = 100.0 * consistent / len(groups)
        else:
            repeatability[appr] = float("nan")

    return {"kappa": kappa, "repeatability": repeatability, "confusion": confusion}


def _attribute_report_lines(attr: dict) -> list[str]:
    lines: list[str] = ["## Attribute Agreement Analysis (S4 positives + S5 negatives)", ""]
    lines += [
        "_Pooled attribute agreement: S4 injected messages (truth = present) "
        "and S5 signal-free slots (truth = absent)._",
        "",
    ]

    lines += ["### Confusion vs truth", ""]
    lines += [f"| Appraiser | TP | FN | FP | TN | Recovery | Specificity |",
              "|---|---|---|---|---|---|---|"]
    for appr in APPRAISERS:
        c = attr["confusion"].get(appr, {})
        tp, fn, fp, tn = c.get("TP", 0), c.get("FN", 0), c.get("FP", 0), c.get("TN", 0)
        rec = 100.0 * tp / (tp + fn) if (tp + fn) else float("nan")
        spec = 100.0 * tn / (tn + fp) if (tn + fp) else float("nan")
        lines.append(
            f"| {appr} | {tp} | {fn} | {fp} | {tn} | "
            f"{_fmt_num(rec)}% | {_fmt_num(spec)}% |"
        )
    lines += [""]

    lines += ["### Kappa", ""]
    lines += ["| Pair | kappa | 95% CI | Gate | Verdict |", "|---|---|---|---|---|"]
    for label, info in sorted(attr["kappa"].items()):
        k = info.get("kappa", float("nan"))
        ci_lo = info.get("ci_lo", float("nan"))
        ci_hi = info.get("ci_hi", float("nan"))
        if not (isinstance(ci_lo, float) and math.isnan(ci_lo)):
            ci = f"[{_fmt_num(ci_lo)}, {_fmt_num(ci_hi)}]"
        else:
            ci = "—"
        if label == "between_platforms":
            gate = f">= {THRESH_KAPPA_XPLAT_PASS}"
            v = _verdict_kappa_xplat(k) if not math.isnan(k) else "—"
        else:
            gate = f">= {THRESH_KAPPA_PASS}"
            v = _verdict_kappa(k) if not math.isnan(k) else "—"
        lines.append(f"| {label} | {_fmt_num(k, '.3f')} | {ci} | {gate} | {v} |")
    lines += [""]

    lines += ["### Within-platform repeatability (decision consistency across trials)", ""]
    lines += ["| Platform | Consistent groups |", "|---|---|"]
    for appr in APPRAISERS:
        lines.append(f"| {appr} | {_fmt_num(attr['repeatability'].get(appr, float('nan')))}% |")
    lines += [""]
    return lines


# ---------------------------------------------------------------------------
# S7 — Co-channel / compounding (local version)
# ---------------------------------------------------------------------------

def _analyse_compounding(df_matched: pd.DataFrame, scen_meta: dict | None,
                         run_dir: Path) -> dict:
    df = df_matched[df_matched["false_positive"] == False].copy()
    df["matched"] = df["matched"].astype(bool)
    df["part_index"] = pd.to_numeric(df["part_index"], errors="coerce")
    df["true_snr_db"] = pd.to_numeric(df["true_snr_db"], errors="coerce")

    part_meta: dict[int, dict] = {}
    for p in (scen_meta or {}).get("parts", []):
        part_meta[int(p["part_index"])] = {
            "overlap_type": p.get("overlap_type", "?"),
            "label": p.get("label", ""),
            "n_signals": len(p.get("signals", [])),
        }

    df["overlap_type"] = df["part_index"].map(
        lambda i: part_meta.get(int(i), {}).get("overlap_type", "?")
        if pd.notna(i) else "?"
    )

    overall: dict[str, float] = {}
    for appr in APPRAISERS:
        sub = df[df["appraiser"] == appr]
        overall[appr] = 100.0 * sub["matched"].mean() if len(sub) else float("nan")

    by_type: dict[str, dict[str, float]] = {}
    for ot in sorted(df["overlap_type"].unique()):
        by_type[ot] = {}
        for appr in APPRAISERS:
            sub = df[(df["overlap_type"] == ot) & (df["appraiser"] == appr)]
            by_type[ot][appr] = 100.0 * sub["matched"].mean() if len(sub) else float("nan")

    per_part: list[dict] = []
    for pi in sorted(df["part_index"].dropna().unique()):
        meta = part_meta.get(int(pi), {})
        row: dict = {
            "part_index": int(pi),
            "overlap_type": meta.get("overlap_type", "?"),
            "label": meta.get("label", ""),
        }
        for appr in APPRAISERS:
            sub = df[(df["part_index"] == pi) & (df["appraiser"] == appr)]
            row[appr] = (int(sub["matched"].sum()), int(len(sub)))
        per_part.append(row)

    capture: dict[str, dict[str, float]] = {}
    df_cap = df[df["overlap_type"] == "capture"].copy()
    if not df_cap.empty:
        part_max = df_cap.groupby("part_index")["true_snr_db"].transform("max")
        df_cap["role"] = np.where(np.isclose(df_cap["true_snr_db"], part_max), "strong", "weak")
        for appr in APPRAISERS:
            capture[appr] = {}
            for role in ("strong", "weak"):
                sub = df_cap[(df_cap["appraiser"] == appr) & (df_cap["role"] == role)]
                capture[appr][role] = 100.0 * sub["matched"].mean() if len(sub) else float("nan")

    keyed: dict[str, dict[tuple, bool]] = {}
    for appr in APPRAISERS:
        sub = df[df["appraiser"] == appr]
        d: dict[tuple, bool] = {}
        for _, r in sub.iterrows():
            key = (r["part_index"], r["trial_index"], r["message_text"], r["true_freq_hz"])
            d[key] = bool(r["matched"])
        keyed[appr] = d
    common = set(keyed.get(APPRAISERS[0], {})) & set(keyed.get(APPRAISERS[1], {}))
    if common:
        agree = sum(1 for k in common
                    if keyed[APPRAISERS[0]][k] == keyed[APPRAISERS[1]][k])
        between_app = 100.0 * agree / len(common)
    else:
        between_app = float("nan")

    chart_path = None
    if per_part:
        fig, ax = plt.subplots(figsize=(13, 5))
        x = np.arange(len(per_part))
        width = 0.38
        for i, appr in enumerate(APPRAISERS):
            vals = [
                (100.0 * r[appr][0] / r[appr][1]) if r[appr][1] else 0.0
                for r in per_part
            ]
            ax.bar(x + (i - 0.5) * width, vals, width, label=appr)
        ax.set_xticks(x)
        ax.set_xticklabels(
            [f"P{r['part_index']}\n{r['overlap_type']}\n{r['label']}" for r in per_part],
            fontsize=6.5,
        )
        ax.set_ylabel("Per-message recovery (%)")
        ax.set_ylim(0, 105)
        ax.set_title("S7 — Co-channel per-message recovery (Windows vs Linux)")
        ax.legend(fontsize=8)
        ax.grid(axis="y", linestyle=":", lw=0.5)
        plt.tight_layout()
        chart_path = run_dir / "S7_recovery.png"
        fig.savefig(chart_path, dpi=150)
        plt.close(fig)

    return {
        "overall": overall, "by_type": by_type, "per_part": per_part,
        "capture": capture, "between_app": between_app,
        "chart": chart_path.name if chart_path else None,
    }


def _compounding_report_lines(results: dict) -> list[str]:
    win, lin = APPRAISERS
    lines: list[str] = ["## S7 — Compounding / co-channel overlap", ""]
    lines += [
        "_Per-message recovery (informational — no PASS/FAIL gate)._", "",
    ]

    lines += ["### Recovery by overlap family", ""]
    lines += [f"| Overlap family | {win} | {lin} |", "|---|---|---|"]
    for ot, d in results["by_type"].items():
        lines.append(
            f"| {ot} | {_fmt_num(d.get(win, float('nan')))}% "
            f"| {_fmt_num(d.get(lin, float('nan')))}% |"
        )
    ov = results["overall"]
    lines.append(
        f"| **all** | **{_fmt_num(ov.get(win, float('nan')))}%** "
        f"| **{_fmt_num(ov.get(lin, float('nan')))}%** |"
    )
    lines += [""]

    cap = results.get("capture") or {}
    if cap:
        lines += ["### Capture effect", ""]
        lines += [f"| Signal | {win} | {lin} |", "|---|---|---|"]
        for role in ("strong", "weak"):
            lines.append(
                f"| {role} | "
                f"{_fmt_num(cap.get(win, {}).get(role, float('nan')))}% | "
                f"{_fmt_num(cap.get(lin, {}).get(role, float('nan')))}% |"
            )
        lines += [""]

    lines += [
        f"**Between-platform per-signal agreement:** "
        f"{_fmt_num(results.get('between_app', float('nan')))}%", "",
    ]

    lines += ["### Per-part detail", ""]
    lines += [f"| Part | Family | Condition | {win} | {lin} |", "|---|---|---|---|---|"]
    for r in results["per_part"]:
        w_rec, w_tot = r[win]
        l_rec, l_tot = r[lin]
        lines.append(
            f"| P{r['part_index']} | {r['overlap_type']} | {r['label']} "
            f"| {w_rec}/{w_tot} | {l_rec}/{l_tot} |"
        )
    lines += [""]
    if results.get("chart"):
        lines += [f"![S7 recovery]({results['chart']})", ""]
    return lines


# ---------------------------------------------------------------------------
# Decode-rate scenarios (S1b, S3b) — local version
# ---------------------------------------------------------------------------

def _analyse_decode_rate(df_matched: pd.DataFrame, scen_id: str,
                         run_dir: Path, part_var: str = "true_dt_s",
                         part_label: str = "True DT (s)") -> dict:
    df = df_matched[df_matched["false_positive"] == False].copy()
    df["matched"] = df["matched"].astype(bool)
    df["part_index"] = pd.to_numeric(df["part_index"], errors="coerce")
    df[part_var] = pd.to_numeric(df[part_var], errors="coerce")

    parts = sorted(df["part_index"].dropna().unique())
    per_part: list[dict] = []
    for pi in parts:
        part_sub = df[df["part_index"] == pi]
        part_val = part_sub[part_var].dropna().iloc[0] if not part_sub.empty else float("nan")
        row: dict = {"part_index": int(pi), "part_val": part_val}
        for appr in APPRAISERS:
            sub = part_sub[part_sub["appraiser"] == appr]
            n_total = len(sub)
            n_matched = int(sub["matched"].sum())
            rate = 100.0 * n_matched / n_total if n_total > 0 else float("nan")
            row[f"{appr}_decoded"] = n_matched
            row[f"{appr}_total"] = n_total
            row[f"{appr}_rate"] = rate
        per_part.append(row)

    overall: dict[str, float] = {}
    for appr in APPRAISERS:
        sub = df[df["appraiser"] == appr]
        overall[appr] = 100.0 * sub["matched"].mean() if len(sub) else float("nan")

    chart_path = None
    if per_part:
        fig, ax = plt.subplots(figsize=(10, 5))
        x_vals = [r["part_val"] for r in per_part]
        for appr in APPRAISERS:
            rates = [r[f"{appr}_rate"] for r in per_part]
            ax.plot(x_vals, rates, marker="o", label=appr)
        ax.set_xlabel(part_label)
        ax.set_ylabel("Decode rate (%)")
        ax.set_ylim(-5, 105)
        ax.set_title(f"{scen_id} — Decode rate vs {part_label}")
        ax.legend(fontsize=9)
        cfg = DECODE_RATE_CONFIG.get(scen_id, {})
        if cfg.get("chart_ref_line") is not None:
            ax.axvline(cfg["chart_ref_line"], color="grey", linestyle=":", lw=0.8)
        ax.grid(axis="y", linestyle=":", lw=0.5)
        plt.tight_layout()
        chart_path = run_dir / f"{scen_id}_decode_rate.png"
        fig.savefig(chart_path, dpi=150)
        plt.close(fig)

    return {
        "scenario_id": scen_id, "part_var": part_var,
        "part_label": part_label, "per_part": per_part,
        "overall": overall, "chart": chart_path.name if chart_path else None,
    }


def _decode_rate_report_lines(results: dict) -> list[str]:
    scen_id = results["scenario_id"]
    part_label = results.get("part_label", "Part value")
    cfg = DECODE_RATE_CONFIG.get(scen_id, {})
    win, lin = APPRAISERS
    section_title = cfg.get("section_title", f"{scen_id} decode-rate study")
    section_intro = cfg.get("section_intro",
                            "Decode rate (informational — no AIAG threshold).")
    lines: list[str] = [
        f"## {scen_id} — {section_title}", "",
        f"_{section_intro}_", "",
        "### Per-part decode rate", "",
        f"| Part | {part_label} | {win} decoded | {win} rate | {lin} decoded | {lin} rate |",
        "|---|---|---|---|---|---|",
    ]
    for r in results["per_part"]:
        w_dec = r.get(f"{win}_decoded", "—")
        w_tot = r.get(f"{win}_total", "—")
        w_rate = _fmt_num(r.get(f"{win}_rate", float("nan")))
        l_dec = r.get(f"{lin}_decoded", "—")
        l_tot = r.get(f"{lin}_total", "—")
        l_rate = _fmt_num(r.get(f"{lin}_rate", float("nan")))
        lines.append(
            f"| P{r['part_index']} | {_fmt_num(r['part_val'])} "
            f"| {w_dec}/{w_tot} | {w_rate}% "
            f"| {l_dec}/{l_tot} | {l_rate}% |"
        )
    ov = results["overall"]
    lines += [
        "",
        f"**Overall decode rate — {win}: {_fmt_num(ov.get(win, float('nan')))}%  "
        f"{lin}: {_fmt_num(ov.get(lin, float('nan')))}%**",
        "",
    ]
    if results.get("chart"):
        lines += [f"![{scen_id} decode rate]({results['chart']})", ""]
    return lines


# ---------------------------------------------------------------------------
# Verdict collection (extended for xplat gates)
# ---------------------------------------------------------------------------

def _collect_verdicts(
    continuous_results: dict,
    kappa_results: dict,
    fp_results: dict,
    bias_results: dict,
    platform_bias: dict,
    mcnemar: dict,
    fisher_fp: dict,
) -> tuple[list[tuple], str, list[str]]:
    verdict_rows: list[tuple] = []
    fails: list[str] = []
    marginals: list[str] = []

    # Continuous GR&R
    for scen_id, res in continuous_results.items():
        if res is None:
            continue
        pct_grr = res["metrics"]["pct_contribution_grr"]
        ndc = res["metrics"]["ndc"]
        v_grr = _verdict_grr(pct_grr)
        v_ndc = _verdict_ndc(ndc)
        verdict_rows.append(("%GR&R", scen_id, f"{pct_grr:.1f}%", v_grr))
        verdict_rows.append(("ndc", scen_id, str(ndc), v_ndc))
        if v_grr == "FAIL":
            fails.append(f"%GR&R ({scen_id}) = {pct_grr:.1f}% (threshold < {THRESH_GRR_PASS}%)")
        elif v_grr == "MARGINAL":
            marginals.append(f"%GR&R ({scen_id}) = {pct_grr:.1f}%")

    # Platform bias gates (STUDY-SPEC-XPLAT §8.1)
    bias_gates = {
        "S1": ("SNR bias |Linux-Windows|", "dB",
               THRESH_PLATFORM_SNR_PASS, THRESH_PLATFORM_SNR_MARGINAL),
        "S2": ("Freq bias |Linux-Windows|", "Hz",
               THRESH_PLATFORM_FREQ_PASS, THRESH_PLATFORM_FREQ_MARGINAL),
        "S3": ("DT bias |Linux-Windows|", "s",
               THRESH_PLATFORM_DT_PASS, THRESH_PLATFORM_DT_MARGINAL),
    }
    for scen_id, (label, unit, pass_t, marg_t) in bias_gates.items():
        if scen_id not in platform_bias:
            continue
        b = platform_bias[scen_id].get("mean_bias", float("nan"))
        if math.isnan(b):
            continue
        v = _verdict_platform_bias(b, pass_t, marg_t)
        verdict_rows.append((label, scen_id, f"{b:+.3f} {unit}", v))
        if v == "FAIL":
            fails.append(f"{label} ({scen_id}) = {b:+.3f} {unit} (gate: <= {marg_t} {unit})")
        elif v == "MARGINAL":
            marginals.append(f"{label} ({scen_id}) = {b:+.3f} {unit}")

    # Between-platform Kappa
    for label, info in kappa_results.items():
        k = info.get("kappa", float("nan"))
        if math.isnan(k):
            continue
        if label == "between_platforms":
            v = _verdict_kappa_xplat(k)
            verdict_rows.append(("Between-platform kappa", "S4+S5", f"{k:.3f}", v))
            if v == "FAIL":
                fails.append(f"Between-platform kappa = {k:.3f} (gate >= {THRESH_KAPPA_XPLAT_PASS})")
            elif v == "MARGINAL":
                marginals.append(f"Between-platform kappa = {k:.3f}")
        else:
            v = _verdict_kappa(k)
            verdict_rows.append((f"Kappa {label}", "S4+S5", f"{k:.3f}", v))
            if v == "FAIL":
                fails.append(f"Kappa ({label}) = {k:.3f}")

    # FP event count
    for appr, info in fp_results.items():
        n_events = info.get("n_fp_events", float("nan"))
        if isinstance(n_events, float) and math.isnan(n_events):
            continue
        event_rate = info["event_rate"]
        rob_95 = info["rob_95"]
        rob_str = f"; 95% UB <= {rob_95:.2f}%" if rob_95 is not None else ""
        v = _verdict_fp(info)
        value_str = (f"{int(n_events)}/{info['n_slots']} slots "
                     f"(event {event_rate:.1f}%{rob_str})")
        verdict_rows.append(("FP event count", f"S5/{appr}", value_str, v))
        if v == "FAIL":
            fails.append(f"FP event count ({appr}): {int(n_events)} events (gate = 0)")

    # SNR bias per appraiser (STUDY-SPEC §8.1)
    for appr, info in bias_results.items():
        b = info.get("mean_bias", float("nan"))
        if math.isnan(b):
            continue
        v = _verdict_bias(b)
        verdict_rows.append(("SNR bias vs truth", f"S1/{appr}", f"{b:+.2f} dB", v))
        if v == "FAIL":
            fails.append(f"SNR bias ({appr}) = {b:+.2f} dB (gate <= {THRESH_BIAS_PASS} dB)")

    # McNemar
    p_mc = mcnemar.get("p_value", float("nan"))
    if not math.isnan(p_mc):
        v = mcnemar.get("verdict", "—")
        verdict_rows.append(("McNemar chi2 p-value", "all", f"p={p_mc:.4f}", v))
        if v == "FAIL":
            fails.append(f"McNemar test rejected at p={p_mc:.4f} (alpha={THRESH_MCNEMAR_P})")

    # Fisher FP parity
    p_fisher = fisher_fp.get("p_value", float("nan"))
    if not math.isnan(p_fisher):
        v = fisher_fp.get("verdict", "—")
        verdict_rows.append(("FP parity Fisher p", "S5", f"p={p_fisher:.4f}", v))
        if v == "FAIL":
            fails.append(f"FP parity Fisher test rejected at p={p_fisher:.4f}")

    overall = "FAIL" if fails else ("MARGINAL" if marginals else "PASS")
    return verdict_rows, overall, fails


# ---------------------------------------------------------------------------
# Report writer (NFR-023 five-section structure)
# ---------------------------------------------------------------------------

def _write_report(
    run_dir: Path,
    git_sha: str,
    continuous_results: dict,
    kappa_results: dict,
    fp_results: dict,
    bias_results: dict,
    platform_bias: dict,
    mcnemar: dict,
    fisher_fp: dict,
    verdict_rows: list,
    overall: str,
    fails: list[str],
    attr_results: dict | None = None,
    s7_results: dict | None = None,
    decode_rate_results: list[dict] | None = None,
) -> Path:
    lines: list[str] = []
    run_date_parts = run_dir.name.split("-")[0:3]
    run_date_str = "-".join(run_date_parts) if len(run_date_parts) >= 3 else run_dir.name
    win, lin = APPRAISERS

    # ── Section 1 — Study hypothesis (QA-authored placeholder) ──────────────
    lines += [
        "# OpenWSFZ Cross-Platform R&R Study Report",
        "",
        "## Section 1 — Study Hypothesis",
        "",
        "> **[QA-authored — required by HK-001]**",
        ">",
        "> _Insert: which shim version is under test; whether this is a parity confirmation",
        "> or regression investigation; which hypotheses (H0_DEC through H0_COMP) are live;",
        "> what outcome would constitute a significant finding._",
        "",
    ]

    # ── Section 2 — Data summary (generated) ────────────────────────────────
    _all_scenarios = (
        set(continuous_results.keys())
        | ({"S5"} if fp_results else set())
        | ({"S4"} if attr_results else set())
    )
    if decode_rate_results:
        _all_scenarios |= {r["scenario_id"] for r in decode_rate_results}
    if s7_results:
        _all_scenarios.add("S7")
    lines += [
        "## Section 2 — Data Summary",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Run date | {run_date_str} |",
        f"| OpenWSFZ git SHA | `{git_sha}` |",
        f"| Shim version (both platforms) | *(verify via GET /api/v1/status)* |",
        f"| Windows platform | win-x64, WASAPI, `libft8.dll` shim 20260030 |",
        f"| Linux platform | WSL2 linux-x64, ALSA-PulseAudio, `libft8.so` shim 20260030 |",
        f"| Scenarios run | {', '.join(sorted(_all_scenarios))} |",
        "",
    ]

    # ── Section 3 — Results (generated) ─────────────────────────────────────
    lines += ["## Section 3 — Results", ""]

    for scen_id, res in sorted(continuous_results.items()):
        if res is None:
            lines += [f"### {scen_id}", "", "_Insufficient data — skipped._", ""]
            continue
        anova = res["anova"]
        metrics = res["metrics"]
        response = res["response"]

        lines += [
            f"### {scen_id} — {response}",
            "",
            "#### Variance Components",
            "",
            "| Component | sigma^2 | %Contribution |",
            "|---|---|---|",
            f"| Repeatability | {_fmt_num(anova['var_repeatability'])} | {_fmt_num(metrics['pct_contribution_repeat'])}% |",
            f"| Reproducibility (platform) | {_fmt_num(anova['var_reproducibility'])} | {_fmt_num(metrics['pct_contribution_reprod'])}% |",
            f"| Part-to-Part | {_fmt_num(anova['var_part'])} | {_fmt_num(metrics['pct_contribution_part'])}% |",
            f"| Total GR&R | {_fmt_num(anova['var_grr'])} | {_fmt_num(metrics['pct_contribution_grr'])}% |",
            f"| Total | {_fmt_num(anova['var_total'])} | 100.00% |",
            "",
            "#### Study Metrics",
            "",
            "| Metric | Value | Verdict |",
            "|---|---|---|",
            f"| %Tolerance (GR&R) | {_fmt_num(metrics['pct_tolerance'])}% | {_verdict_grr(metrics['pct_contribution_grr'])} |",
            f"| %Study Var (GR&R) | {_fmt_num(metrics['pct_study_var_grr'])}% | — |",
            f"| ndc | {metrics['ndc']} | {_verdict_ndc(metrics['ndc'])} |",
            "",
        ]
        png_name = f"{scen_id}_grr_panel.png"
        lines += [f"![{scen_id} GR&R panel]({png_name})", ""]

        if scen_id == "S1" and bias_results:
            lines += ["#### Bias & Linearity (individual platform vs truth)", ""]
            lines += [f"| Platform | Mean Bias (dB) | Slope | R^2 | Verdict |",
                      "|---|---|---|---|---|"]
            for appr, bi in bias_results.items():
                v = _verdict_bias(bi["mean_bias"])
                lines.append(
                    f"| {appr} | {bi['mean_bias']:+.2f} | {bi['slope']:.3f} | "
                    f"{bi['r2']:.3f} | {v} |"
                )
            lines += ["", f"![S1 Bias & Linearity](S1_bias_linearity.png)", ""]

        # Platform bias (Linux - Windows)
        if scen_id in platform_bias:
            pb = platform_bias[scen_id]
            bias_labels = {
                "S1": ("SNR bias |Linux-Windows|", "dB",
                       THRESH_PLATFORM_SNR_PASS, THRESH_PLATFORM_SNR_MARGINAL),
                "S2": ("Freq bias |Linux-Windows|", "Hz",
                       THRESH_PLATFORM_FREQ_PASS, THRESH_PLATFORM_FREQ_MARGINAL),
                "S3": ("DT bias |Linux-Windows|", "s",
                       THRESH_PLATFORM_DT_PASS, THRESH_PLATFORM_DT_MARGINAL),
            }
            if scen_id in bias_labels:
                blabel, bunit, bpass, bmarg = bias_labels[scen_id]
                b = pb.get("mean_bias", float("nan"))
                p_val = pb.get("p_value", float("nan"))
                n_pairs = pb.get("n_pairs", 0)
                bv = _verdict_platform_bias(b, bpass, bmarg)
                lines += [
                    f"#### Platform Bias ({lin} - {win})",
                    "",
                    f"| Metric | Value | Gate | Verdict |",
                    "|---|---|---|---|",
                    f"| Mean {blabel} | {_fmt_num(b, '+.3f')} {bunit} | <= {bmarg} {bunit} | {bv} |",
                    f"| Paired t-test p | {_fmt_num(p_val, '.4f')} | | — |",
                    f"| n matched pairs | {n_pairs} | | |",
                    "",
                ]

        if scen_id == "S1":
            lines += ["![S1 Platform Bias](S1_platform_bias.png)", ""]

        if scen_id == "S3":
            jitter_img = "S3_dt_jitter.png"
            lines += [
                "#### DT Jitter Time-Series",
                "",
                f"![S3 DT Jitter]({jitter_img})",
                "",
            ]

    # Decode-rate companion studies
    for dr in (decode_rate_results or []):
        lines += _decode_rate_report_lines(dr)

    # Attribute
    if attr_results:
        lines += _attribute_report_lines(attr_results)

    if fp_results:
        lines += ["### False-positive rate (S5)", ""]
        lines += [f"| Platform | FP events / slots | Event rate | 95% UB | Verdict |",
                  "|---|---|---|---|---|"]
        for appr, info in fp_results.items():
            n_events = info.get("n_fp_events", float("nan"))
            if isinstance(n_events, float) and math.isnan(n_events):
                lines.append(f"| {appr} | — | — | — | — |")
                continue
            n_slots = info["n_slots"]
            event_rate = info["event_rate"]
            rob_95 = info["rob_95"]
            rob_str = f"<= {rob_95:.2f}%" if rob_95 is not None else "—"
            v = _verdict_fp(info)
            lines.append(
                f"| {appr} | {int(n_events)} / {n_slots} "
                f"| {_fmt_num(event_rate)}% | {rob_str} | {v} |"
            )
        lines += [""]

        # McNemar and Fisher
        lines += ["### Cross-platform attribute parity", ""]
        mc_chi2 = mcnemar.get("chi2", float("nan"))
        mc_p = mcnemar.get("p_value", float("nan"))
        mc_n12 = mcnemar.get("n12", 0)
        mc_n21 = mcnemar.get("n21", 0)
        mc_v = mcnemar.get("verdict", "—")
        lines += [
            "| Test | Statistic | p-value | Verdict |",
            "|---|---|---|---|",
            f"| McNemar (Win+/Lin- vs Win-/Lin+) = ({mc_n12}/{mc_n21}) "
            f"| chi2 = {_fmt_num(mc_chi2, '.3f')} | {_fmt_num(mc_p, '.4f')} | {mc_v} |",
        ]
        fp_p = fisher_fp.get("p_value", float("nan"))
        fp_v = fisher_fp.get("verdict", "—")
        lines.append(
            f"| Fisher FP parity (S5 Windows vs Linux) | — | {_fmt_num(fp_p, '.4f')} | {fp_v} |"
        )
        lines += [""]

    # S7
    if s7_results:
        lines += _compounding_report_lines(s7_results)

    # ── Section 4 — Summary verdict table (generated) ────────────────────────
    lines += [
        "## Section 4 — Summary Verdict",
        "",
        "| Metric | Scope | Value | Verdict |",
        "|---|---|---|---|",
    ]
    for row in verdict_rows:
        lines.append(f"| {row[0]} | {row[1]} | {row[2]} | {row[3]} |")
    lines += [
        "",
        f"**Overall verdict: {overall}**",
        "",
    ]

    if fails:
        lines += ["### Defect Notices", ""]
        for f in fails:
            lines.append(f"- FAIL — {f}")
        lines += [""]

    # ── Section 5 — Recommendations (QA-authored placeholder) ───────────────
    lines += [
        "## Section 5 — Recommendations",
        "",
        "> **[QA-authored — required by HK-001]**",
        ">",
        "> _For each FAIL or MARGINAL metric: state the hypothesis rejected, the most",
        "> probable physical cause (audio latency, floating-point divergence, sample-rate",
        "> mismatch), and the recommended next diagnostic step. If all metrics PASS,",
        "> write: 'No further investigation required.'_",
        "",
    ]

    report_path = run_dir / "report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


# ---------------------------------------------------------------------------
# Trend CSV (cross-platform variant)
# ---------------------------------------------------------------------------

_TREND_COLUMNS_XPLAT = [
    "run_date", "git_sha",
    "pct_grr_snr", "ndc_snr",
    "platform_snr_bias_db",
    "between_platform_kappa",
    "fp_events_windows", "fp_events_linux",
    "mcnemar_p", "overall",
]


def _append_trend(qa_rr_root: Path, run_dir: Path, git_sha: str,
                  continuous_results: dict, kappa_results: dict,
                  fp_results: dict, platform_bias: dict,
                  mcnemar: dict, overall: str) -> None:
    import csv as _csv
    trend_path = qa_rr_root / "trend_xplat.csv"
    write_header = not trend_path.exists()

    run_date_parts = run_dir.name.split("-")[0:3]
    run_date_str = "-".join(run_date_parts) if len(run_date_parts) >= 3 else run_dir.name

    def _safe(v: Any) -> str:
        if v is None or (isinstance(v, float) and math.isnan(v)):
            return ""
        return str(round(v, 4) if isinstance(v, float) else v)

    pct_grr_snr = ndc_snr = ""
    if "S1" in continuous_results and continuous_results["S1"] is not None:
        pct_grr_snr = _safe(continuous_results["S1"]["metrics"]["pct_contribution_grr"])
        ndc_snr = _safe(continuous_results["S1"]["metrics"]["ndc"])

    platform_snr_bias_db = _safe(platform_bias.get("S1", {}).get("mean_bias", float("nan")))

    bk = kappa_results.get("between_platforms", {})
    between_kappa = _safe(bk.get("kappa", float("nan")))

    win_fp = _safe(fp_results.get("Windows", {}).get("n_fp_events", float("nan")))
    lin_fp = _safe(fp_results.get("Linux", {}).get("n_fp_events", float("nan")))
    mc_p = _safe(mcnemar.get("p_value", float("nan")))

    row = {
        "run_date": run_date_str,
        "git_sha": git_sha,
        "pct_grr_snr": pct_grr_snr,
        "ndc_snr": ndc_snr,
        "platform_snr_bias_db": platform_snr_bias_db,
        "between_platform_kappa": between_kappa,
        "fp_events_windows": win_fp,
        "fp_events_linux": lin_fp,
        "mcnemar_p": mc_p,
        "overall": overall,
    }

    with open(trend_path, "a", newline="", encoding="utf-8") as fh:
        writer = _csv.DictWriter(fh, fieldnames=_TREND_COLUMNS_XPLAT)
        if write_header:
            writer.writeheader()
        writer.writerow(row)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Cross-platform R&R analyser (Windows vs Linux/WSL2)"
    )
    parser.add_argument("--run-dir", required=True,
                        help="Run directory containing *_matched.csv files")
    parser.add_argument("--scenario",
                        help="Comma-separated scenario IDs to analyse (default: all found)")
    args = parser.parse_args()

    run_dir = Path(args.run_dir)
    if not run_dir.exists():
        sys.exit(f"ERROR: run directory does not exist: {run_dir}")

    scenario_filter = [s.strip() for s in args.scenario.split(",")] if args.scenario else None
    scenarios_dir = _QA_ROOT / "scenarios"

    matched = _load_matched_csvs(run_dir, scenario_filter, scenarios_dir)
    if not matched:
        sys.exit(f"ERROR: no *_matched.csv files found in {run_dir}")

    print(f"Analysing: {', '.join(sorted(matched.keys()))}")
    git_sha = _git_sha()
    scenario_meta = _load_scenario_meta(scenarios_dir)

    continuous_results: dict = {}
    kappa_results: dict = {}
    fp_results: dict = {}
    bias_results: dict = {}
    platform_bias: dict = {}

    # --- Continuous GR&R (S1, S2, S3) ---
    for scen_id, df in matched.items():
        if scen_id not in CONTINUOUS_SCENARIOS:
            continue
        response = RESPONSE_VAR[scen_id]
        tol_half = TOLERANCE_HALF[scen_id]

        # NOTE: No WSJT-X DT correction in xplat study — both platforms use UTC convention.

        anova = _two_way_anova(df, response, scen_id)
        if anova is None:
            continuous_results[scen_id] = None
            continue
        metrics = _derived_metrics(anova, tol_half)
        continuous_results[scen_id] = {
            "anova": anova, "metrics": metrics,
            "response": response, "tol_half": tol_half,
        }
        print(f"  {scen_id}: %GR&R={metrics['pct_contribution_grr']:.1f}%  ndc={metrics['ndc']}")
        png = _plot_grr_panel(df, response, anova, metrics, scen_id, run_dir)
        print(f"    -> {png.name}")

        # Platform bias (Linux - Windows)
        pb = _platform_bias_metrics(df, response)
        platform_bias[scen_id] = pb
        print(f"  {scen_id} platform bias (Linux-Windows): {_fmt_num(pb['mean_bias'], '+.3f')} "
              f"{response.split('_')[1]}  p={_fmt_num(pb['p_value'], '.4f')}  "
              f"n={pb['n_pairs']}")

    # --- S1 Bias & Linearity ---
    if "S1" in matched and continuous_results.get("S1") is not None:
        bias_results = _bias_linearity(matched["S1"], run_dir)
        for appr, info in bias_results.items():
            print(f"  S1 bias ({appr}): {info['mean_bias']:+.2f} dB  slope={info['slope']:.3f}")
        # Platform bias scatter chart
        chart = _platform_bias_chart(matched["S1"], run_dir)
        if chart:
            print(f"    -> {chart.name}")

    # --- S3 DT jitter time-series ---
    if "S3" in matched and continuous_results.get("S3") is not None:
        jitter_chart = _dt_jitter_timeseries(matched["S3"], run_dir)
        if jitter_chart:
            print(f"  S3 DT jitter time-series -> {jitter_chart.name}")

    # --- Decode-rate companions (S1b, S3b) ---
    decode_rate_results: list[dict] = []
    for sid in sorted(DECODE_RATE_SCENARIOS):
        if sid not in matched:
            continue
        cfg = DECODE_RATE_CONFIG[sid]
        dr = _analyse_decode_rate(
            matched[sid], sid, run_dir,
            part_var=cfg["part_var"],
            part_label=cfg["part_label"],
        )
        decode_rate_results.append(dr)
        for appr in APPRAISERS:
            rate = dr["overall"].get(appr, float("nan"))
            print(f"  {sid} decode rate ({appr}): {_fmt_num(rate)}%  (informational)")

    # --- Attribute (S4 + S5) ---
    attr_results: dict | None = None
    if "S4" in matched or "S5" in matched:
        attr_results = _attribute_agreement(matched, run_dir)
        kappa_results = attr_results["kappa"]
        for label, info in kappa_results.items():
            print(f"  Kappa {label}: {_fmt_num(info.get('kappa', float('nan')), '.3f')}")

    # --- FP rate (S5) ---
    if "S5" in matched:
        fp_results = _fp_rate(matched["S5"])
        for appr, info in fp_results.items():
            n_events = info.get("n_fp_events", float("nan"))
            if isinstance(n_events, float) and math.isnan(n_events):
                print(f"  S5 FP ({appr}): undefined")
                continue
            print(
                f"  S5 FP ({appr}): {int(n_events)}/{info['n_slots']} events "
                f"(event rate {_fmt_num(info['event_rate'])}%)"
            )

    # --- McNemar's test (pooled all scenarios) ---
    mcnemar = _mcnemar_test(matched)
    print(f"  McNemar: n12={mcnemar['n12']} n21={mcnemar['n21']} "
          f"chi2={_fmt_num(mcnemar['chi2'], '.3f')} p={_fmt_num(mcnemar['p_value'], '.4f')} "
          f"-> {mcnemar['verdict']}")

    # --- Fisher FP parity ---
    fisher_fp = _fp_parity_fisher(fp_results) if fp_results else {"p_value": float("nan"), "verdict": "—"}
    if not math.isnan(fisher_fp["p_value"]):
        print(f"  Fisher FP parity: p={_fmt_num(fisher_fp['p_value'], '.4f')} -> {fisher_fp['verdict']}")

    # --- S7 co-channel ---
    s7_results: dict | None = None
    if "S7" in matched:
        s7_results = _analyse_compounding(matched["S7"], scenario_meta.get("S7"), run_dir)
        for appr in APPRAISERS:
            rate = s7_results["overall"].get(appr, float("nan"))
            print(f"  S7 recovery ({appr}): {_fmt_num(rate)}%")

    # --- Verdicts ---
    verdict_rows, overall, fails = _collect_verdicts(
        continuous_results, kappa_results, fp_results, bias_results,
        platform_bias, mcnemar, fisher_fp,
    )

    # --- Report ---
    report_path = _write_report(
        run_dir, git_sha, continuous_results, kappa_results,
        fp_results, bias_results, platform_bias, mcnemar, fisher_fp,
        verdict_rows, overall, fails,
        attr_results=attr_results,
        s7_results=s7_results,
        decode_rate_results=decode_rate_results,
    )
    print(f"\nReport written: {report_path}")
    print(f"Overall verdict: {overall}")

    if fails:
        print("\n[!] DEFECT NOTICES:")
        for f in fails:
            print(f"  FAIL — {f}")

    _append_trend(
        _QA_ROOT, run_dir, git_sha,
        continuous_results, kappa_results, fp_results,
        platform_bias, mcnemar, overall,
    )
    print(f"Trend row appended: {_QA_ROOT / 'trend_xplat.csv'}")
    print(f"\nRemember (HK-001): complete Sections 1 and 5 in {report_path}")


if __name__ == "__main__":
    main()
