#!/usr/bin/env python3
"""fp_composition_per_part.py -- FP-COMPOSITION QA task (2026-09-04).

Re-derives the S5 false-positive-gate event count, per run, split by
`part_index`, for the nine committed rr-study run directories named in

  qa/rr-study/2026-09-04-1820-architect-to-qa-amendment1-and-spec-s5-fp-per-part-rederivation.md

No decode. No capture. No src/native change. Pure re-analysis of CSVs
already committed under qa/rr-study/results/.

Method (STUDY-SPEC.md Section 16, restated exactly, HK-021(r) -- ship the
predicate as code rather than leaving it as prose anyone must re-derive by
hand):

  1. From `truth.csv`, take the rows with `scenario_id == "S5"`. These give
     the scoping filter -- the set of `cycle_utc` values that genuinely
     belong to S5 -- and the `cycle_utc -> part_index` map. Without this
     filter the join over-attributes: `matcher.py`'s `main()` parses the
     WHOLE session `ALL.TXT`, unscoped by time, so `S5_matched.csv` also
     carries `false_positive=True` rows generated by OTHER scenarios in the
     same session (confirmed directly: 7d36038's S5_matched.csv carries
     FP rows timestamped inside that run's S8 window).
  2. From `S5_matched.csv`, take rows for a given `appraiser`, restricted to
     cycle_utc values in step 1's set.
  3. Collapse decode ROWS to per-slot EVENTS: STUDY-SPEC Section 10 defines
     the gate as "the per-slot FP event rate -- P(a signal-free S5 slot
     emits >= 1 decode)". A slot (cycle_utc) with one or more
     false_positive=True decode rows is ONE event, not N events. Reporting
     decode rows as events is flagged in the spec as the likeliest way to
     get this wrong.
  4. Attribute each event's cycle_utc to its part_index via step 1's map.

Usage:
  python qa/rr-study/fp_composition_per_part.py
"""
from __future__ import annotations

import csv
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RESULTS = ROOT / "qa" / "rr-study" / "results"

# Nine runs named in the QA spec, in date order.
RUNS = [
    "2026-08-05-3bd4cd0",
    "2026-08-15-8d6e1b1",
    "2026-08-21-7d36038",
    "2026-08-22-f5dec23",
    "2026-08-27-22b749c",
    "2026-08-29-872ba65",
    "2026-08-30-2e60949",  # S5 lives here, NOT in 2026-08-31-2e60949 (that dir is the S7 re-run)
    "2026-09-02-3b52608",
    "2026-09-03-35378b9",
]

# Each run's own ratified §10 gate line, transcribed verbatim from that run's
# committed report.md, for ROW C1's reproduction check. Not an input to the
# join -- a fixed comparator the join's own output is checked against.
REPORTED_GATE = {
    "2026-08-05-3bd4cd0": {"OpenWSFZ": (0, 120), "WSJT-X": (0, 120)},
    "2026-08-15-8d6e1b1": {"OpenWSFZ": (1, 120), "WSJT-X": (0, 120)},
    "2026-08-21-7d36038": {"OpenWSFZ": (1, 120), "WSJT-X": (0, 120)},
    "2026-08-22-f5dec23": {"OpenWSFZ": (4, 120), "WSJT-X": (0, 120)},
    "2026-08-27-22b749c": {"OpenWSFZ": (0, 60), "WSJT-X": (0, 60)},
    "2026-08-29-872ba65": {"OpenWSFZ": (1, 60), "WSJT-X": (0, 60)},
    "2026-08-30-2e60949": {"OpenWSFZ": (2, 120), "WSJT-X": (0, 120)},
    "2026-09-02-3b52608": {"OpenWSFZ": (4, 60), "WSJT-X": (0, 60)},
    "2026-09-03-35378b9": {"OpenWSFZ": (2, 60), "WSJT-X": (0, 60)},
}

AWGN_PARTS = {"0", "1"}
PRE_WINDOW = {"2026-08-05-3bd4cd0", "2026-08-15-8d6e1b1", "2026-08-21-7d36038"}
POST_WINDOW = set(RUNS) - PRE_WINDOW


def is_true(val: str) -> bool:
    return val.strip().lower() in ("true", "1")


def load_s5_part_map(run_dir: Path) -> dict[str, str]:
    """cycle_utc -> part_index for scenario_id == S5 rows in truth.csv."""
    part_map: dict[str, str] = {}
    with (run_dir / "truth.csv").open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["scenario_id"] != "S5":
                continue
            cyc = row["cycle_utc"]
            pidx = row["part_index"]
            if cyc in part_map and part_map[cyc] != pidx:
                raise ValueError(f"{run_dir.name}: cycle_utc {cyc} maps to >1 part_index")
            part_map[cyc] = pidx
    return part_map


def scoped_fp_events(run_dir: Path, appraiser: str, s5_cycles: set[str]) -> dict[str, int]:
    """Returns {cycle_utc: decode_row_count} for FP rows of `appraiser`,
    restricted to `s5_cycles`. One dict entry per EVENT (slot); the value is
    the row count only for diagnostic/anomaly reporting, never used as the
    event count itself."""
    events: dict[str, int] = {}
    with (run_dir / "S5_matched.csv").open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["appraiser"] != appraiser:
                continue
            if not is_true(row["false_positive"]):
                continue
            cyc = row["cycle_utc"]
            if cyc not in s5_cycles:
                continue
            events[cyc] = events.get(cyc, 0) + 1
    return events


def scoped_fp_row_count(run_dir: Path, appraiser: str, s5_cycles: set[str]) -> int:
    """Total FP decode ROWS (not events) scoped to S5 -- used only for the
    C2 anomaly ratio, never for the gate count itself."""
    n = 0
    with (run_dir / "S5_matched.csv").open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["appraiser"] != appraiser:
                continue
            if not is_true(row["false_positive"]):
                continue
            if row["cycle_utc"] in s5_cycles:
                n += 1
    return n


def main() -> int:
    per_run = {}
    for name in RUNS:
        run_dir = RESULTS / name
        part_map = load_s5_part_map(run_dir)
        s5_cycles = set(part_map)
        n_slots = len(s5_cycles)

        result = {"n_slots": n_slots}
        for appraiser in ("OpenWSFZ", "WSJT-X"):
            events = scoped_fp_events(run_dir, appraiser, s5_cycles)
            row_count = scoped_fp_row_count(run_dir, appraiser, s5_cycles)
            by_part: dict[str, int] = {}
            for cyc in events:
                p = part_map[cyc]
                by_part[p] = by_part.get(p, 0) + 1
            result[appraiser] = {
                "n_events": len(events),
                "scoped_fp_rows": row_count,
                "by_part": by_part,
            }
        per_run[name] = result

    # ---- ROW C1: reproduction gate ----
    print("=== ROW C1 -- reproduction gate ===")
    c1_fires = False
    for name in RUNS:
        r = per_run[name]
        for appraiser in ("OpenWSFZ", "WSJT-X"):
            recomputed = (r[appraiser]["n_events"], r["n_slots"])
            reported = REPORTED_GATE[name][appraiser]
            ok = recomputed == reported
            if not ok:
                c1_fires = True
            print(f"  {name:24s} {appraiser:8s} recomputed={recomputed} "
                  f"reported={reported} {'OK' if ok else '*** MISMATCH ***'}")
    print(f"ROW C1: {'FIRES -- STOP' if c1_fires else 'does not fire'}")
    if c1_fires:
        print("Per spec: STOP. Nothing downstream may be cited.")
        return 1

    # ---- ROW C2: 8d6e1b1 anomaly ----
    print()
    print("=== ROW C2 -- 2026-08-15-8d6e1b1 anomaly ===")
    anomaly_name = "2026-08-15-8d6e1b1"
    anomaly_events = per_run[anomaly_name]["OpenWSFZ"]["n_events"]
    anomaly_scoped_rows = per_run[anomaly_name]["OpenWSFZ"]["scoped_fp_rows"]
    other_scoped_rows = [
        per_run[n]["OpenWSFZ"]["scoped_fp_rows"] for n in RUNS if n != anomaly_name
    ]
    median_other = statistics.median(other_scoped_rows)
    ratio = anomaly_scoped_rows / median_other if median_other else float("inf")

    with (RESULTS / anomaly_name / "S5_matched.csv").open(newline="", encoding="utf-8") as f:
        total_rows_in_file = sum(1 for _ in csv.DictReader(f))

    c2_fires = (anomaly_events != 1) or (ratio > 5)
    print(f"  recomputed events (OpenWSFZ): {anomaly_events} (expect 1)")
    print(f"  scoped FP rows (OpenWSFZ), post cycle_utc filter: {anomaly_scoped_rows}")
    print(f"  raw S5_matched.csv row count (unscoped): {total_rows_in_file}")
    print(f"  median scoped FP rows across other 8 runs: {median_other}")
    print(f"  ratio: {ratio:.2f}x")
    print(f"ROW C2: {'FIRES -- STOP' if c2_fires else 'does not fire'}")
    if c2_fires:
        print("Per spec: STOP. Do not fix, exclude, or re-pool. PO's to rule on.")
        return 1

    # ---- ROW C3: composition claim ----
    print()
    print("=== ROW C3 -- composition table (counts only, no verdict) ===")
    c3_fires = False
    for label, window in (("Pre-window", PRE_WINDOW), ("Post-window", POST_WINDOW)):
        runs_in_window = [n for n in RUNS if n in window]
        total_events = sum(per_run[n]["OpenWSFZ"]["n_events"] for n in runs_in_window)
        total_slots = sum(per_run[n]["n_slots"] for n in runs_in_window)
        awgn_slots = sum(
            sum(1 for p in load_s5_part_map(RESULTS / n).values() if p in AWGN_PARTS)
            for n in runs_in_window
        )
        events_01 = sum(
            sum(c for p, c in per_run[n]["OpenWSFZ"]["by_part"].items() if p in AWGN_PARTS)
            for n in runs_in_window
        )
        events_23 = sum(
            sum(c for p, c in per_run[n]["OpenWSFZ"]["by_part"].items() if p not in AWGN_PARTS)
            for n in runs_in_window
        )
        if events_23 > 0:
            c3_fires = True
        print(f"  {label} ({len(runs_in_window)} runs, {', '.join(runs_in_window)}):")
        print(f"    events={total_events} slots_gated={total_slots} "
              f"AWGN_slots={awgn_slots} events_parts01={events_01} events_parts23={events_23}")

    print(f"ROW C3: {'FIRES' if c3_fires else 'does not fire'}")

    print()
    print("=== Per-run detail (OpenWSFZ) ===")
    for name in RUNS:
        r = per_run[name]["OpenWSFZ"]
        print(f"  {name:24s} n_slots={per_run[name]['n_slots']:3d} "
              f"events={r['n_events']:2d} by_part={dict(sorted(r['by_part'].items()))}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
