"""L5b -- Two-path Watterson fading (E4-BENCH FADE family, Sec.2.3).

    y(t) = Re{ g1(t) * z(t) + g2(t) * z(t - tau) },   tau = 1 ms

``z(t) = exp(j*phase(t))`` is built from the modulator's own instantaneous phase
(:func:`synth.modulator.instantaneous_phase`) -- no amplitude envelope yet (that is
applied to the real-valued ``y(t)`` afterwards, via the same click-envelope the DRIFT/
plain path uses) and no drift (FADE and DRIFT are never combined on the same station
in E4's ladder, Sec.2.4 -- 7 DRIFT doses and 8 FADE doses fill the 15-station slot,
one family per station).

``g1``, ``g2``: independent, zero-mean complex Gaussian processes, each with ensemble
power ``E|gk|^2 = 1/2`` (so ``E|g1|^2 + E|g2|^2 = 1``, average SNR = nominal SNR) and a
Gaussian Doppler spectrum whose frequency spread ``B`` is defined as ``2*sigma`` of that
spectrum (ITU-R F.1487 convention). Generated by shaping complex white Gaussian noise in
the frequency domain, per the spec's own prescription.

Never normalise a REALISED draw to unit power -- that would delete the slow-fade lottery,
which is half of what fading is. The 1/2 target is enforced by a FIXED, draw-independent
filter gain, derived once analytically from Parseval's theorem for a given ``(B, n,
sample_rate_hz)`` -- never from any specific noise realisation. See
:func:`_shaped_gaussian_process`'s derivation below.
"""
from __future__ import annotations

import numpy as np

from .constants import DEFAULT_SAMPLE_RATE_HZ, SLOT_LENGTH_S
from .modulator import _apply_click_envelope, _place_in_slot, instantaneous_phase

FADE_TAU_S = 0.001  # 1 ms two-path delay (Sec.2.3)


def _shaped_gaussian_process(
    n: int,
    spread_hz: float,
    sample_rate_hz: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """One realisation of a complex Gaussian process with a Gaussian Doppler spectrum.

    `spread_hz` is `B` = 2*sigma (ITU-R F.1487 convention). Returns an `n`-sample
    complex array with ensemble power `E|g[n]|^2 = 0.5`, enforced by a fixed,
    draw-independent filter gain -- see module docstring.

    Derivation of the fixed gain (numpy's FFT convention: unnormalised forward,
    ``1/N`` on the inverse). For unit-power complex white noise `w`
    (`E|w[n]|^2 = 1`), Parseval gives `E|W[k]|^2 = n` per frequency bin. Filtering
    by a real magnitude response `H` gives `E|G[k]|^2 = H[k]^2 * n`, and Parseval
    again on the inverse transform gives the average per-sample power of
    `g = ifft(G)` as `sum_k(H[k]^2) / n`. Scaling `H` by a constant `c` scales this
    average power by `c^2`; solving `c^2 * sum(H_raw^2)/n = 0.5` gives the `c` used
    below. This is a property of the filter alone (`B`, `n`, `sample_rate_hz`), not
    of any particular noise draw -- ROW 0a(iii) verifies it holds in practice.

    `B` = `2*sigma` of "that spectrum" (Sec.2.3) is the standard deviation of the
    DOPPLER *POWER* spectrum `S(f) = |H(f)|^2` -- not of the magnitude response `H`
    itself. If `H(f) = exp(-f^2 / (2*sigma_h^2))`, then `S(f) = H(f)^2 =
    exp(-f^2 / sigma_h^2)`, whose own standard deviation is `sigma_h / sqrt(2)`, not
    `sigma_h`. So to make `S(f)`'s standard deviation equal `B/2`, the magnitude
    response's own sigma must be `sigma_h = (B/2) * sqrt(2)`, not `B/2` (verified:
    using `sigma_h = B/2` directly measured a 2-sigma power-spectrum spread ~1/sqrt(2)
    of `B` on a 2000 s synthetic carrier, exactly the missing factor).
    """
    sigma_h = (spread_hz / 2.0) * np.sqrt(2.0)
    freqs = np.fft.fftfreq(n, d=1.0 / sample_rate_hz)

    if sigma_h <= 0.0:
        # Not one of E4's doses (min 0.1 Hz) but guarded: a zero-spread Doppler
        # spectrum is a pure DC (time-invariant) process.
        h_raw = (freqs == 0.0).astype(np.float64)
    else:
        h_raw = np.exp(-(freqs ** 2) / (2.0 * sigma_h ** 2))

    raw_power = float(np.sum(h_raw ** 2)) / n
    if raw_power <= 0.0:
        raise ValueError(
            f"spread_hz={spread_hz} produced a zero-energy Doppler filter at "
            f"sample_rate_hz={sample_rate_hz}, n={n} (too narrow to resolve at this "
            f"frequency resolution -- widen n or spread_hz)"
        )
    gain = np.sqrt(0.5 / raw_power)
    h = h_raw * gain

    # Unit-power complex white noise: E|w[n]|^2 = 1 (real, imag each variance 0.5).
    w = (rng.standard_normal(n) + 1j * rng.standard_normal(n)) / np.sqrt(2.0)
    return np.fft.ifft(np.fft.fft(w) * h)


def _wrapped_shaped_gaussian_process(
    n: int,
    spread_hz: float,
    sample_rate_hz: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """`n` samples of :func:`_shaped_gaussian_process`, generated on a longer buffer
    and truncated, to avoid the circular-shaping wrap (amendment A1, Sec.8.3).

    Frequency-domain shaping via `ifft(fft(w) * H)` is inherently CIRCULAR
    convolution: the process's last sample is adjacent to its first in the FFT's
    own topology, so on a buffer exactly `n` (one transmission) long, the gain at
    the last symbol is spuriously correlated with the gain at the first (measured
    0.89-1.02 at every dose on the un-fixed generator; the true correlation at that
    lag is <= 4e-4). Generating on `L = T_tx + 2/B` seconds and keeping only the
    first `n` samples pushes the wrap-around term down to `exp(-2*pi**2) ~ 3e-9`
    (A1's own figure) -- negligible. Worst case is `B` = 0.1 Hz: `L` = 12.64 + 20 =
    32.64 s.
    """
    transmission_s = n / sample_rate_hz
    buffer_s = transmission_s + 2.0 / spread_hz
    buffer_n = max(n, int(np.ceil(buffer_s * sample_rate_hz)))
    full = _shaped_gaussian_process(buffer_n, spread_hz, sample_rate_hz, rng)
    return full[:n]


def generate_fade_pair(
    n: int,
    spread_hz: float,
    sample_rate_hz: int,
    seed: int,
) -> "tuple[np.ndarray, np.ndarray]":
    """The exact `(g1, g2)` generation :func:`modulate_faded` uses -- factored out
    so ROW 0a(iii) checks (b)/(c) exercise this SAME code path, not a
    re-implementation of it (amendment A1, Sec.8.3: "the function `modulate_faded`
    itself calls").
    """
    rng = np.random.default_rng(seed)
    g1 = _wrapped_shaped_gaussian_process(n, spread_hz, sample_rate_hz, rng)
    g2 = _wrapped_shaped_gaussian_process(n, spread_hz, sample_rate_hz, rng)
    return g1, g2


def modulate_faded(
    tones: list[int],
    base_freq_hz: float,
    spread_hz: float,
    dt_s: float = 0.0,
    sample_rate_hz: int = DEFAULT_SAMPLE_RATE_HZ,
    slot_length_s: float = SLOT_LENGTH_S,
    amplitude: float = 1.0,
    *,
    seed: int,
    extended: bool = False,
    tau_s: float = FADE_TAU_S,
):
    """Render `tones` through a two-path Watterson fading channel (Sec.2.3), placed
    at `dt_s` in a `slot_length_s` slot -- the FADE-family counterpart to
    :func:`synth.modulator.modulate` (DRIFT). Shares that function's click-envelope
    and slot-placement logic exactly (:func:`synth.modulator._apply_click_envelope`,
    :func:`synth.modulator._place_in_slot`), so the two families compose identically
    with the rest of the pipeline (`encoder.py`, `channel.mix_to_shared_floor`) --
    same single-slot-or-raise / `extended` contract as `modulate`.

    `seed` must come from the caller, keyed on `(trial, position)` and independent of
    the AWGN seed used elsewhere for the same trial (Sec.2.3) -- e.g.
    ``compute_seed("E4-FADE", position, trial_index)`` against the scenario's own
    ``compute_seed("E4", 0, trial_index)`` for the shared noise floor. `seed` is
    consumed by both `g1` and `g2` in sequence from one `Generator`, so the two paths
    are independent draws from the same deterministic stream, not from two identical
    seeds.
    """
    phase = instantaneous_phase(tones, base_freq_hz, sample_rate_hz)  # no drift (Sec.2.4)
    z = np.exp(1j * phase)
    n = len(z)

    g1, g2 = generate_fade_pair(n, spread_hz, sample_rate_hz, seed)

    delay_samples = int(round(tau_s * sample_rate_hz))
    z_delayed = np.concatenate([np.zeros(delay_samples, dtype=complex), z])[:n]

    signal = amplitude * np.real(g1 * z + g2 * z_delayed)
    signal = _apply_click_envelope(signal, sample_rate_hz)
    return _place_in_slot(signal, dt_s, sample_rate_hz, slot_length_s, extended)
