namespace OpenWSFZ.Web;

/// <summary>
/// Public façade that allows <c>OpenWSFZ.Daemon</c> components (e.g.
/// <c>QsoAnswererService</c> and the <c>POST /api/v1/audio-offset</c> endpoint)
/// to broadcast <c>audioOffset</c> WebSocket events to all connected clients
/// without depending on the internal <see cref="WebSocketHub"/> class directly.
///
/// <para>
/// Carries an <c>appScope</c> GUID (N6) so <see cref="WebSocketHub.BroadcastAudioOffset"/>
/// only delivers to sockets belonging to the same <see cref="WebApp"/> instance — mirrors
/// <see cref="CatEventBus"/>'s scope-guard pattern. Defaulted rather than required because
/// many tests construct this bus directly without a real <c>WebApp</c>/socket in play, where
/// the scope value is never actually consulted (<c>ActiveSockets.IsEmpty</c> short-circuits
/// first).
/// </para>
/// </summary>
public sealed class AudioOffsetEventBus
{
    private readonly Guid _appScope;

    /// <summary>
    /// Creates a new <see cref="AudioOffsetEventBus"/>, optionally bound to an
    /// app-instance scope.
    /// </summary>
    /// <param name="appScope">
    /// Scope ID generated by <see cref="WebApp.Create"/> for this application instance.
    /// Defaults to <see cref="Guid.Empty"/> for callers that never register a real socket.
    /// </param>
    public AudioOffsetEventBus(Guid appScope = default) => _appScope = appScope;

    /// <summary>
    /// Broadcasts an <c>audioOffset</c> event carrying the new RX Hz, TX Hz, and
    /// Hold TX Freq state to every WebSocket client currently connected to this
    /// bus's app-instance scope.
    /// </summary>
    /// <param name="rxHz">New RX audio frequency cursor position in Hz (0–3000).</param>
    /// <param name="txHz">New TX audio frequency cursor position in Hz (0–3000).</param>
    /// <param name="holdTxFreq">
    /// Whether the QSO answerer is locked to the operator-set TX frequency.
    /// </param>
    public void Publish(int rxHz, int txHz, bool holdTxFreq)
        => WebSocketHub.BroadcastAudioOffset(_appScope, rxHz, txHz, holdTxFreq);
}
