using OpenWSFZ.Abstractions;

namespace OpenWSFZ.Web;

/// <summary>
/// Public façade that allows <c>OpenWSFZ.Daemon.Cat.CatPollingService</c> to
/// broadcast <c>cat_status</c> WebSocket events to all connected clients
/// without depending on the internal <see cref="WebSocketHub"/> class directly
/// (FR-033).
///
/// <para>
/// Each bus instance carries the <c>appScope</c> assigned by
/// <see cref="WebApp.Create"/> so that <see cref="WebSocketHub.BroadcastCatStatus"/>
/// only delivers events to sockets that belong to the same <see cref="WebApp"/>
/// instance.  This prevents cross-contamination between concurrent <c>WebApp</c>
/// instances in the same process (e.g. integration-test servers).
/// </para>
/// </summary>
public sealed class CatEventBus
{
    private readonly Guid _appScope;

    /// <summary>
    /// Creates a new <see cref="CatEventBus"/> bound to the given app-instance scope.
    /// </summary>
    /// <param name="appScope">
    /// Scope ID generated by <see cref="WebApp.Create"/> for this application instance.
    /// </param>
    public CatEventBus(Guid appScope) => _appScope = appScope;

    /// <summary>
    /// Broadcasts a <c>cat_status</c> event to every WebSocket client connected
    /// to the same <see cref="WebApp"/> instance as this bus.
    /// </summary>
    /// <param name="status">Current CAT connection state.</param>
    /// <param name="dialFrequencyMHz">
    /// Latest polled VFO-A frequency in MHz, or <c>null</c> when unavailable.
    /// </param>
    public void Publish(CatConnectionStatus status, double? dialFrequencyMHz)
        => WebSocketHub.BroadcastCatStatus(_appScope, status, dialFrequencyMHz);
}
