using OpenWSFZ.Abstractions;

namespace OpenWSFZ.Web;

/// <summary>
/// Public façade that allows <c>OpenWSFZ.Daemon</c> to publish decoded FT8 results
/// to all connected WebSocket clients without depending on the internal
/// <see cref="WebSocketHub"/> class directly.
///
/// <para>
/// Carries an <c>appScope</c> GUID (N6) so <see cref="WebSocketHub.BroadcastDecodes"/> only
/// delivers to sockets belonging to the same <see cref="WebApp"/> instance — mirrors
/// <see cref="CatEventBus"/>'s scope-guard pattern. Defaulted rather than required because
/// many tests construct this bus directly without a real <c>WebApp</c>/socket in play, where
/// the scope value is never actually consulted (<c>ActiveSockets.IsEmpty</c> short-circuits
/// first).
/// </para>
/// </summary>
public sealed class DecodeEventBus
{
    private readonly Guid _appScope;

    /// <summary>
    /// Creates a new <see cref="DecodeEventBus"/>, optionally bound to an app-instance scope.
    /// </summary>
    /// <param name="appScope">
    /// Scope ID generated by <see cref="WebApp.Create"/> for this application instance.
    /// Defaults to <see cref="Guid.Empty"/> for callers that never register a real socket.
    /// </param>
    public DecodeEventBus(Guid appScope = default) => _appScope = appScope;

    /// <summary>
    /// Broadcasts a <c>decode</c> event carrying <paramref name="results"/> to every
    /// WebSocket client currently connected to this bus's app-instance scope.
    /// </summary>
    /// <returns>
    /// A <see cref="Task"/> that completes when all per-socket sends have finished.
    /// Production callers may discard this for fire-and-forget; test callers should await it.
    /// </returns>
    public Task Publish(IReadOnlyList<DecodeResult> results)
        => WebSocketHub.BroadcastDecodes(_appScope, results);
}
