using OpenWSFZ.Abstractions;

namespace OpenWSFZ.Web;

/// <summary>
/// Public façade that allows <c>OpenWSFZ.Daemon</c> to publish a daemon-driven
/// <see cref="DecodeFilterState"/> change to all connected WebSocket clients without depending
/// on the internal <see cref="WebSocketHub"/> class directly
/// (<c>fix-decode-filter-new-value-admission</c>, design.md Decision 4). Mirrors
/// <see cref="DecodeEventBus"/>'s shape exactly, including the N6 <c>appScope</c> guard, so the
/// decode pump's new-value-admission auto-broadcast (a peer of <c>POST /api/v1/decode-filter</c>'s
/// existing broadcast) reaches only sockets belonging to this <see cref="WebApp"/> instance.
/// </summary>
public sealed class DecodeFilterEventBus
{
    private readonly Guid _appScope;

    /// <summary>
    /// Creates a new <see cref="DecodeFilterEventBus"/>, optionally bound to an app-instance
    /// scope.
    /// </summary>
    /// <param name="appScope">
    /// Scope ID generated by <see cref="WebApp.Create"/> for this application instance.
    /// Defaults to <see cref="Guid.Empty"/> for callers that never register a real socket.
    /// </param>
    public DecodeFilterEventBus(Guid appScope = default) => _appScope = appScope;

    /// <summary>
    /// Broadcasts a <c>decodeFilterChanged</c> event carrying <paramref name="state"/> to every
    /// WebSocket client currently connected to this bus's app-instance scope — identical in
    /// shape to the broadcast <c>POST /api/v1/decode-filter</c> already triggers, so no
    /// connected client can tell the two apart.
    /// </summary>
    public void Publish(DecodeFilterState state)
        => WebSocketHub.BroadcastDecodeFilterChanged(_appScope, state);
}
