namespace OpenWSFZ.Web;

/// <summary>
/// Public façade that allows <c>OpenWSFZ.Daemon</c> to broadcast spectrum data
/// to all connected WebSocket clients without depending on the internal
/// <see cref="WebSocketHub"/> class directly.
///
/// <para>
/// Carries an <c>appScope</c> GUID (N6) so <see cref="WebSocketHub.BroadcastSpectrum"/> only
/// delivers to sockets belonging to the same <see cref="WebApp"/> instance — mirrors
/// <see cref="DecodeEventBus"/>'s scope-guard pattern. Defaulted rather than required because
/// many tests construct this bus directly without a real <c>WebApp</c>/socket in play, where
/// the scope value is never actually consulted (<c>ActiveSockets.IsEmpty</c> short-circuits
/// first).
/// </para>
/// </summary>
public sealed class SpectrumEventBus
{
    private readonly Guid _appScope;

    /// <summary>
    /// Creates a new <see cref="SpectrumEventBus"/>, optionally bound to an app-instance scope.
    /// </summary>
    /// <param name="appScope">
    /// Scope ID generated by <see cref="WebApp.Create"/> for this application instance.
    /// Defaults to <see cref="Guid.Empty"/> for callers that never register a real socket.
    /// </param>
    public SpectrumEventBus(Guid appScope = default) => _appScope = appScope;

    /// <summary>
    /// True when at least one WebSocket client is currently connected.
    /// Used to gate FFT serialisation when no clients exist.
    /// </summary>
    public bool HasClients => WebSocketHub.HasClients;

    public void Publish(int[] bins) => WebSocketHub.BroadcastSpectrum(_appScope, bins);
}
