namespace OpenWSFZ.Web;

/// <summary>
/// Public façade that allows QSO controller services to broadcast
/// <c>txState</c> WebSocket events to all connected clients without depending on the
/// internal <see cref="WebSocketHub"/> class directly (FR-047).
///
/// <para>
/// Carries an <c>appScope</c> GUID (N6) so <see cref="WebSocketHub.BroadcastTxState"/> only
/// delivers to sockets belonging to the same <see cref="WebApp"/> instance — mirrors
/// <see cref="CatEventBus"/>'s scope-guard pattern. Defaulted rather than required because
/// many tests construct this bus directly without a real <c>WebApp</c>/socket in play, where
/// the scope value is never actually consulted (<c>ActiveSockets.IsEmpty</c> short-circuits
/// first). <see cref="PublishQsoReview"/> is unaffected — <c>BroadcastQsoReview</c> is out of
/// scope for this fix (see N6 dev-task §3.1).
/// </para>
/// </summary>
public sealed class TxEventBus : ITxEventBus
{
    private readonly Guid _appScope;

    /// <summary>
    /// Creates a new <see cref="TxEventBus"/>, optionally bound to an app-instance scope.
    /// </summary>
    /// <param name="appScope">
    /// Scope ID generated by <see cref="WebApp.Create"/> for this application instance.
    /// Defaults to <see cref="Guid.Empty"/> for callers that never register a real socket.
    /// </param>
    public TxEventBus(Guid appScope = default) => _appScope = appScope;

    /// <summary>
    /// Broadcasts a <c>txState</c> event carrying the new state, active role, partner
    /// callsign, arm state, and optional abort reason to every WebSocket client
    /// currently connected to this bus's app-instance scope.
    /// </summary>
    /// <param name="state">Raw enum name from <c>QsoState</c> or <c>CallerState</c>.</param>
    /// <param name="role"><c>"answerer"</c> or <c>"caller"</c>.</param>
    /// <param name="partner">
    /// Active partner callsign, or <c>null</c> when transitioning to Idle.
    /// </param>
    /// <param name="abortReason">
    /// Human-readable abort reason, or <c>null</c> for normal completion and routine
    /// Idle pushes (FR-UX-002).
    /// </param>
    public void Publish(
        string  state,
        string  role,
        string? partner,
        bool    autoAnswerEnabled,
        string? abortReason = null,
        bool    keying = false,
        string? lastTxMessage = null)
        => WebSocketHub.BroadcastTxState(
            _appScope, state, role, partner, autoAnswerEnabled, keying, abortReason, lastTxMessage);

    /// <inheritdoc/>
    public void PublishQsoReview(
        OpenWSFZ.Abstractions.QsoRecord record,
        string retainedTxPower,
        string retainedComment,
        string retainedPropMode)
    {
        var msg = new WsQsoReviewMessage(
            Type:              "qsoReview",
            Callsign:          record.PartnerCallsign,
            Grid:              record.PartnerGrid,
            RstSent:           record.RstSent,
            RstRcvd:           record.RstRcvd,
            StartUtc:          record.QsoStartUtc.ToString("O"),
            EndUtc:            record.QsoEndUtc.ToString("O"),
            FreqMHz:           record.DialFrequencyMHz,
            OperatorCallsign:  record.OperatorCallsign,
            RetainedTxPower:   retainedTxPower,
            RetainedComment:   retainedComment,
            RetainedPropMode:  retainedPropMode);

        WebSocketHub.BroadcastQsoReview(msg);
    }
}
